### ISSUE TITLE
Extract EfSpecificationEvaluator in own repository

### ISSUE THREAD

**Issue by mrukas** [ardalis/Specification#10]
Wouldn't it make sense to extract the specification evaluators in an own repository? It may lead to a cleaner separation. Now this repository has a direct dependency to EF Core which may not be necessary. A specification may be evaluated to EF queries, ODATA queries, file system access or whatever.

I think an own Nuget package per evaluator would be a great idea.

**Comment by ardalis** [comment]
That was the original plan but I opted to keep it simpler for now since the only evaluator I have to start is for EF Core and I didn’t want the complexity of maintaining many small interdependent packages slowing down initial progress.

But yes I’m open to that split now.

**Comment by mrukas** [comment]
I totally understand that. Keeping it simple at first makes sense.

**Comment by fiseni** [comment]
@mrukas I think this structure is partly my fault, and added to the confusion. The logic of the evaluator was within the repository implementation itself. I took it out into utility class simply based on esthetical reasons, but with time it became a separate "thing" I guess.
The evaluator on its own doesnt make much sense without the repository, and vice versa.
I would suggest the following.
- Abstract package "Specification", containing the base specification and the interfaces.
- Implementation packages "Specification.Efcore", containing the repository implementation along the spec evaluators.

**Comment by fiseni** [comment]
This is implemented in version 4. I'm closing the issue. If anyone has additional comments or suggestions, please feel free to reply or re-open the issue.
