### ISSUE TITLE
Consumers of the package sometimes get 'The call is ambiguous between the following methods or properties' error

### ISSUE THREAD

**Issue by ardalis** [ardalis/Specification#113]
Error:
```
Error: /home/runner/work/CleanArchitecture/CleanArchitecture/src/Clean.Architecture.Core/DatabasePopulator.cs(11,32): error CS0121: The call is ambiguous between the following methods or properties: 'IReadRepositoryBase<T>.ListAsync()' and 'IReadRepositoryBase<T>.ListAsync()' [/home/runner/work/CleanArchitecture/CleanArchitecture/src/Clean.Architecture.Core/Clean.Architecture.Core.csproj]
```

Example:
https://github.com/ardalis/CleanArchitecture/pull/165/checks?check_run_id=2194406249

This seems to have started when we introduced the separate interface for `IReadRepository<T>`.

**Comment by fiseni** [comment]
It's not an issue per se, but it's easy to get confused I guess. In the package, `IRepositoryBase<T>` inherits `IReadRepositoryBase<T>`. So, if the consumers explicitly inherit from both interfaces might lead to build errors. Also, if users want to define `IRepository` and `IReadRepository`, then for sure they will end up with conflicts.

We should define the following interfaces
- `IReadRepositoryBase<T>`
- `IWriteRepositoryBase<T>`
- `IRepositoryBase<T>` inheriting both read and write.

Users that need only one consolidated repository can define their interface as following
```c#
 public interface IRepository<T> : IRepositoryBase<T> where T : class
{
}
```

If anyone needs to have a read and consolidated repository, then
```c#
 public interface IReadRepository<T> : IReadRepositoryBase<T> where T : class
{
}

// Here the user inherits from his own read interface, and just add the write one
 public interface IRepository<T> : IReadRepository<T>, IWriteRepositoryBase<T> where T : class
{
}
```

**Comment by fiseni** [comment]
Now that I'm thinking, it shouldn't matter if you inheriting the same interface from various paths. Just look at `List` Definition
```
public class List<T> : ICollection<T>, IEnumerable<T>, IEnumerable, IList<T>, IReadOnlyCollection<T>, IReadOnlyList<T>, ICollection, IList
```

And `ICollection<T>` already inherits `IEnumerable<T>`. So, this shouldn't be an issue. Probably some subtle framework bug?

**Comment by ardalis** [comment]
Seems the issue occurred with 5.0.100 but not with 5.0.201 on the build server.

**Comment by ardalis** [comment]
This seems to be an issue with .NET 5 SDK 5.0.100 and not our package. Closing.
