### ISSUE TITLE
RepositoryBase improvements.

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#118]
Since we kind of started advocating the usage of the base repository implementations provided in this package, then we should perhaps fix a few stuff here.
If anyone has suggestions here please let us know. Also, if anyone thinks we should not make these changes, speak now :)

### Update method

The update method is implemented as follows

```c#
public virtual Task UpdateAsync(T entity, CancellationToken cancellationToken = default)
{
	dbContext.Entry(entity).State = EntityState.Modified;

	SaveChangesAsync(cancellationToken);
}
```

This is not very nice. If we set the state to modified, EF will consider the whole entity as modified, and regardless if you changed only one property, EF will produce SQL Update statements containing all columns. Practically we're not making use of the EF's change tracker. Having only SaveChangesAsync is more than enough. EF will figure out what is changed and produce a SQL Update statement accordingly.

There is a caveat here, and it all depends on how you actually use EF. If you're fetching the entity, mutate a state and save, then it's all good. But, if you try to update an entity that is not tracked by EF, then obviously it won't work. If we want to cover these cases, then we should utilize the `dbContext.Update()` method.

### GetById

We're utilizing `FindAsync` method here. But, there is no overload of this method which accepts the Id and CancellationToken. There is an option for CancellationToken if you provide a collection of Ids. That's what we're doing here, and it's an unnecessary allocation. Does anyone know why there is no such overload? It's an anyway fast operation, so no need for cancellationToken? Should we remove the token?

```c#
public virtual Task<T?> GetByIdAsync<TId>(TId id, CancellationToken cancellationToken = default) where TId : notnull
{
	return dbContext.Set<T>().FindAsync(new object[] { id }, cancellationToken: cancellationToken);
}
```

### Write actions

It's not uncommon to have a service that mediates between different aggregates. Apply some changes across aggregates, and then persist changes in a single transaction.
If users have this scenario, we might provide the ability to discard saving changes on a given "write" action. You do all changes, and in the end, you call `SaveChangesAsync` explicitly. It might be ambiguous usage since we practically implementing unit of work through repositories, but anyhow it's an option. And having the ability to switch off the SaveChanges, users can implement their own UoW if necessary.

```c#
public virtual async Task<T> AddAsync(T entity, bool saveChanges = true, CancellationToken cancellationToken = default)
{
	dbContext.Set<T>().Add(entity);

	if (saveChanges)
	{
		await SaveChangesAsync(cancellationToken);
	}

	return entity;
}
public virtual async Task UpdateAsync(T entity, bool saveChanges = true, CancellationToken cancellationToken = default)
{
	dbContext.Entry(entity).State = EntityState.Modified;

	if (saveChanges)
	{
		await SaveChangesAsync(cancellationToken);
	}
}
public virtual async Task DeleteAsync(T entity, bool saveChanges = true, CancellationToken cancellationToken = default)
{
	dbContext.Set<T>().Remove(entity);

	if (saveChanges)
	{
		await SaveChangesAsync(cancellationToken);
	}
}
public virtual async Task DeleteRangeAsync(IEnumerable<T> entities, bool saveChanges = true, CancellationToken cancellationToken = default)
{
	dbContext.Set<T>().RemoveRange(entities);

	if (saveChanges)
	{
		await SaveChangesAsync(cancellationToken);
	}
}
public virtual async Task SaveChangesAsync(CancellationToken cancellationToken = default)
{
	await dbContext.SaveChangesAsync(cancellationToken);
}
```

**Comment by Blackclaws** [comment]
I second the fact that unit of work is sometimes needed even if you try to avoid it. For example in our case we have an aggregate root called project. But we also have a function to move files between projects. We would like to preserve the identity of these files but efcore will not preserve identity if the delete and update statements aren't part of the same unit of work.

**Comment by ardalis** [comment]
Hmm, in the interests of following ISP and not having all consumers of these types have to depend on features/methods they don't necessarily need and may never call, maybe it would make sense to introduce a separate repository that includes UoW which could be used as-needed? In that case, how might be differentiate it via naming its interface/implementation differently?

`IUoWRepository` just rolls off the tongue...

Anyone have suggestions? We can certainly go with the above if nobody has a better solution/name. Its interface can inherit from the `IRepository<>` interface, probably. Its implementation probably needs to be separate, though.

**Comment by Blackclaws** [comment]
How about just adding a BeginTransaction, FinishTransaction to the repository, those would enable/disable the auto-save behaviour and the latter would initiate a save. That functionality wouldn't be too exposed and the consumers wouldn't see it in the existing interface.

**Comment by fiseni** [comment]
Just to make sure that there is no missunderstanding and that we're on the same page. This is what we have right now.

```c#
public interface IReadRepositoryBase<T> where T : class
{
    Task<T?> GetByIdAsync<TId>(TId id, CancellationToken cancellationToken = default) where TId : notnull;
    Task<T?> GetBySpecAsync<Spec>(Spec specification, CancellationToken cancellationToken = default) where Spec : ISingleResultSpecification, ISpecification<T>;
    Task<TResult> GetBySpecAsync<TResult>(ISpecification<T, TResult> specification, CancellationToken cancellationToken = default);
    Task<List<T>> ListAsync(CancellationToken cancellationToken = default);
    Task<List<T>> ListAsync(ISpecification<T> specification, CancellationToken cancellationToken = default);
    Task<List<TResult>> ListAsync<TResult>(ISpecification<T, TResult> specification, CancellationToken cancellationToken = default);
    Task<int> CountAsync(ISpecification<T> specification, CancellationToken cancellationToken = default);
}

public interface IRepositoryBase<T> : IReadRepositoryBase<T> where T : class
{
    Task<T> AddAsync(T entity, CancellationToken cancellationToken = default);
    Task UpdateAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteRangeAsync(IEnumerable<T> entities, CancellationToken cancellationToken = default);
    Task SaveChangesAsync(CancellationToken cancellationToken = default);
}
```

The proposed change has to do only with `IRepositoryBase<T>`, by adding an additional `saveChanges` parameter for the methods. The parameter should be optional, and if not set explicitly should have the same behavior as now.

```c#
public interface IRepositoryBase<T> : IReadRepositoryBase<T> where T : class
{
    Task<T> AddAsync(T entity, bool saveChanges = true, CancellationToken cancellationToken = default);
    Task UpdateAsync(T entity, bool saveChanges = true, CancellationToken cancellationToken = default);
    Task DeleteAsync(T entity, bool saveChanges = true, CancellationToken cancellationToken = default);
    Task DeleteRangeAsync(IEnumerable<T> entities, bool saveChanges = true, CancellationToken cancellationToken = default);
    Task SaveChangesAsync(CancellationToken cancellationToken = default);
}
```

How do you envision the new `IUoWRepository` interface?

**Comment by Blackclaws** [comment]
It won't have the same behaviour if its before cancellation token however. If you use the repository as is right now and push another parameter in front of an existing one people that update will have errors in their existing code.

**Comment by fiseni** [comment]
Ah, that's a minor issue, we can put it in the end. You're right.
I see the usage as following

```c#
var customer = await customerRepository.GetBySpecAsync(new CustomerByNameWithStoresSpec(customerName));

// Do the update

await customerRepository.UpdateAsync(customer, saveChanges: false);

// Do something else with another aggregate

await customerRepository.SaveChangesAsync();
```

**Comment by ardalis** [comment]
Here was my thought:

```csharp
public interface IRepositoryBase<T> : IReadRepositoryBase<T> where T : class
{
    Task<T> AddAsync(T entity, CancellationToken cancellationToken = default);
    Task UpdateAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteRangeAsync(IEnumerable<T> entities, CancellationToken cancellationToken = default);
}
public interface IUoWRepositoryBase<T> : IRepositoryBase<T> where T : class
{
    Task SaveChangesAsync(CancellationToken cancellationToken = default);
}
```

The trick with this approach is, because it inherits from IRB you would expect that something implements IRB already could also implement IUOWRB by just adding a method (and changing nothing else). This would be incorrect, since the existing implementation would have to have been doing a SaveChanges per method.

So, probably this is better:

```csharp
public interface IUoWRepositoryBase<T> : IReadRepositoryBase<T> where T : class
{
    Task<T> AddAsync(T entity, CancellationToken cancellationToken = default);
    Task UpdateAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteRangeAsync(IEnumerable<T> entities, CancellationToken cancellationToken = default);
    Task SaveChangesAsync(CancellationToken cancellationToken = default);
}
```

Now since it doesn't share an inheritance ancestor with IRB it should be (more) clear that it's a totally separate way of doing things.

It's probably worth noting that this doesn't support every UoW/Transaction scenario. For instance, there will no doubt be a need for a service that works with two different aggregates and wants to enlist them in the same transaction in an obvious manner. This one will "work" but you'll end up committing the transaction for both repositories by calling SaveChanges on either one of them, which isn't intuitive.

A more intuitive approach would be something like this:

```csharp
public interface IUoWRepositoryBase<T> : IReadRepositoryBase<T> where T : class
{
    Task<T> AddAsync(T entity, CancellationToken cancellationToken = default);
    Task UpdateAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteAsync(T entity, CancellationToken cancellationToken = default);
    Task DeleteRangeAsync(IEnumerable<T> entities, CancellationToken cancellationToken = default);
    IUnitOfWork UnitOfWork { get; }
}
public interface IUnitOfWork
{
  void Commit();
  // optionally put transaction start/rollback/commit methods here
}
```

At its simplest it just exposes the UnitOfWork being used. This would be injected into the constructor of the instance of the repository (but you can't put constructor requirements in an interface). The property probably won't get used much but does make clear the instance is required. The repository has no code at all for saving - only the IUnitOfWork implementation has that code. DI can provide one which can typically be Transient scoped so that whatever unit of work is created, it will need to be committed (or not) in the service that requests it. Alternately, some devs may prefer a Scoped UOW which they might then automatically open and commit using filters or middleware wrapped around their request handlers.

Thoughts?

**Comment by fiseni** [comment]
I see now what you meant. You want to provide these constructs out of the box, as part of the package.

Initially, my intention was not to introduce breaking changes and just to sneak in the possibility of implementing these concepts by the users in their codebases. If you need UoW, sure go and implement it, you can use the repos and suppress the save behavior of the methods.

If we want to ship it, then your suggestions work. I do agree. We have to make few breaking changes perhaps. We have to remove `SaveChangesAsync` from the `IRepositoryBase`, otherwise, it will create confusion.
There is a downside though, we'll have a lot of constructs. Not sure if all this can lead to some confusion. Probably we'll need more detailed documentation.
- IReadRepositoryBase
- IRepositoryBase
- IUoWRepositoryBase
- IUnitOfWork
- RepositoryBase - implements `IReadRepositoryBase` and `IRepositoryBase`
- UoWRepositoryBase - implements `IUoWRepositoryBase` and `IRepositoryBase`
- UnitOfWork - implements `IUnitOfWork`

Other than that, in the majority of cases, 90% of cases, they will have atomic actions and won't need the UoW. So instead of one-liner, now they will have the following all the time
```c#
await customerRepository.UpdateAsync(customer);
await customerRepository.UnitOfWork.Commit();
```
In order to avoid doing that, they might start using both `IRepositoryBase` and `IUoWRepositoryBase`. Perhaps they will inject both repos in the same service on some occasions. And they can end up in a mess.

Honestly, I have no strong opinion here. It works for me either way. It's up to the consumers.

Oh, we have one more option. Not to do anything and leave it as it is 😄  If anyone needs all this, they can have their own implementations.

**Comment by Blackclaws** [comment]
I think introducing the IUoWRepository as an additional repository type that is separate will definitely lead to people using both implementations, which might not be the worst thing but also not the best thing. 
What exactly is the drawback of implementing a sort of transaction like behaviour in the RepositoryBase that just isn't used by whoever doesn't need repositories? Or is that cluttering the API too much?

I also think its fair game to say that this simply isn't in scope of this library and whoever needs it can implement it themselves in any way they see fit.

**Comment by ConnerOrth** [comment]
My 2 cents, as already suggested by both @fiseni and @Blackclaws. 
Adding more different 'flavours' will most likely only serve to add more confusion.
Keep it the way it is currently, but perhaps put a section in the documentation/readme.
That either links to this discussion/brainstorm or that just based on the input here explains/guides people.
Then if they need an UoW implementation they should be able to build it themselves, for their specific use case.

**Comment by fiseni** [comment]
Closing this issue. If anyone needs something different, all repository methods are marked as virtual, so they can override and change them as they see fit.

**Comment by davidhenley** [comment]
I ended up overriding the Update method to call dbContext.Update(entity) instead (because I'm dealing with Address owned properties that aren't picked up with the one currently used.) Are there any downsides to this?

**Comment by fiseni** [comment]
No, actually that's the correct way of doing it. We shouldn't set the state manually. Probably, we'll update the implementation to use `dbContext.Update()` instead in the next release.
