### ISSUE TITLE
Duplicate Azure DevOps Build as GitHub Action

### ISSUE THREAD

**Issue by ardalis** [ardalis/Specification#12]
Take the work being done in Azure DevOps currently and migrate it to do the same thing in GitHub actions.

**Comment by feliperomero3** [comment]
@ardalis do you mean to replace your current Azure DevOps Build Pipeline with GitHub Actions?

**Comment by ardalis** [comment]
Yes unless there is a good reason not to do so.

**Comment by ardalis** [comment]
Done!
