### ISSUE TITLE
Should EF package 4.2 be compatible with Spec packages 5.1?

### ISSUE THREAD

**Issue by MisinformedDNA** [ardalis/Specification#120]
I was using `Ardalis.Specification` and `Ardalis.Specification.EntityFrameworkCore` v4.2 and everything worked fine.

But if `Ardalis.Specification` is updated to v5.1 and `Ardalis.Specification.EntityFrameworkCore` is not, then I get a runtime error:

> 'Method 'AddAsync' in type 'XXXX.Infrastructure.Data.EfRepository`1' from assembly 'XXXX.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

Per the dependencies, [Ardalis.Specification.EntityFrameworkCore v4.2.0](https://www.nuget.org/packages/Ardalis.Specification.EntityFrameworkCore/4.2.0) requires `Ardalis.Specification (>= 4.2.0)`, but maybe this is no longer true?

Is there a way to fix the dependency requirements?

**Comment by fiseni** [comment]
The new v5 contains breaking changes and is not backward compatible. Moving forward, I don't expect to have huge changes that will affect the backward compatibility (never say never 😄 )

The dependency requirements for `Ardalis.Specification.EntityFrameworkCore` v4.2.0 should be `Ardalis.Specification` (>= 4.2.0 AND < 5). I don't know if we can set the max limit somehow for old packages.

Is there anything that prevents you to update the plugin package to v5.1?

**Comment by MisinformedDNA** [comment]
Yep, I'm working on a WinForms app targeting 4.8. I hope to update it to .NET 5/6 in the future, but until then, I'm stuck on .NET Standard 2.0 and EF Core 3.X.

**Comment by fiseni** [comment]
Yep, I was anticipating this scenario. Maybe we can add a separate EFCore3 plugin package. @ardalis any thoughts?
Basically, we'll have the following:
- EntityFramework6
- EntityFramework Core - this will always target the latest version
- EntityFramework Core3 - this will target the EFCore3 version specifically.

So, the idea is we always keep the EF Core up to date, and whenever there is a requirement we may release specific version.

**Comment by MisinformedDNA** [comment]
@fiseni @ardalis Mind if I take a stab at it?

**Comment by ardalis** [comment]
I don't know when I'd have time to look into it, so please if you like that would be helpful. Thanks!

**Comment by MisinformedDNA** [comment]
Done. https://github.com/ardalis/Specification/pull/123
