### ISSUE TITLE
PostProcessingAction on Single record

### ISSUE THREAD

**Issue by David-Moreira** [ardalis/Specification#125]
Hello,

Is it possible to extend **PostProcessingAction** to also work on Single output queries?
For example:
![image](https://user-images.githubusercontent.com/22283161/118482854-38c7ad00-b70d-11eb-9010-01050399ed3e.png)
![image](https://user-images.githubusercontent.com/22283161/118482875-3ebd8e00-b70d-11eb-89a4-c7f5bf909f47.png)

Is not calling into the delegate I set in the PostProcessingAction as I believe that is only called on ListAsync, right?

**Comment by David-Moreira** [comment]
Nvm.. I see the use case for **PostProcessingAction** is another... I don't think you can quite get that from just looking at the exposed API. Maybe if the method was documented, that could help a bit. 

I just need to use the Getter and run it myself after retrieving the data from the data source. (I'm not using the provided Repository abstractions, I just took a look and that's what you guys are doing. :P)
Even so, a **PostProcessingAction** for a Single record, would be great, right?

Thanks!

**Comment by fiseni** [comment]
Hey @David-Moreira,

The `PostProcessingAction` (formerly `InMemory`) is a feature that offers the ability to do some custom/additional manipulation after the data is retrieved from the data store. There are some details in this [PR](https://github.com/ardalis/Specification/pull/56).

Yes, initially we provided this only for the collections, but having it for the single entity makes sense too. We might add an overload, and the contract might look like this

```c#
Func<IEnumerable<T>, IEnumerable<T>>? PostProcessingAction { get; }
Func<T, T>? PostProcessingAction { get; }
```

For now, you can use the following hack, and apply it to your repository

```c#
public virtual async Task<T?> GetBySpecAsync<Spec>(Spec specification, CancellationToken cancellationToken = default) where Spec : ISpecification<T>, ISingleResultSpecification
{
    var queryResult = await ApplySpecification(specification).FirstOrDefaultAsync(cancellationToken);

    return specification.PostProcessingAction is null 
                ? queryResult 
                : specification.PostProcessingAction(new T[] { queryResult }).First();
}
```

**Comment by David-Moreira** [comment]
@fiseni 
Thanks for the prompt response! Alright. 
Yea I added that hack with some null handling because of FirstOrDefaultAsync. Will switch to the overload if you do end up adding it.

Thanks!

**Comment by fiseni** [comment]
Great!

I meant overload for the builder. The above approach does not make sense, we can't have two different properties with the same name. My bad. There is no such thing as property overloading 😅

**Comment by David-Moreira** [comment]
I honestly did not even notice, but I understood what you meant. Gotcha. Haha

**Comment by ardalis** [comment]
I'll make a note to update our docs to cover this better.
