### ISSUE TITLE
Consider Covariance and Contravariance in Repository types

### ISSUE THREAD

**Issue by ardalis** [ardalis/Specification#128]
ReadRepository types can be covariant; WriteRepository types (if we split them off - currently we don't have this) can be contravariant.

https://github.com/ardalis/Specification/blob/main/ArdalisSpecification/src/Ardalis.Specification/IReadRepositoryBase.cs
https://github.com/ardalis/Specification/blob/main/ArdalisSpecification/src/Ardalis.Specification/IRepositoryBaseOfT.cs

**Comment by ardalis** [comment]
Actually since our interfaces are async and thus return tasks, they cannot use covariance:
https://stackoverflow.com/a/38140402/13729

**Comment by fiseni** [comment]
Covariance and contravariance are really useful in various scenarios and we're already using covariance for our builders here. Do you see any compelling reason or any scenario of utilizing them with repositories? I assume you're having shared entities perhaps? 

If you define the generic parameter as contravariant
```c#
public interface IWriteRepository<in T>
{
    void Add(T entity);
}
```
Then, that won't enable us to pass the `CommonEntity` as an argument for `IWriteRepository<Customer>` repository methods. It will just enable us to do the following, as an example.

```c#
var list = new List<IWriteRepository<Customer>>
{
    new CommonWriteRepository(dbContext),
    new CustomerWriteRepository(dbContext)
};
```

**Comment by ardalis** [comment]
Just something I was considering as I was working on my C# Generics pluralsight course. :)

The case for contravariance would be if I had an instance of IWriteRepository<Person> and I had a method like this:

```
public void AddCustomer(IWriteRepository<Customer> repo)
{
  repo.Add(new Customer());
}
```

Assuming Customer : Person. Without contravariance I can't pass in an instance of IWriteRepository<Person> but with it I could.

Nobody has requested this functionality, though, and inheritance of entities has limited usefulness and usually requires more custom code than this simple example shows, so...

In terms of covariance, though, I did find that MorseCode.ITask nuget package does a good job of allowing you to have covariant task returns in your readonly interfaces. They return `ITask<T>` instead of `Task<T>` but the library includes helpers to convert.

**Comment by fiseni** [comment]
Ah yes, that's a valid case. I won't ask why? :) Probably you have a valid scenario.
You may face issues with EF, not sure though. EF Core 5 works with runtime types I think, so it might resolve it correctly.

**Comment by ardalis** [comment]
I don't think this is really that useful, so closing.
