### ISSUE TITLE
Select Specifications

### ISSUE THREAD

**Issue by pynej** [ardalis/Specification#130]
The documentation isn't very clear and the default EfRepository doesn't actually support Select specifications

The default suggested code is:
```
private IQueryable<T> ApplySpecification(ISpecification<T>? spec)
 {
    return spec == null ? _dbContext.Set<T>() : SpecificationEvaluator.Default.GetQuery(_dbContext.Set<T>().AsQueryable(), spec);
}
```
When in fact it has to be changed to:
```
private IQueryable<T> ApplySpecification(ISpecification<T>? spec)
{
    if (spec == null)
    {
         return _dbContext.Set<T>();
     }
     var query = SpecificationEvaluator.Default.GetQuery(_dbContext.Set<T>().AsQueryable(), spec);
     return spec is ISpecification<T, T> specFiltered ? query.Select(specFiltered.Selector) : query;
}
```
(We don't necessarily want to create a second signature as that would expose more variations of the selectors.)

Also the documentation coesn't make it very clear that you won't see .Select unless you change to:
```
public MySpec : Specification<XXSource, XXSource>

**Comment by fiseni** [comment]
Hi @pynej,

You're right, we lack good documentation. We started working on it, but we've been busy lately, sorry. Any help or contributions are more than welcome.

As for the selector functionality, the design is based on 2 premises:
- The `Select` expressions should be written as part of the specification (not passed in the repo methods).
- We should provide a strongly-typed experience. No casting should be required or utilized after the data is retrieved. Simply said, the repository should be able to infer the result type from the specification somehow.

That said, if you want to use `Select` you should:
- Define your return type in the specification by inheriting from `Specification<T, TResult>`, where `TResult` is the return type of the selector expression. We also ensure in our builders that you can't use the feature if you have not defined the `TResult` parameter.
- Once you have done that, you don't have to do anything else and the rest of the infrastructure should automatically infer the result type and provide the correct output. Not sure to which repository implementation you're referring, but you can find the provided base repository [here](https://github.com/ardalis/Specification/blob/main/ArdalisSpecificationEF/src/Ardalis.Specification.EF/RepositoryBaseOfT.cs). You can notice we have overloads for `ListAsync` and `GetBySpec` methods which accept `ISpecification<T, TResult>` and return `TResult` type, hence providing the correct result type. Also, you can notice we have two different `ApplySpecification` methods which apply the correct behavior.
```c#
protected virtual IQueryable<T> ApplySpecification(ISpecification<T> specification, bool evaluateCriteriaOnly = false)
{
	return specificationEvaluator.GetQuery(dbContext.Set<T>().AsQueryable(), specification, evaluateCriteriaOnly);
}

protected virtual IQueryable<TResult> ApplySpecification<TResult>(ISpecification<T, TResult> specification)
{
	if (specification is null) throw new ArgumentNullException("Specification is required");
	if (specification.Selector is null) throw new SelectorNotFoundException();

	return specificationEvaluator.GetQuery(dbContext.Set<T>().AsQueryable(), specification);
}
```

**Comment by pynej** [comment]
To clarify, I was using the specifications. The issue was in EF6 when we call SpecificationEvaluator.Default.GetQuery() in the base repository it doesn't attach the select filters and it took me a long while to figure out I had to do it myself.

Also in my example we are just mapping the items back to the original object witch totally works, so don't take that feature away :)

**Comment by pynej** [comment]
Hu, i guess i started form https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/EfRepository.cs and that was what had the issue, but that is in a different project.

**Comment by fiseni** [comment]
I see. That's quite an old implementation, and there is no support for the Select there. Probably the demo app doesn't use selectors, so it was not updated accordingly. 
Thanks for the feedback. The app might need a update.
