### ISSUE TITLE
Setting EnableCache throws MissingMethod 

### ISSUE THREAD

**Issue by fspataro** [ardalis/Specification#132]
Hi, 
I have a simple Spec built to test the caching feature.  When I enable the caching, I'm getting the following error:

System.MissingMethodException: Method not found: 'System.String Ardalis.GuardClauses.GuardClauseExtensions.NullOrEmpty(Ardalis.GuardClauses.IGuardClause, System.String, System.String)'.
   at Ardalis.Specification.SpecificationBuilderExtensions.EnableCache[T](ISpecificationBuilder`1 specificationBuilder, String specificationName, Object[] args)

My Spec class:

```
public class AnnouncementWithTagsSpec: Specification<Announcement>
	{
		public AnnouncementWithTagsSpec() 
		{
			Query
				.Include(a => a.AnnouncementTags)
				.EnableCache(nameof(AnnouncementWithTagsSpec), "*");
		}
	}

```

Version: 5.1.0  reference 3.2.0
I also have GaurdClauses installed as a package 3.2.0

**Comment by fiseni** [comment]
This is weird. It happens here

```C#
public static ISpecificationBuilder<T> EnableCache<T>(
	this ISpecificationBuilder<T> specificationBuilder,
	string specificationName, params object[] args) where T : class
{
	Guard.Against.NullOrEmpty(specificationName, nameof(specificationName));

	specificationBuilder.Specification.CacheKey = $"{specificationName}-{string.Join("-", args)}";

	specificationBuilder.Specification.CacheEnabled = true;

	return specificationBuilder;
}
```

The exception is MissingMethodException, so it's like `NullOrEmpty` is missing. I just checked, the specification package depends on GuardClauses v.3.1.0. If you have installed explicitly v3.2.0, and if there are breaking changes, might affect perhaps? Can you do some further debugging? Try with 3.1.0.

**Comment by fspataro** [comment]
I'll do a clean and reset the packages and see what happens.  VS is showing 5.1.0 references 3.2.0

![image](https://user-images.githubusercontent.com/5933821/122446871-60a26e80-cf60-11eb-93cb-3cf186f859b8.png)

**Comment by fspataro** [comment]
@fiseni thanks! I removed the reference to 3.2.0 in both the Core and Web project, reset to 3.1.0 and did a clean ... now it works.

**Comment by fiseni** [comment]
Honestly it's a bit weird. That exception is usually thrown if you use reflection.
I don't know what changes GuardClauses 3.2.0 contain, but it's worth checking it out. @ardalis
