### ISSUE TITLE
Specification With Many-to-Many and Where Clause

### ISSUE THREAD

**Issue by andrewwilkin** [ardalis/Specification#133]
I realise this may fall outside of the design goals of Specification. I have two Aggregate Routes with a Many-to-Many relationship configured in EF.

In EF I can do something like this:

```csharp
            var jobTitles = await JobTitles
                .Include(j => j.Industries)
                .Where(j => j.Industries.All(i => i.Id == industryId))
                .ToListAsync();
```

Is there a way of doing this with a specification (other than creating the mapping table explicitly like in EF Core 3.x)?

**Comment by andrewwilkin** [comment]
For context what ideally I would like to do is apply order by, skip and take to the collection from the other side (Industries). 

Something like:

```csharp
Query
    .Includes(industry => industry.JobTitles.OrderBy(x => x.Name).Skip(10).Take(10))
    .Where(industry => industry.id == industryId)
```

The reason is I want to use it to do a paginated query for an endpoint like:
/api/industries/{industryId:guid}/jobtitles?page=2&pageSize=20

**Comment by fiseni** [comment]
Hi @andrewwilkin,

Which version of the Specification package are you using? Starting with v5 you can do this with specifications. You can even use filtered includes. Whatever EF supports inside Include or Where clauses, it should work. Did you have any issues?

**Comment by andrewwilkin** [comment]
Hi @fiseni 

Using Specification 5.1.0. Honestly don't know what I was doing wrong at the weekend (facepalm) as just tried this:

```csharp
        public JobTitlesForIndustryIdSpec(JobTitlesByIndustryIdFilter filter)
        {
            Query
                .Include(j => j.Industries.Where(x => x.Id == filter.IndustryId))
                .Where(j => j.Industries.All(x => x.Id == filter.IndustryId))
                .OrderBy(j => j.Name)
                .Skip(filter.CalculateSkip())
                .Take(filter.CalculateTake());
        }
```

And that seems to work fine, quite possibly was Intellisense that stopped working.

**Comment by fiseni** [comment]
Ok then great :) I'm closing the issue.
