### ISSUE TITLE
Feature Request: Query 2 tables using single specification

### ISSUE THREAD

**Issue by julian-altech** [ardalis/Specification#137]
I am trying write the following query (well this is the simplified version) using specifications and I'm wondering if there is a better way:

```csharp 
private record UserGroupInfo
{
    public string ID { get; init; }
    public string Name { get; init; }
}

var usersQuery = _dbContext.Users
   .Where(u => u.UserName.Contains(search))
   .Select(u => new UserGroupInfo { ID = u.UserName, Name = u.UserName });
var groupQuery = _dbContext.Roles
    .Where(r => r.Name.Contains(search))
    .Select(r => new UserGroupInfo { ID = r.Id, Name = r.Name });
var results = await usersQuery.Concat(groupQuery).ToArrayAsync();
```

And so far I've managed to write it as the following:

```csharp
var usersSearch = _dbContext.Users.WithSpecification(new UserAndGroupSearchSpecification.User(request.Search));
var groupsSearch = _dbContext.Roles.WithSpecification(new UserAndGroupSearchSpecification.Group(request.Search));

var dbResults = await usersSearch.Concat(groupsSearch).ToArrayAsync();
```

by using the following specifications:

```csharp
public class UserAndGroupSearchSpecification
{
    public class User : Specification<ApplicationUser, UserGroupInfo>
    {
        public User(string search)
        {
            Query.Where(u => u.UserName.Contains(search));
            Query.Select(u => new UserGroupInfo() { ID = u.Id, Name = u.UserName });
        }
    }

    public class Group : Specification<ApplicationRole, UserGroupInfo>
    {
        public Group(string search)
        {
            Query.Where(g => g.Name.Contains(search));
            Query.Select(u => new UserGroupInfo() { ID = u.Id, Name = u.Name });
        }
    }
}
```

And creating the extra extension method (which would be useful to add into the framework itself):
```csharp
public static IQueryable<TResult> WithSpecification<TSource, TResult>(this IQueryable<TSource> source, ISpecification<TSource, TResult> specification, ISpecificationEvaluator? evaluator = null)
    where TSource : class
    where TResult : class
{
    return (evaluator ?? SpecificationEvaluator.Default).GetQuery(source, specification);
}
```

And all this works a-ok, but what I'd like to be able to do is have my UserAndGroupSearchSpecification be the only specification that my controller needs to worry about so I can pass it to my repository and not need to use the database context. 

What I'm using is the same as [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/EfRepository.cs) so while I could implement this myself and create a method which can take multiple specifications it no longer fits with how everything else works and I'd rather a cleaner way.

Is there a better way of doing this?

Also with this example you cant chain .Where().Select() as there is no `ISepcificationBuilder<T, TResult> Where` extension

**Comment by Huacnin** [comment]
Dear Julian,
By reviewing your question, I was able to solve a problem that arose when listing the products in an application.
The specs are a great way to reduce code repetition.
It helped me figure this out.
`public class PageProducts : Specification<Product, ProductDto>
    {
        public PageProducts(int pageSize, int pageNumber, string nombre, string codigo)
        {
            Query
                .OrderByDescending(x => x.Id)
                .Skip((pageNumber -1) * pageSize)
                .Take(pageSize);
            
            Query
            .Select(x => new ProductDto() {
                Id = x.Id,
                IdCategory = x.IdCategory, 
                Category = x.Categorys.Nombre,
                IdDocument = x.IdDocument,
                Document = x.Documents.Nombre,
                Codigo = x.Codigo,
                Nombre = x.Nombre,
                UM = x.UM,
                PrecioCompra = x.PrecioCompra,
                PrecioVenta = x.PrecioVenta,
                Stock = x.Stock,
                Estado = x.Estado
            });

            if(!string.IsNullOrEmpty(nombre))
            {
                Query.Search(x => x.Nombre, "%" + nombre + "%");
            }

            if(!string.IsNullOrEmpty(codigo))
            {
                Query.Search(x => x.Codigo, "%" + codigo + "%");
            }
        }

    }`
Thank you

**Comment by Huacnin** [comment]
Dear Julian,
By reviewing your question, I was able to solve a problem that arose when listing the products in an application.
The specs are a great way to reduce code repetition.
It helped me figure this out.
`Query
            .Select(x => new ProductDto() {
                Id = x.Id,
                IdCategory = x.IdCategory, 
                Category = x.Categorys.Nombre,
                IdDocument = x.IdDocument,
                Document = x.Documents.Nombre,
                Codigo = x.Codigo,
                Nombre = x.Nombre,
                UM = x.UM,
                PrecioCompra = x.PrecioCompra,
                PrecioVenta = x.PrecioVenta,
                Stock = x.Stock,
                Estado = x.Estado
            });
`
Thank you

**Comment by prabhpahul** [comment]
Did we figure a way out? We are in similar situation where we want to have row level security while fetching records, depending upon the role and claims. For ex: A manager can see all the documents of their team, A basic role user can see only theirs and admin can see all the documents. Is there a way to use Strategy or a chaining pattern?

**Comment by julian-altech** [comment]
@prabhpahul 

Yes I did find a better way in the end, it does have a caveat where you need to specify the starting entity to query on, but here's a simplified version of what I did:

Create the following classes
```c#
public interface IQueryableAccessor
{
	IQueryable<T> GetQueryable<T>() where T : class;
}
public interface ISpecificationTransform<T, TResult> : ISpecification<T, TResult>
{
	IQueryable<TResult> Transform(IQueryable<T> query, IQueryableAccessor queryableAccessor);
}
public abstract class SpecificationTransform<T, TResult> : Specification<T, TResult>, ISpecificationTransform<T, TResult>
{
	public abstract IQueryable<TResult> Transform(IQueryable<T> query, IQueryableAccessor queryableAccessor);
}
```

Then using the following specification (non functioning but it shows the theory how to use it):
```c#
public class MyTransformingQuerySpecification : SpecificationTransform<User, UserGroupInfo>
{
	private int _itemId;
	private string? _someValue;
	public MyTransformingQuerySpecification(int itemId, string? someValue)
	{
		Query.Where(u => u.SomeProp == itemId)
			.Include(u => u.Roles)
			.AsSplitQuery();

		_itemId = itemId;
		_someValue = someValue;
	}

	public override IQueryable<UserGroupInfo> Transform(IQueryable<User> query, IQueryableAccessor queryableAccessor)
	{
		var rolesQ = queryableAccessor.GetQueryable<ApplicationRole>();

		IQueryable<UserGroupInfo> q = query
			.Select(u => new UserGroupInfo())
			.Concat(
				rolesQ.Where(r => r.SomeProp == _someValue)
					.Select(r => new UserGroupInfo())
			);

		return q;
	}
}
```

To tie these parts together you need to make a custom specification evaluator like so:
```c#
internal class SpecificationEvaluator : Ardalis.Specification.EntityFrameworkCore.SpecificationEvaluator
{
	private IQueryableAccessor _queryAccessor;
	public SpecificationEvaluator(DbContext context) =>
		_queryAccessor = context;


	public override IQueryable<TResult> GetQuery<T, TResult>(IQueryable<T> query, ISpecification<T, TResult> specification)
	{
		if (specification is ISpecificationTransform<T, TResult> transformerSpec)
		{
			IQueryable<T> q = GetQuery(query, (ISpecification<T>)specification);
			return transformerSpec.Transform(q, _queryAccessor);
		}

		return base.GetQuery(query, specification);
	}
}
```

You then need to tell your repository to use this evaluator, if you are using the [`RepositoryBase<T>`](https://github.com/ardalis/Specification/blob/73693ac1b7ada2ac889c89c1e1b7882f19f566cb/Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs#L22) and injecting `IAsyncRepository<T>` in your controllers then below will work for you

```c#
public class EfRepository<T> : RepositoryBase<T>, IAsyncRepository<T> where T : class
{
	protected readonly DbContext _dbContext;
	private readonly ISpecificationEvaluator _evaluator;

	public EfRepository(DbContext dbContext) : this(dbContext, new SpecificationEvaluator(dbContext)) { }
	public EfRepository(DbContext dbContext, ISpecificationEvaluator evaluator) : base(dbContext, evaluator)
	{
		_dbContext = dbContext;
		_evaluator = evaluator;
	}

	///<inheritdoc/>
	protected override IQueryable<TResult> ApplySpecification<TResult>(ISpecification<T, TResult> specification)
	{
		if (specification is null) throw new ArgumentNullException("Specification is required");
		if (specification.Selector is null && specification is not ISpecificationTransform<T, TResult>) throw new SelectorNotFoundException();

		return _evaluator.GetQuery(_dbContext.Set<T>().AsQueryable(), specification);
	}
}
```

Finally on your DbContext implement `IQueryableAccessor` as follows:
```c#
public IQueryable<T> GetQueryable<T>() where T : class =>
            Set<T>();
```

**Comment by ardalis** [comment]
Closed as inactive.
