### ISSUE TITLE
Can I do multi spec?

### ISSUE THREAD

**Issue by ShadyNagy** [ardalis/Specification#139]
```csharp
  var spec = new ProjectByNumberSpecification("1234")
      .And(new ProjectByStatusSpecification("M"))
      .And(new ProjectByTypeSpecification("X"));
  var projects = await _repository.ListAsync<CalendarStatus, string>(spec);
```

**Comment by fiseni** [comment]
Hi @ShadyNagy,

No, we don't have that feature. The composite specifications make more sense for the classic specifications (a.k.a Fowler's specifications), and not so much for query specifications. In our case of queries, there are features that won't "compose" well. Think of Take, Skip, Select, Order, etc. What if the specifications you're trying to compose contain any of those states. Which one will be considered relevant? We'll need to introduce precedence rules, and will just complicate things and introduce bugs in user's codebases. The composition makes more sense only for "filtering" features (Where, Search, etc.).

There was some discussion in these issues #122 and [here](https://github.com/ardalis/Specification/issues/111#issuecomment-803461749).

**Comment by ShadyNagy** [comment]
@fiseni 
Thanks so much.
