### ISSUE TITLE
Update all Nuget dependencies and publish version 5.2.0

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#147]

**Comment by MisinformedDNA** [comment]
We should also update the .NET SDK's in the workflows to be '5.0.x'.

**Comment by fspataro** [comment]
Reminder to check that GuardClauses 3.1/3.2 issue : #132

**Comment by fiseni** [comment]
Thanks for bringing this up. That was a weird issue you had. Didn't have time to thoroughly analyze it.
Anyhow, I see we've been using GuardClauses in a single place only, so I just removed that dependency altogether.
