### ISSUE TITLE
[Question] If I needed to return total count for pagination, where is the best place to implement?

### ISSUE THREAD

**Issue by davidhenley** [ardalis/Specification#156]
If I am using pagination to skip and take based on page size, but still need to return total items to the client, where should I implement this?

I want to run count after the where filter so I get the actual count of items returned from the search but before my pagination.

In the specification? or run Count() on the entire table first then use the specification? 

Do I need a filter specification, and then another pagination specification?

```
        public GetCustomersForListSpecification(QueryParams query)
        {
            if (!string.IsNullOrWhiteSpace(query.Filter))
                Query.Where(x => x.Name.Contains(query.Filter));

           **********
           NEED TO CALCULATE TOTAL COUNT HERE BEFORE PAGINATION
           **********

            Query
                .Select(x => new CustomerForListResponse
                {
                    Id = x.Id,
                    Name = x.Name
                })
                .Skip((query.Page - 1) * query.PerPage)
                .Take(query.PerPage);
        }
```

I was using this on the IQueryable:

```
var source = _context.Customers.Where(x => x.Name.Contains(query.Filter));
var count = await source.CountAsync();
var items = await source.Skip((query.Page - 1) * query.PerPage).Take(query.PerPage).ToListAsync();
```

Is this a job for an evaluator? I'm trying to find documentation on this

**Comment by davidhenley** [comment]
Duplicate #134

**Comment by davidhenley** [comment]
Can we add this to docs?

**Comment by fiseni** [comment]
Here is the issue #135. I tried to elaborate it, we'll need to add it to the docs.

**Comment by davidhenley** [comment]
Thanks @fiseni I’m playing with it now. Are the 2 YouTube videos currently the best way to learn more about extending the specs and evaluators?

**Comment by fiseni** [comment]
Not really to be honest. Perhaps we need to create a new video, a planned one :) We recorded the last ones on the fly with no particular agenda.

I know we're lacking good docs. We started working on it, but we're far from finished.
https://ardalis.github.io/Specification/

**Comment by davidhenley** [comment]
OK, thank you! Once I understand everything going on I'll see if I can create some PR's!

**Comment by ardalis** [comment]
If you want to add/update anything in the docs, they're just markdown files here:
https://github.com/ardalis/Specification/tree/main/docs

Thanks!

**Comment by tnlthanzeel** [comment]
hi all. im having a scenario where i start the specification from the aggregate root and include children with skip and take. it works fine. but how can i get the totalrecord count of the children using this library?
