### ISSUE TITLE
FeatureRequest: IgnoreQueryFilters

### ISSUE THREAD

**Issue by rezathecoder** [ardalis/Specification#159]
Hi
If we have global filters applied in ef core configuration there should be a way to ignore them in some specifications.

**Comment by fiseni** [comment]
We've been trying hard not to make the package too EF centric. But, we've added `AsNoTracking`, `AsNoTrackingWithIdentityResolutionEvaluator`, `AsSplitQueryEvaluator`. So, I assume we can add this one too, it's useful one.

**Comment by ardalis** [comment]
Agreed. As much as possible it's nice to put them in the EF-specific packages, but I know that's not always possible, either.

**Comment by MiHum** [comment]
I implemented this by myself. I derive from Specification<T> and use an evaluator. The new specificaton class is a base class from that I can derive my business specifications. It was very easy for me.

But I was suprised that the SpecificationEvaluator has no ctor to add my new evaluator to the default ones. So I had to copy the whole list from the default ctor. I think no one would loose the default evaluators.

**Comment by fiseni** [comment]
Note to implement `IgnoreQueryFilters` in the next release.

Regarding your question, the `SpecificationEvaluator` has 2 constructors, parameterless one and the one accepting a list of evaluators. There is no ctor that accepts a single evaluator (to be appended to the default ones), and that's done intentionally. The order of evaluation might be important, and we simply wouldn't know where to place your evaluator (it would be a guessing game). So, yeah you have to pass the whole list 😄 Just copy-paste stuff from the default evaluator and add yours.

```c#
public SpecificationEvaluator()
{
	this.evaluators.AddRange(new IEvaluator[]
	{
		WhereEvaluator.Instance,
		SearchEvaluator.Instance,
		IncludeEvaluator.Instance,
		OrderEvaluator.Instance,
		PaginationEvaluator.Instance,
		AsNoTrackingEvaluator.Instance,
#if NETSTANDARD2_1
		AsSplitQueryEvaluator.Instance,
		AsNoTrackingWithIdentityResolutionEvaluator.Instance
#endif
	});
}
public SpecificationEvaluator(IEnumerable<IEvaluator> evaluators)
{
	this.evaluators.AddRange(evaluators);
}
```
