### ISSUE TITLE
Execute 1000 limit for Any

### ISSUE THREAD

**Issue by ShadyNagy** [ardalis/Specification#160]
@ardalis  & @fiseni
When use Any for more than 1000 record DB give an error executed 1000 limit.
and sure that code will not work as the where will overwrite the other where so, in the end, where will have only the last one.
it will be a good idea to add OrWhere function or inside the package, if there is Any then we will split it into many where?
or there is already a workaround?

```csharp
var cnt = 0;
while(count > 0)
{
  // To take only 999 every time
  var items = CreateItems(allItems, filter, cnt++ * 999, 999);
  count = items.Count;
  if (count > 0)
  {
    Query.Where(f => items.Any(p => p == f.Id.Trim()));
  }
}
```

**Comment by ardalis** [comment]
Can you show an example demonstrating the problem? If we're talking about `.Any()` isn't it just returning a boolean value and that should be pretty easy to do?

**Comment by ShadyNagy** [comment]
@ardalis 
```csharp
public class SomethingFilterByItemsSpecification : Specification<Something>
{
        public SomethingFilterByItemsSpecification(List<string> items)
        {
            Query.Where(f => items.Any(p => p == f.Id));
         }
}
```
when items execute 1000 will give an error when trying to do List `this error from DB ORA-01795: maximum number of expressions in a list is 1000 error`.
```csharp
var spec = new SomethingFilterByItemsSpecification(items);
var somethings = await _repository.ListAsync<Something, string>(spec);
```
it will be a good idea to add AndWhere function or inside the package, if there is Any then we will split it into many where?
or there is already a workaround?

**Comment by fiseni** [comment]
This is not related to the `Specification` package in any way. We're not touching the expressions in any form. You'll be getting the same error in any approach (EF, SQL, etc). Try `Contains` LINQ method. That may be translated differently by EF and generate a different SQL query.

Splitting it, won't help either. You have to split actual SQL queries. It's an error given from the DB side.

**Comment by ShadyNagy** [comment]
@fiseni 
Contains did not help
We can split actual SQL queries by making OrWhere function or if there is any inside the expression the package will split it into many expressions every one is 999 items.
If you are interested I can make PR and let's see how it will be.

**Comment by fiseni** [comment]
Shady, no matter how much you split it when the EF will try to evaluate it, all parameters will be sent anyway. It's not about the `Where` but the produced SQL. The error is from the DB side.

Try this. Write the query directly using the dbContext and see how it goes. Once you're done with that and everything works, then we can think about how we can utilize it through specification. But, as I said, we're not touching expressions, so if you find a way that would work with specs anyhow.

Sounds good?

**Comment by ShadyNagy** [comment]
@fiseni 
it is working if I make this like this
```csharp
Query.Where(f => itemsId1st999.Any(p => p == f.Id) || itemsId2nd999.Any(p => p == f.Id));
```
so I can make it also by expressions.

**Comment by fiseni** [comment]
But this is a way too specific case to be included in the package, don't you agree?
I mean we can find tons of such specific usages. You can try to create extensions, we'll document it, and whoever needs it can use it.

Also, manipulating expressions can get nasty quite fast :) Give it a try and see how it goes.

**Comment by ShadyNagy** [comment]
yes, Oracle.EntityFrameworkCore 5.21.1

> 
> 
> @ShadyNagy That just doesn't make sense. It should work with EF Core.
> 
> But it has nothing to do with this library. Maybe ask your question in EF Core.
> 
> https://github.com/dotnet/efcore/
> 
> Are you using the `Oracle.EntityFrameworkCore` package?

**Comment by ardalis** [comment]
Closing as this isn't a Specification issue at this point.
