### ISSUE TITLE
Support more complex entity selectors

### ISSUE THREAD

**Issue by julian-altech** [ardalis/Specification#164]
I am using a specification that essentially needs to do this:

```csharp
public class Spec : Specification<Entity, string>
{
    public Spec()
    {
        Query.Select(e => e.Foo.PropA)
            .Concat(Query.SelectMany(e => e.Bar.Prop.Select(p => p.Baz)))
    }
}
```

Which doesn't work because there's no concat option, I've currently worked around it by doing the following:

```csharp
public interface ISpecificationTransform<T, TResult> : ISpecification<T, TResult>
{
    IQueryable<TResult> Transform(IQueryable<T> query);
}
public abstract class SpecificationTransform<T, TResult> : Specification<T, TResult>, ISpecificationTransform<T, TResult>
{
    public abstract IQueryable<TResult> Transform(IQueryable<T> query);
}

public class Spec : SpecificationTransform<Entity, string>
{
    public override IQueryable<string> Transform(IQueryable<Entity> query)
    {
        query.Select(e => e.Foo.PropA)
            .Concat(query.SelectMany(e => e.Bar.Prop.Select(p => p.Baz)))
    }
}
```

And then I simply overrode `ApplySpecification<TResult>` in `RepositoryBase<T>` and all works well. 

I would propose having a way to do this within the framework itself, perhaps having it so that the `ISpecificationBuilder<T, TResult>` returns an `IQuery<T>` so that the specification can do some more advanced processing if needed.

**Comment by fiseni** [comment]
Hi,

This is a very old issue. We kept it open just in case we find a way how to implement this properly. But, honestly, I don't see a clear plan here. These are very specific use cases that you're better off working directly with your ORM and utilizing its full features.

In the future, if we do some major refactoring and change the basics of the library then we might re-consider it.
