### ISSUE TITLE
[Question] Adding ListWithCountAsync to IAsyncRepository

### ISSUE THREAD

**Issue by davidhenley** [ardalis/Specification#166]
I am not very good with Generics and was wondering what I'm doing wrong:

I created these 2 methods in my repository to automatically add the headers with count. 

One for a `ISpecification<T>`, one for `ISpecification<T, TResult>`

```csharp
public async Task<IEnumerable<T>> ListWithCountAsync<TSpec>(TSpec specification) where TSpec : ISpecification<T>
    {
        var count = await CountAsync(specification);
        var entity = await ListAsync(specification);
        _contextAccessor.HttpContext?.Response.Headers.Add("X-Paging-Total", count.ToString());
        return entity;
    }

    public async Task<IEnumerable<TResult>> ListWithCountAsync<TSpec, TResult>(TSpec specification)
        where TSpec : ISpecification<T, TResult>
    {
        var count = await CountAsync(specification);
        var entity = await ListAsync(specification);
        _contextAccessor.HttpContext?.Response.Headers.Add("X-Paging-Total", count.ToString());
        return entity;
    }
```

I want to be able to call them both with the same method:

```csharp
    var specification = new GetCustomersSpecification(query); // ISpecification<T>
    var customers = await _repository.ListWithCountAsync(specification);

    var specification = new GetCustomerDtoSpecification(query); // ISpecification<T,TResult>
    var dto = await _repository.ListWithCountAsync(specification);
```

But right now I have to call this to get the second one to work:

```csharp
    var specification = new GetCustomersSpecification(query);
    var customers = await _repository.ListWithCountAsync<GetCustomersSpecification, CustomerListDto>(specification);
```

Any ideas?

**Comment by ardalis** [comment]
If you do projection (`.Select()`) then you need to specify the projected type in the generic method so that the return type is known. If you don't do a projection, then the entity type is used for the return type, and that is known from the `Specification<TEntity>`. Does that help?

**Comment by davidhenley** [comment]
Hey Steve, thanks for the reply. It's hard to convey this. I'm just confused on why my 2nd ListWithCountAsync doesn't automatically see that the specification it's being passed is an ISpecification<T, TResult>

I just think I have my generics wrong or something.

**Comment by ardalis** [comment]
> Is it because it's calling the first one since ISpecification<T, TResult> extends ISpecification<T>?

That's my first thought. Debug it or otherwise determine what is called if you don't specify the `TResult` in your call to `ListWithCountAsync`. I'm not sure that's it but it's worth ruling out.
