### ISSUE TITLE
.NET Core 3.1 ambiguous call when extending IReadRepositoryBase<T> interface

### ISSUE THREAD

**Issue by gabrielheming** [ardalis/Specification#175]
I am using this library on a project that implements clean architecture. Currently, we are using the .NET Core 3.1 as it is still supported.

I found an issue while trying to extend the `IReadRepositoryBase<T>` to add specific read methods.

`IAsyncReadRepository<T>` that extends `IReadRepositoryBase<T>`:

```
public interface IAsyncReadRepository<T> : IReadRepositoryBase<T> where T : class
{
    Task<bool> AnyAsync(ISpecification<T> specification, CancellationToken cancellationToken = default);
    Task<bool> AnyAsync(CancellationToken cancellationToken = default);
}
```

And then, my `IAsyncRepository<T>` that extends `IAsyncReadRepository<T>` and `IRepositoryBase<T>`:

```
public interface IAsyncRepository<T> : IAsyncReadRepository<T>, IRepositoryBase<T> where T : class
{
}
```

After implementing a concrete class that relies only on interfaces:

```
public class AmbigousCall
{
    private readonly IAsyncRepository<MyEntity> myEntityRepository;

    public AmbigousCall(IAsyncRepository<MyEntity> myEntityRepository)
    {
        this.myEntityRepository = myEntityRepository;
    }

    public async Task Handle(CancellationToken cancellationToken = default)
    {
        await myEntityRepository.ListAsync(cancellationToken);
    }
}
```

I got the following error when building the application:

> AmbigousCall.cs(18,38): e Error CS0121: The call is ambiguous between the following methods or properties: "IReadRepositoryBase<T>.ListAsync(CancellationToken)" and "IReadRepositoryBase<T>.ListAsync(CancellationToken)" [D:\Projetos\repos\Study\ambiguous-call\Application\Application.csproj]

I was able to "fix" the issue with 2 workarounds.

**First**

Updating the global.json file from 3.1.415 to 5.0.403

global.json
```
{
    "sdk": {
        "version": "5.0.403"
    }
}
```

Following are my current installed sdks

> 3.1.404 [C:\Program Files\dotnet\sdk]
> 3.1.415 [C:\Program Files\dotnet\sdk]
> 5.0.403 [C:\Program Files\dotnet\sdk]

**Second**

Removing the "cross extending interface" (I coined this term at this moment) removing the `IReadRepositoryBase<T>` from `IAsyncReadRepository<T>` because `IAsyncRepository<T>` also extends from `IReadRepositoryBase<T>` through `IRepositoryBase<T>`

IAsyncReadRepository.cs:
```
public interface IAsyncReadRepository<T> where T : class
{
    Task<bool> AnyAsync(ISpecification<T> specification, CancellationToken cancellationToken = default);
    Task<bool> AnyAsync(CancellationToken cancellationToken = default);
}
```

I have created this following repository to allow you on reproducing the same situation: https://github.com/gabrielheming/AmbiguousCall

I am not sure whether this is a problem with the library or specific with .NET 3.1. Also, I make sure on setting the framework as `netstandard2.0` to use EntityFrameworkCore 3.1.18 from the package `Ardalis.Specification.EntityFrameworkCore`

**Comment by MisinformedDNA** [comment]
I can repro it, but I don't see anything strange with your projects or the library. It builds fine in VS, but fails in the CLI. Considering it works with .NET 5 SDK, I'd have to guess that it's a problem within the SDK.

**Comment by gabrielheming** [comment]
That is what I thought. I came here first to narrow the "variables" that might be the cause. I think I will open an issue on dotnet/core project. As .NET 3.1 is still in maintenance, it will be good for fixing issues like that.

**Comment by fiseni** [comment]
We had similar issues. Refer to this #113.
Once we updated the SDK from 5.0.100 to 5.0.201, it worked out. Might have been a subtle bug in the SDK, but not quite sure. I know I've been facing this in the past quite often.
