### ISSUE TITLE
Repository is trying to insert related object

### ISSUE THREAD

**Issue by ngruson** [ardalis/Specification#176]
I'm working on a .NET 5 application using Ardalis.Specification.EntityFrameworkCore 5.1.0.
In a MediatR command handler, I'm adding new Address objects to the database.
There are multiple entity repositories, one for the Country entity and one for the Address entity.
First, I lookup a country from the db using the Country repository. When that's successful, I'm assigning the country to a new Address object. 
The problem I have, is that the Address repository is trying to insert the country to the db (which already exists).
The AddAsync method is throwing this SqlException: 
`Cannot insert explicit value for identity column in table 'Country' when IDENTITY_INSERT is set to OFF`.

In SQL Profiler, I see an insert statement for the Country record.
Probably the DbContext of the Address repository is unaware that the country already exists in the db. 
The MediatR command handler is working with IRepository interface variables to access the repositories.
I don't want to expose the DbContext to the command handler to untrack the country object.
The command handler shouldn't have a direct dependency to EF Core.

How should I solve this?

**Comment by ardalis** [comment]
Sounds like you do t have your dB context set up as a scoped lifetime. Can you confirm and show your service registration code for EF and the repositories and MediatR handlers/stuff?

All should be scoped. No singletons. No transient dBcontext.

**Comment by ngruson** [comment]
Thanks Steve,

That was indeed the solution.
I changed my DI registrations to be scoped.
