### ISSUE TITLE
Composite Keys

### ISSUE THREAD

**Issue by Jacob-Roberts** [ardalis/Specification#177]
Is there a way to use this library with composite keys?
We have a table that has two keys, one an int, and one a dateTime (varchar in MySQL).
Can I use the GetByID method like this somehow?

var entity = await _repository.GetByIDAsync<tuple>(int, dateTime);

**Comment by fiseni** [comment]
This is related to the repository capabilities. We're providing a built-in repository, which includes the bare minimum. You can extend it with your additional methods.

Probably you'll need an overload similar to this
```
public async Task<T?> GetByIdAsync<TId>(params object[] keyValues)
{
	return await dbContext.Set<T>().FindAsync(keyValues);
}
```

**Comment by ardalis** [comment]
Also something to add to docs.

**Comment by Jacob-Roberts** [comment]
ok thank you!
