### ISSUE TITLE
Throwing custom domain exceptions instead of build ones

### ISSUE THREAD

**Issue by XardasLord** [ardalis/Specification#179]
Is it possible in the actual implementation to throw a custom exception instead of a build ones?

So in example when calling this:

```Guard.Against.NullOrWhiteSpace(text, nameof(text));```

I would like to throw my domain custom exception like `CreationalException` instead of `ArgumentNullException`.

**Comment by fiseni** [comment]
Hey @XardasLord,

I assume you wanted to post this issue in [GuardClauses](https://github.com/ardalis/GuardClauses) repository.
You can create your own extensions and use them in your application. It would be something like
```c#
public static class MyExtensions
{
	public static string NullOrWhiteSpace(this IGuardClause guardClause, string? input, string parameterName, string? message = null)
	{
		Guard.Against.NullOrEmpty(input, parameterName);
		if (String.IsNullOrWhiteSpace(input))
		{
			throw new CreationalException(message ?? $"Required input {parameterName} was empty.", parameterName);
		}

		return input;
	}
}
```

**Comment by XardasLord** [comment]
Hey @fiseni,

That's right, I put it in a wrong repository... Thanks for that! 
And thanks for your solution as well! :)
