### ISSUE TITLE
Implementing AnyAsync

### ISSUE THREAD

**Issue by gabrielheming** [ardalis/Specification#181]
Following a bit the issue #175. Can the method `Task<bool> AnyAsync` be implemented?

```
public interface IReadRepositoryBase<T> where T : class
{
    Task<bool> AnyAsync(ISpecification<T> specification, CancellationToken cancellationToken = default);
    Task<bool> AnyAsync(CancellationToken cancellationToken = default);
}
```

I think it is a "non-harmful" implementation and it does not seem to break any previous implementation.

**Comment by fiseni** [comment]
Yes, we'll implement this. Check issue #180 too.

**Comment by gabrielheming** [comment]
I think I let open the issues page yesterday and I haven't seen that.
BTW, I will make the PR to it if the @devbased doesn't want to.

**Comment by fiseni** [comment]
Yeah, please go ahead. Ensure that you're adding the implementation for all plugin packages (EFCore and EF6).
I can't remember well, but I think EF6 had issues with AnyAsync (the way it is translated). Please let's ensure it works everywhere.

**Comment by devbased** [comment]
@gabrielheming you're welcome and thanks for contribution

**Comment by andrewwilkin** [comment]
Any chance the NuGet Package could be updated please :)

**Comment by ardalis** [comment]
v6 will ship this month (hopefully earlier rather than later). Still catching up since the holidays.
