### ISSUE TITLE
Error calling the specification

### ISSUE THREAD

**Issue by DiogoAFD** [ardalis/Specification#194]
Hello,

I'm getting this error:
![image](https://user-images.githubusercontent.com/15615965/147230459-be0722bb-69d5-41cf-b07c-e30b8e223bc1.png)
When I call this method: 
![image](https://user-images.githubusercontent.com/15615965/147230116-b3bc50a6-17f2-4af7-bf97-7b2cf88a55c9.png)
My Specification:
![image](https://user-images.githubusercontent.com/15615965/147230534-cf755e74-efe9-41cd-937d-2e9740cfb0fa.png)

Anyone knows what I'm doing wrong ? I've used this Ardalis Nugget before in another project, with no problems.
Framework: .NET Framework 4.7.2

Thanks.

**Comment by fiseni** [comment]
It seems there is an issue with ValueTupples in `.NET Framework`. Some of the properties in the specification are Tupples, such as 
`public IEnumerable<(Expression<Func<T, string>> Selector, string SearchTerm, int SearchGroup)> SearchCriterias { get; }`.
I can't remember in which version they are supported. 

But, nobody complained until now 🤔 Can you try with `.NET Framework 4.8` please, and see if it works?

Btw, for the next release, we removed all Tupples and replaced them with explicit types.

**Comment by DiogoAFD** [comment]
> It seems there is an issue with ValueTupples in `.NET Framework`. Some of the properties in the specification are Tupples, such as `public IEnumerable<(Expression<Func<T, string>> Selector, string SearchTerm, int SearchGroup)> SearchCriterias { get; }`. I can't remember in which version they are supported.
> 
> But, nobody complained until now 🤔 Can you try with `.NET Framework 4.8` please, and see if it works?
> 
> Btw, for the next release, we removed all Tupples and replaced them with explicit types.

I don't know if the problem was specifically with ValueTupples, but I re-installed my packages, deleted bin/obj and packages folder, and Clean - Rebuild.
All this made the magic and now it works 😃

**Comment by fiseni** [comment]
Oh ok, then it had nothing to do with it 😄 
Glad that you fixed it.
