### ISSUE TITLE
Nested value objects not updating

### ISSUE THREAD

**Issue by jgondev** [ardalis/Specification#197]
I'm having the issue described here:
https://stackoverflow.com/questions/50486669/entity-framework-core-fail-to-update-entity-with-nested-value-objects

What would be the way to do it with the current implementation of the RepositoryBaseOfT?

(I've tried to find an answer in the Update endpoint of Patient in the DDD fundamentals repo but updating AnimalType is not implemented there)

**Comment by devbased** [comment]
You can override UpdateAsync and use `DbContext.Model` to perform generic update based on some criterias. For example, you can scan navigations and mark them as Modified if they're structs.

**Comment by fiseni** [comment]
The Update method implementation in our base repository is not very nice. Refer to this issue where I raised my concerns #118 .
I think utilizing the EF's `Update` method would fix the issue in your case. So, you can override it as following

```c#
public override async Task UpdateAsync(T entity, CancellationToken cancellationToken = default)
{
    dbContext.Set<T>().Update(entity);

    await SaveChangesAsync(cancellationToken);
}
```
Not sure, but having only the `SaveChangesAsync` statement might be enough too. In EF Core 5, the change tracker might recognize these changes.

**Comment by jgondev** [comment]
Thank you both, it worked with the code @fiseni just shared. Much appreciated.
