### ISSUE TITLE
Enable C# Nullable Reference Types

### ISSUE THREAD

**Issue by ardalis** [ardalis/Specification#20]
Should just need to add this to projects and fix all warnings:
```xml
<Nullable>enable</Nullable>
```

**Comment by deepumi** [comment]
@ardalis I have enabled Nullable Reference Types for the projects and trying to push. However I ran into Permission issue. 

my github account is - @deepumi. 

Would you please allow access to create a PR.

![image](https://user-images.githubusercontent.com/554039/84121174-6a8fb880-aa54-11ea-8592-837628e14f17.png)

**Comment by ardalis** [comment]
Done

**Comment by deepumi** [comment]
> Done

Thank you! 

There is another warning VS shows up for <PackageIconUrl> which is changed to now <PackageIcon> from nuget. Do you want to take care this?
