### ISSUE TITLE
Docs: Using the built-in Abstract Repository

### ISSUE THREAD

**Issue by ardalis** [ardalis/Specification#206]
This document: https://ardalis.github.io/Specification/usage/use-built-in-abstract-repository.html

This doc should build on the [quick start](https://ardalis.github.io/Specification/getting-started/quick-start-guide.html), which already demonstrates the very basics.

In addition to showing (or linking to) the quick start setup steps, this doc should include coverage (briefly) of all of the built-in repository's methods, showing how each one would be used in simple code snippets with comments.

**Comment by KyleMcMaster** [comment]
Happy to jump into this issue next, I think it builds on some of the other docs I've contributed so it's a logical next step if you want to assign me.
