### ISSUE TITLE
The 'PackageIconUrl'/'iconUrl' element is deprecated

### ISSUE THREAD

**Issue by deepumi** [ardalis/Specification#22]
The issue is about a deprecated tag which is 'PackageIconUrl' tag in the Specification.csproj file. 

```xml
<PackageIconUrl>https://user-images.githubusercontent.com/782127/33497760-facf6550-d69c-11e7-94e4-b3856da259a9.png</PackageIconUrl>
```
The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl	Ardalis.Specification

![image](https://user-images.githubusercontent.com/554039/84284755-3c949c00-ab5a-11ea-856d-2c4c485951e3.png)

**Comment by fiseni** [comment]
This change is already merged, and I'm closing this issue.
