### ISSUE TITLE
XML comments are not displayed.

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#227]
The XML comments are not displayed, even though the XML file exists in the NuGet package file. Can anyone else confirm this behavior?
We have added the following line in our csproj file
```
<DocumentationFile>bin\$(Configuration)\Ardalis.Specification.EntityFrameworkCore.xml</DocumentationFile>
```

I have other Nuget packages where this configuration works and comments are displayed correctly. Are we missing something here?

**Comment by devbased** [comment]
Why not just use?
```
<GenerateDocumentationFile>true</GenerateDocumentationFile>
```

**Comment by fiseni** [comment]
Hm, I don't know. I've been doing it that way for ages and it worked, so I guess "inertia" 😄 
The `GenerateDocumentationFile` property looks simpler. Does that work for sure? Do we need to add anything else?

**Comment by devbased** [comment]
I can't confirm that this will resolve the issue 😞 
Usually GenerateDocumentationFile is added to Directory.Build.props and explicitly set to false if not needed.

**Comment by fiseni** [comment]
Ok, I'm testing it locally and found the issue.
@ardalis the typo we had with the filename, that's what is causing it (I guess it expects to be the same as the project name). Once I created a new package locally with the correct filename, now it works correctly. Once we publish v6.0.1 the comments will appear.

Closing the issue.

**Comment by fiseni** [comment]
Actually, it turned out to be my Nuget cache. Ignore all this thread. Sorry 😄

**Comment by devbased** [comment]
Just a note related to comments.
In following case `inheritdoc` inherits comment from `System.Object`. Interfaces have to be specified via `cref`
```csharp
 /// <inheritdoc/>
public abstract class RepositoryBase<T> : IRepositoryBase<T> where T : class
```
should be
```csharp
/// <inheritdoc cref="IRepositoryBase{T}" />
public abstract class RepositoryBase<T> : IRepositoryBase<T> where T : class
```

**Comment by fiseni** [comment]
Thanks! I'm getting the comments for the repo methods too 🤔 
Anyhow, we still don't have full coverage with XML comments. Once we enabled them we have a lot of warnings now. At least it's easier to spot where we're missing comments.

**Comment by devbased** [comment]
Is it really a nuget cache issue? I've deleted all nuget packages locally and downloaded them again.
Ardalis.Specification/6.0.0/lib/netstandard2.0 content:
- Ardalis.Specification.dll
- Ardalis.Specification.EntityFrameworkCore.xml
- Ardalis.Specification.pdb

**Comment by fiseni** [comment]
The filename is wrong (that will be fixed in the next release), but you should have comments. Don't you.

**Comment by devbased** [comment]
They're not showing up in intellisense...

**Comment by fiseni** [comment]
Hm, perhapa my intellisense cached them once I loaded the updated local package, then displayed them even for the current version?

Anyhow, once we release v6.0.1, they will appear.

**Comment by fiseni** [comment]
@devbased version 6.0.1 is published. The comments seem fine here. Can you confirm that IntelliSense displays the comments?
