### ISSUE TITLE
Support to IAsyncEnumerable<T> which can be enumerated asynchronously

### ISSUE THREAD

**Issue by nelsonprsousa** [ardalis/Specification#229]
Already discussed here: https://github.com/ardalis/CleanArchitecture/pull/161

Usage example:

```csharp
[HttpGet]
public async IAsyncEnumerable<ToDoItem> GetAsyncEnumerable()
{
	await foreach(var todoItem in _repository.GetAsyncEnumerable<ToDoItem>())
	{
		yield return todoItem;
	}
}
```

I'll open and submit a PR for us to discuss this approach.

**Comment by nelsonprsousa** [comment]
@ardalis I was trying to figure out where I should add the `IAsyncEnumerable<T> GetAsyncEnumerable<T>()` and I believe I should add it to `IReadRepositoryBase`, however it is using netstandard2.0, that doesn't expose `IAsyncEnumerable<T>`.

How do you see this class libraries evolving?

**Comment by ardalis** [comment]
Agreed `IReadRepositoryBase` would be best place to try it out.

**Comment by nelsonprsousa** [comment]
Only possible if we upgrade to .NET Standard 2.1, however we will lose support to .NET Framework.

Not sure if you are up for that breaking change?

**Comment by ardalis** [comment]
Eventually, yes. Ideally, I'd like to keep two things true:

- This package utilizes semver, and breaking changes result in a new major version number
- This package's major version number updates in step with .NET; .NET 7 will be released in Nov 2022

However, I can be convinced to sacrifice the 2nd priority if the feature in question is in high demand and not easily worked around by client code. @fiseni what do you think?

**Comment by nelsonprsousa** [comment]
Just an heads-up, targeting non LTS versions (like .NET5, .NET7, .NET9, ...) can be challenging for some customers, but I get the need and I also support it 😅

**Comment by fiseni** [comment]
I do strongly dislike the `.NET Standard` specification altogether, and I can't wait the day we no longer have to use it (nor support it). But, we still have a lot of .NET FX users, that's the reason we have EF6 package too.

The feature you're requesting is just a repository feature, and you can easily add that method to your inherited interface and repository. Our built-in repository exposes some basic behavior only, and I'm sure everyone is adding something additional to it. I do like `AsyncEnumerable`, but making such a breaking change and losing support for NET FX users, just to have it in the built-in repository? Is it worth it?

**Comment by nelsonprsousa** [comment]
It's been 3 years since the last .NET FX release, but maybe there's a lot of people using it. The problem is that you'll soon start losing access to nice and new improved APIs.

Feel free to close this issue 👍

**Comment by ardalis** [comment]
Maybe it can go in CA after all, then. Thanks.
