### ISSUE TITLE
Would it be possible to get synchronous methods on the repository methods?

### ISSUE THREAD

**Issue by chadboettcher** [ardalis/Specification#233]
Would it be possible to get synchronous versions of the various methods declared in `IReadRepositoryBase<T>` and `IRepositoryBase<T>`?  We have legacy projects that are not able to go to `async` yet but could take advantage of the library if they methods didn't require `async` calls.  We did pull down the code and added sync methods for each of them and it works, but as you can imagine, we're already out of date with this code and would much rather use this library directly and take advantage of bug fixes, etc.

Thanks,

Chad

**Comment by asinghca** [comment]
I actually needed to add custom methods on top of the built-in ones, so I created interfaces that extend the built-in ones and did the same for concrete repository classes. This way you don't have to stop depending on the nuget package and manage it yourself.
