### ISSUE TITLE
can't use `ISpecification<T, TOut>` and `ISingleResultSpecification` together

### ISSUE THREAD

**Issue by BenMakesGames** [ardalis/Specification#236]
if I declare a specification as follows:

```
public class CustomerByEmailAddress: Specification<Customer, CustomerDetailsDto>, ISingleResultSpecification
```

I'm unable to use it as follows:

```
var spec = new CustomerByEmailAddress(query.EmailAddress);
var customer = await CustomerRepository.GetBySpecAsync(spec, cancellationToken);
```

because the `GetBySpecAsync` method in the Ardalis.Specification library which gets called is the following:

```
Task<T?> GetBySpecAsync<Spec>(Spec specification, CancellationToken cancellationToken = default (CancellationToken)) where Spec : ISingleResultSpecification, ISpecification<T>;
```

which does not respect the `TOut` return type.

the code executes, but the wrong method is called; it seems my query's `.Select` statement is ignored/skipped, and I receive an object of type `Customer` instead of one of type `CustomerDetailsDto`.

I'm able to fix this by writing my own, intermediate repository interface as follows:

```
public interface IRepository<T> : IRepositoryBase<T> where T : class
{
    new Task<TOut?> GetBySpecAsync<TOut>(ISpecification<T, TOut> specification, CancellationToken cancellationToken = default);
}
```

no other code required, however it does feel a bit worrying to hide one of the library's built-in methods (and without specifying that `ISingleResultSpecification` be present); I feel like there may be _consequences_ for this decision, down the road.

I don't have a suggested solution; just bringing the issue up.

I'm also very open to the possibility that I'm just using the library wrong. I did skim through the documentation, but didn't see anything about this use case (combining `ISpecification<T, TOut>` and `ISingleResultSpecification`).

**Comment by BenMakesGames** [comment]
update: I have tried the following:

```
var customer = await CustomerRepository.GetBySpecAsync<CustomerDetailsDto>(spec, cancellationToken);
```

which is better, however when invoked this way, the IDE believes my subsequent null checks are unnecessary, as the Ardalis.Specification method being called here results `TOut`, and not `TOut?`.

**Comment by fiseni** [comment]
Hey @BenMakesGames,

Which version of the package you're using? Starting with v6, we have better support for nullability. We're returning `TResult?`.
```c#
    public virtual async Task<TResult?> GetBySpecAsync<TResult>(ISpecification<T, TResult> specification, CancellationToken cancellationToken = default)
    {
      return await ApplySpecification(specification).FirstOrDefaultAsync(cancellationToken);
    }
```
As for the original question, you can be explicit in the call and you won't have issues. I believe this will map to the correct method.
```c#
var customer = await CustomerRepository.GetBySpecAsync<CustomerDetailsDto>(spec, cancellationToken);
```

I have to admit, adding `ISingleResultSpecification` was quite an opinionated action. I regret we did that. Some folks use the same specification for single and multiple returns, with multiple constructors, and now that approach won't work. We'll revisit the repository implementation and try to fix these minor issues. For now, you can always mask the underlying method in the base repository, and implement it as you wish (that's what I'm doing personally since `ISingleResultSpecification` is of no use to me).

**Comment by fiseni** [comment]
One more clarification here. Since the `TResult` is a method generic parameter, you can't use `TResult?` prior to `.NET6` and C#10. So, if you're consuming project is `.NET5`, you're out of the luck there. The nullability won't be inferred correctly.

**Comment by BenMakesGames** [comment]
we were indeed on an older version of the Ardalis.Specification library! and updating has resolved the nullability issue! (I should have checked for upgrades first! sorry about that!) (and we are on .NET6 and C#10, so no issues, there!)

I did kind of wonder about the `ISingleResultSpecification` thing, but was willing to accept that as "just how this library likes to do it"; it doesn't seem totally outlandish to me :P

thanks for your help!
