### ISSUE TITLE
issues using a specification which returns Max (`Specification<T, TResult>`, where `TResult` = `int`)

### ISSUE THREAD

**Issue by BenMakesGames** [ardalis/Specification#237]
I'm attempting to find the maximum value from a relationship.

I have seen this thread: https://github.com/ardalis/Specification/issues/171 but was surprised by the answer, because I thought I had come up with something... but I'm here because it's not working, so maybe it just isn't going to.

this is what I've tried; to simplify the example, and because I'm not sure my boss would appreciate me sharing our actual code, I've renamed everything to be as if something from a game... which matches with my name, so I'm down with that :P (I'm pretty sure nothing has been lost in this translation; it really was just some name changes.)

```c#
public class PlayerHighestScoreSpecification: Specification<Player, int>, ISingleResultSpecification
{
    public PlayerHighestScoreSpecification(long playerId)
    {
        Query
            .Select(p=> p.Games!.Max(g => g.Score))
            //.Include(p=> p.Games) // didn't think I'd need this, but I tried; didn't make a difference
            .Where(p => p.Id == playerId)
        ;
    }
}
```

used as follows:

```c#
var spec = new PlayerHighestScoreSpecification(playerId);
var highestScore = await PlayerRepository.GetBySpecAsync<int>(spec, cancellationToken);
```

however, I get a mysterious exception from deep within EF when `GetBySpecAsync` is invoked:

```
InvalidOperationException: Nullable object must have a value.
System.Nullable<T>.get_Value()
lambda_method619(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+AsyncEnumerator.MoveNextAsync()
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)
Ardalis.Specification.EntityFrameworkCore.RepositoryBase<T>.GetBySpecAsync<TResult>(ISpecification<T, TResult> specification, CancellationToken cancellationToken)
```

(with a little more, but I'd have to start editing again :P)

googling for "Nullable object must have a value." in relation to EF, people suggest that the proper data isn't being queried. the webpage I'm working on provides an exception page for this, with a "Query" tab, which is empty :P so unless something's gone wrong with the exception page, I don't think it's a null due to failing to query for required data:

![image](https://user-images.githubusercontent.com/1587505/152553241-7049980b-fd65-4d94-b8e2-fed846b0371d.png)

it _feels_ like this specification should work as written. but if it isn't going to work, what are some DDD-friendly alternatives?

**Comment by BenMakesGames** [comment]
a co-worker recommended using `.OrderByDescending` to get the max value... which works great, and now I feel very foolish for not thinking of myself :P

I am a bit curious to know about this issue, in general, though; I can definitely foresee a future in which I'd like to `.Sum` up more values than I'd want to individually query for (as referenced in #171)

**Comment by fiseni** [comment]
Hey @BenMakesGames,

I have to say you got a bit of weird usage here, but nevertheless, it should work. I just tested it now. You have to crosscheck your entities, the relationships, whether the Games collection is initialized, and that sort of stuff.

Here are the entities and the specification
```c#
public class Blog
{
    public int Id { get; set; }

    public List<Post> Posts { get; } = new();
}

public class Post
{
    public int Id { get; set; }
    public int Score { get; set; }

    public Blog Blog { get; set; } = default!;
    public int BlogId { get; set; }
}

public class BlogSpec : Specification<Blog, int>, ISingleResultSpecification
{
    public BlogSpec(int blogId)
    {
        Query.Select(x => x.Posts.Max(p => p.Score))
            .Where(x => x.Id == blogId);
    }
}
```

And here are the usages with and without specifications

```c#
var maxEF = await _dbContext.Blogs
    .Where(x => x.Id == 1)
    .Select(x => x.Posts.Max(p=>p.Score))
    .FirstOrDefaultAsync();

var maxSpec = await _blogRepository.GetBySpecAsync<int>(new BlogSpec(1));
```

Produced query for `maxEF`
```SQL
SELECT TOP(1) (
  SELECT MAX([p].[Score])
  FROM [Post] AS [p]
  WHERE [b].[Id] = [p].[BlogId])
FROM [Blog] AS [b]
WHERE [b].[Id] = 1
```

Produced query for `maxSpec`
```SQL
SELECT TOP(1) (
  SELECT MAX([p].[Score])
  FROM [Post] AS [p]
  WHERE [b].[Id] = [p].[BlogId])
FROM [Blog] AS [b]
WHERE [b].[Id] = @__blogId_0
```

As we can see both approaches yield the same SQL statement. So it has to be something in your design or EF configurations.

**Comment by BenMakesGames** [comment]
hm! thanks; I'll double-check the entity config.

my understanding with DDD (thought it is new to me, so I'm happy to be corrected) is that the application is not aware that there's a database under the hood. direct access to a DbContext is not something I think our application (or DDD in general?) facilitates.

**Comment by fiseni** [comment]
I gave a sample with EF direct approach, just to compare the approaches. I just wanted to emphasize that the given specification, once evaluated, will produce the same EF query, therefore the SQL statement will be the same as well. In this case, you would get the same exception even if not using specifications.

As for your questions about DDD, well, that's not exactly true. You can work directly with EF and still do DDD. Fundamentally, DDD has to do with your approach to the problem. It's about solving and designing the business domain first. Identifying boundaries, and using ubiquitous language. It's not important what tools and mechanisms you use for that.

What you're referring to is "clean/onion/hexagonal" infrastructure. This design in some form builds on top of the premises of DDD, and takes it one step further. It forces you to separate your domain model and the core logic from any infrastructural or UI concerns.

**Comment by BenMakesGames** [comment]
thanks for all the info. it's another developer who's really been in charge of the architecture; good for me to be hearing this stuff multiple times, from different places :P

anyway; thanks again! :)
