### ISSUE TITLE
Does Include support filtering on Included Navigation Property Query.Include(t=>t.ListOfData.Where(d=>d.SomeProperty == "SomeValue"))?

### ISSUE THREAD

**Issue by mosessaur** [ardalis/Specification#240]

**Comment by fiseni** [comment]
If it works without specifications, then it will work with specs too. We're passing the same expressions.

You have an issue?

**Comment by mosessaur** [comment]
Yes Sorry for not being clear. I am writing my unit tests using Sqlite provider instead of inmomery. 
Noticed when I use Include(t=>t.NavProperty.Where(predicate))  in my specification. The where statement is ignored and all records are returned.

**Comment by fiseni** [comment]
How are you evaluating the specification? Are you using 'Evaluate' method? If that is the case, that's intended for in-memory evaluation (you pass in-memory collection). During this evaluation, all ORM features are excluded, so 'Include' statements are just ignored. Since you're working with in-memory collections, the Include doesn't make much sense, right? you got what you got.

If you wanna to fully test your specs, then you need integration tests there.

**Comment by mosessaur** [comment]
Here is my specification
```C#
public sealed class AccountSpec : Specification<Account>,
    ISingleResultSpecification
{
    public AccountSpec(Guid accountId)
    {
        var endDate = DateTime.UtcNow.Date;
        var startDate = endDate.AddDays(-7);
        Query.Where(a => a.Id == accountId)
            .Include(a => a.Records.Where(t => t.Date >= startDate && t.Date <= endDate));
    }
}
```

And I use GetBySpecAsync of my repostiry (which inherits from RepositoryBase<T>)
```C#
// dbContext created earlier..
// Database has data
var repo = new EfRepository<Account>(dbContext);
var spec = new AccountSpec("<GUID VALUE>");
var account = await repo.GetBySpecAsync(spec);
```
when evaluating account.Recrods. It contains all data.
`DbContext.Set<Account>().Include(a=a.Records.Where(predicate))` using the same condition above. It loaded only records matching the condition.

So I wanted to know if I could be someting wrong. Or Specification Include extension doesn't support having where for included navigation property

**Comment by fiseni** [comment]
Thank you, it's clear now. You're doing it correctly.

Yes, we have support for filtered includes (starting with v5). We got some [tests](https://github.com/ardalis/Specification/blob/5427bd4848d8117b80756cfccb8449495d0ea09e/Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/RepositoryOfT_ListAsync.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L61) on that, using SqlServer provider and works fine.

We also do not depend on any EF provider. We depend only on `Microsoft.EntityFrameworkCore` package, so the provider shouldn't make any difference. Btw, which version of the specification package are you using? In version 6 we improved the Include infrastructure a bit and now it depends only on "public" constructs of EF. Previously we have been utilizing some internals and perhaps that's what is causing issues with Sqlite? Frankly, these are just guesses. But, it's worth trying the newest version.

**Comment by mosessaur** [comment]
I am referencing v6.0.1. And using .net 6.
I will also try to change my integration to SqlServer and see what will happen.
Thanks a lot.

**Comment by fiseni** [comment]
One last thing. Make sure that the children are not already loaded in the context by some other means. Not saying that you have that, but it's a common mistake.

Refer to the warning sections in the EF docs https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include

>In case of tracking queries, results of Filtered Include may be unexpected due to [navigation fixup](https://docs.microsoft.com/en-us/ef/core/querying/tracking). All relevant entities that have been queried for previously and have been stored in the Change Tracker will be present in the results of Filtered Include query, even if they don't meet the requirements of the filter. Consider using NoTracking queries or re-create the DbContext when using Filtered Include in those situations.

**Comment by mosessaur** [comment]
Thanks will definitely check that first then. I am not sure yet but I won't roll that out. Thanks for the reminder🙏🏾

**Comment by mosessaur** [comment]
Thanks a lot @fiseni . Your last commit touched the heart of my issue.
Because I was using the same repo to 
1) Fetch Account by Id. Then added records
2) Update Account
3) Fetch account again using GetBySpecAsync 
All was using the same repo instance.
After using fresh repo instance the behaviour was as expected.
