### ISSUE TITLE
Querying multiple tables using joins for performance reasons.

### ISSUE THREAD

**Issue by asinghca** [ardalis/Specification#241]
Hi Steve S. 

I have seen probably all your plural sight courses, and the linked YouTube video on specs for querying data. Thanks for sharing your knowledge, it helped me understand SOLID/DDD. If you share content on other platforms, please let me know.

Now regarding my question for this GitHub repo. These specifications are great to reduce noisy/repetitive code for sure. I was wondering if it would be possible to query data from multiple entities?

Say I have Students (includes student date of birth, student name), Courses (includes course name), Registrations (includes student id and course id as FK along with the year of registration).

Say I want to query all the student registrations for 2022. This is easy with the specification<Registrations> with something like where(x => x.year == requestedYear)

But what if I wanted to query something like:
List student name,  course name
where student.age > 22  and registration.year > 2018

Specifically, I would like the resulting SQL to achieve this using a join that returns just the requested data.  Can we achieve this using specification?

**Comment by ardalis** [comment]
Specifications are meant to be part of your domain model and a way to do common queries that return domain entities. If you just need some kind of report for read in it purposes, repositories and specifications are usually not the right tool for the job. Create instead a custom query service that returns DTOs with exactly the data you want to display and leave your domain model and it's rules out of it, as much as you can.

Sometimes there are edge cases where you want to do ad communication querying but use logic in your model as part of your filter. You can try to bring that logic into your query service. It's really hard to do entirely custom queries through repositories.

**Comment by asinghca** [comment]
Thanks for your response. 
Just to clarify: "Specifications are meant to be part of your domain model and a way to do common queries that return domain entities."

This in practice would mean we can query against entities in a given bounded context using specifications and repository. This is possible because those entities would be present in the backing DB context for the repository?

However, when it comes to needing data from entities that are not part of a given bounded context, they should either have their own bounded context (along with backing db context) or could be moved up in the application layer (escaping core/domain layer)?

Another question related to db context/specs, there is a legacy system with just one database with probably ~50 tables. Looking at its .dbml designer is not pleasant. For the sake of db migrations management and to facilitate code migration to .Net/ASP.Net Core MVC from legacy .Net framework, would creating a complete EF core db context be the appropriate approach here, at least to start migrating to .net core? DDD can then be applied iteratively by encapsulating related entities/logic into their bounded contexts and for those, we can create dedicated db contexts?

I would appreciate your expertise. Thanks, Steve.

**Comment by asinghca** [comment]
Not ~50 but more like 100. Monolith and anemic, and lacks SOLID. Lots of work for sure
![image](https://user-images.githubusercontent.com/10579398/153926092-846bcc1f-b5f2-43a7-895c-34e3fc2c1ce9.png)

**Comment by ardalis** [comment]
yes, you could create a separate dbContext for the other database and write your queries against it in whatever way is convenient. Again you may not need to use specifications for this purpose - they're mainly beneficial for your domain model, not for ad hoc queries.

Also regarding this:

> Specifically, I would like the resulting SQL to achieve this using a join that returns just the requested data. Can we achieve this using specification?

This is when you would want to use the `.Select` statement and a `Specification<TEntity,TResult>`.
