### ISSUE TITLE
Using Table per Hierarchy with specification

### ISSUE THREAD

**Issue by BuddhaCodes** [ardalis/Specification#243]
I have two Classes called Product and Service that inherits from BaseProductService, TPH works fine but I dont know how to use it with specification and endpoints

**Comment by caztial** [comment]
What is the exact problem you are facing? I have tried TPC and it worked correctly. The issue I'm facing is OfType isn't supported yet for IQuerible in Specification

**Comment by BuddhaCodes** [comment]
Sorry I figure it out, by calling the IRepository on the child class, because I couldn't find a proper documentation I was thinking that the way I was handeling the problem at hand could be wrong and I walking on a maze searching for a OfType alternative. Thanks.

**Comment by caztial** [comment]
When [this](https://github.com/ardalis/Specification/pull/56) feature is available in the next release. you can add a PostProcessingAction to filter the OfType.

**Comment by BuddhaCodes** [comment]
That would be awesome
