### ISSUE TITLE
Feature: Add  OnBefore\OnAfter methods to RepositoryBase<T> 

### ISSUE THREAD

**Issue by vincenzomartusciello** [ardalis/Specification#244]
Hi, I'm in a particular situation, where for each writing method of the repository I need to do some pre and post operations.

For example, one of my actions is to take the events of the domain entity and pass them to the IEventStore.

For the moment I've created my own abstract class which encapsulates the one present in the library and add this behavior, like this.
```
....
  public override async Task<T> AddAsync(T entity, CancellationToken cancellationToken = default)
  {
        await this.OnBeforeCallAsync(cancellationToken);
        var result = await base.AddAsync(entity, cancellationToken);
        await this.OnAfterCallAsync(cancellationToken);
        return result;
  }
....
```
I wanted to know if it was useful\possible to add this functionality to the library.

Thanks

**Comment by caztial** [comment]
I think this has to do with the dbContext please refer [here](https://github.com/ardalis/pluralsight-ddd-fundamentals/blob/main/ClinicManagement/src/ClinicManagement.Infrastructure/Data/AppDbContext.cs)

**Comment by vincenzomartusciello** [comment]
Not if using more then one db context 
Differently from the example, in my case I don't have the possibility to dispatch the events in the db context.
Domain events are saved through the repository in an event store.
Then the actions are performed on the various contexts and finally a single saving is carried out.
The events, in case of saving carried out, are then published in different ways: forground, background or sent elsewhere
