### ISSUE TITLE
Feature improvements.

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#25]
Hi there,

The package offers great functionalities for now. I think we can do few improvements though. For the next major release we might think of the following subjects. If you think that any of this makes sense, then we can open separate issues and work on them.

- Naming convention
People are already quite familiar with LINQ. Why would we introduce new method names for them to remember? Instead of `AddCriteria`, let just be `Where`; instead of `AddInclude`, let be `Include`, etc. Other than that, usually it's not quite obvious what functionalities the base classes offer, and users constantly look it up to see what's available. Let simply define property which would encapsulate everything. Simply, it can be `this`. The statements look better and more familiar to the users. Might be as following

```
    public abstract class BaseSpecification<T> : ISpecification<T>
    {
        public BaseSpecification<T> Query { get; }

        protected BaseSpecification()
        {
            Query = this;
        }
    }

// Usage

    public class MySpec : BaseSpecification<MyEntity>
    {
        public MySpec() : base()
        {
            Query.Where(x => x.ID == 1);
            Query.Include(x => x.MyEntityCollection);
        }
    }
```

- Include functionalities
One of contributors did great job with "ThenInclude", but kinda I'm still not satisfied :). In the current implementation, ultimately everything is still converted to include strings. Let's keep the additional expressions and evaluate properly in the spec evaluators, utilize "ThenBy" of EF. The implementation would be a bit more complex, but it's possible.

- Specification Evaluator
Since this grew to be a separate construct, then let just do it properly. Lets make the methods non-static, and define an interface. If you decide to go with infrastructure as described in issue #10 and include the repository implementation in the package, then the interface would be injected in the constructor.
The included repository actually would be abstract, and the users will have to inherit it, so they can use their own DbContext. It might be something as below

```
    public abstract class Repository<T> : IRepository<T> where T : BaseEntity, IAggregateRoot
    {
        private readonly DbContext dbContext;
        private readonly ISpecificationEvaluator<T> specificationEvaluator;

        public RepositoryEF(DbContext dbContext)
        {
            this.dbContext = dbContext;
            this.specificationEvaluator = new SpecificationEvaluator<T>();
        }

        public RepositoryEF(DbContext dbContext, ISpecificationEvaluator<T> specificationEvaluator)
        {
            this.dbContext = dbContext;
            this.specificationEvaluator = specificationEvaluator;
        }

        // Interface implementation

    }

    public class MyRepository<T> where T : BaseEntity, IAggregateRoot
    {
        private readonly MyDbContext myDbContext;

        public RepositoryEF(MyDbContext myDbContext)
            : base(myDbContext)
        {
            this.myDbContext = myDbContext;
        }

        public RepositoryEF(MyDbContext myDbContext, ISpecificationEvaluator<T> specificationEvaluator)
            : base(myDbContext, specificationEvaluator)
        {
            this.myDbContext = myDbContext;
        }

        // Not required to implement anything. Override or add additional functionalities.
    }
```

If the user has not defined their own implementation for the SpecificationEvaluator, then the default one will be instantiated. And yet again, they can implement their own. This structure offers much more flexibility.

- Ordering
For now we can order by max two columns (two levels). We may keep list of expressions, so we don't have such limitation.

There are few other features that we might consider.. but we can elaborate them by time.

**Comment by ardalis** [comment]
Love it! Can you split this into separate issues and we can discuss them individually (as you suggested)? I can add a milestone to them to group them together for a planned release.

**Comment by fiseni** [comment]
I split it into separate issues. I was testing now different possibilities. I achieved the following.
I personally like this style. Let me know what u think.

    public class BlogWithPostsSpec : BaseSpecification<Blog>
    {
        public BlogWithPostsSpec(int id) : base()
        {
            // It would be possible to chain everything
            Query.Where(x => x.Id == id)
                    .Include(x => x.Posts)
                    .EnableCache(nameof(BlogWithPostsSpec), id)
                    .ApplyPaging(10, 20)
                    .OrderBy(x => x.Name)
                    .ThenByDescending(x => x.Url);

            // This also is possible, or combination of both
            Query.Where(x => x.Id == id);
            Query.Include(x => x.Posts);
            Query.EnableCache(nameof(BlogWithPostsSpec), id)
                    .ApplyPaging(10, 20)
                    .OrderBy(x => x.Name)
                    .ThenByDescending(x => x.Url);
        }
    }
```

**Comment by fiseni** [comment]
Hey @ardalis,
Had a chance to look on the issues? Next period I won't be very available. Let me know your thoughts, so I can fix today.

**Comment by ardalis** [comment]
Yes, these look great. I know you're pushing forward in your own repo but PRs are welcome on these.

**Comment by fiseni** [comment]
Yea sure. I've been waiting for you to create a branch, not to pollute the master.
I already finished it, need to just fix the azure pipeline, and I'll publish it. Take a look on the implementation. Whatever you like from there, I'll PR here!

**Comment by ardalis** [comment]
Ah, ok. I figured we would just PR to master until we were ready but a separate v4 branch makes sense. Here you go:
https://github.com/ardalis/Specification/tree/version4

**Comment by fiseni** [comment]
The features are implemented in version 4. I'm closing the issue. If anyone has additional comments or suggestions, please feel free to reply or re-open the issue.
