### ISSUE TITLE
Add support for updating specifications.

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#250]
In the current design, we have `virtual protected` signature for the specification builder (`Query`). Users, if necessary, can create their own base specification, override the builder, and so on (I doubt that anyone is overriding the builder). The intention with such a design was to keep the specifications immutable in some sense. Users write all their rules within the constructor. They should not further modify the specification once it is created, since that would leak custom querying logic throughout the code. And that's exactly what we're trying to prevent with this library.

But, that's just our opinion, and confining the users how they want to use the library is not a very open-minded approach :) We had a lot of requests to allow further modifications of the specs. I gave a thought to this, and instead of exposing the specification state for mutation, let's just expose the specification builder publicly. Thus, we'll still keep the state encapsulated in some form and we'll have the opportunity to validate the inputs if necessary. So, users would be able to do this:
```c#
var spec = new CustomerSpec();

// Add additional logic to existing spec
spec.Query.Where(x => x.Name == "Something");
```

A lot of folks have asked for composite specifications (that's the main reason for this proposal). Once we do this change, users will have the opportunity to write extensions and create their custom composition rules.

```c#
namespace Ardalis.Specification
{
  public static class MySpecExtensions
  {
    public static ISpecification<T> Combine<T>(this ISpecification<T> spec, ISpecification<T> otherSpec)
    {
      // Add Where expressions to the original spec
      foreach (var whereExpressionInfo in otherSpec.WhereExpressions)
      {
        spec.Query.Where(whereExpressionInfo.Filter);
      }

      // Similarly, add other expressions/states, whatever your rule is for combining.

      return spec;
    }
  }
}
```

The usage would be:

```c#
var spec1 = new CustomerSpec();
var spec2 = new CustomerSpec();

// The spec2 state is added to spec1
spec1.Combine(spec2);
```

**Comment by devbased** [comment]
@fiseni I've noticed that CacheKey cannot be copied from other spec (as well as IncludeExpressions)
```csharp
public MySpec(ISpecification<Orders> originalSpec)
{
    // TODO: not working
    // this.CacheEnabled = originalSpec.CacheEnabled;
    // this.CacheKey = originalSpecification.CacheKey;

    // no access to original specification name or arguments
    // this.Query.EnableCache(originalSpec.Name, originalSpec.Args);

    // foreach (var includeInfo in originalSpec.IncludeExpressions)
    // {
    //     // this.Query.Include(includeInfo.LambdaExpression) // not possible without reflection
    // }
    // fallback to internal List manipulation
    ((List<IncludeExpressionInfo>)this.IncludeExpressions).AddRange(originalSpec.IncludeExpressions);
}
```

**Comment by fiseni** [comment]
Hey @devbased 

Why would you need the arguments? Each of the specifications has already readily computed cache key. You just need to join them and you will get the unique key for the combined spec.
```c#
public static class MySpecExtensions
{
  public static ISpecification<T> Combine<T>(this ISpecification<T> spec, ISpecification<T> otherSpec) where T : class
  {
    spec.Query.EnableCache(spec.CacheKey, otherSpec.CacheKey);

    return spec;
  }
}
```

As for the `Include`, that's a special case. As you already know, there is no way of storing the generic parameters for the inner layers of the chain, other than keeping the state as `LambdaExpression`. So yea, it's an either reflection or manipulating the internal collection.

I've been wanting to refactor the specification for a long time, but it's a big breaking change and I've been hesitating. Now that the specification evolved and has a lot of states, we should introduce a separate `SpecificationContext` construct instead of keeping it in `Specification`. We may also introduce `Append` functionality for those collections, so you don't need casting (that's just a hack).
