### ISSUE TITLE
Translating specifications into SQL

### ISSUE THREAD

**Issue by lncendia** [ardalis/Specification#257]
In my project, I try not to violate srp and have allocated domain entities and storage-level entities. I am writing specifications for domain entities, but at the data access level it is necessary to translate them into SQL or a LINQ query in accordance with the data level entities. I have heard that the visitor pattern is suitable for this, is it possible to implement it with this library? If not, maybe there are some other solutions to the problem?

**Comment by ardalis** [comment]
I take it you're not using an ORM like EF Core to do this translation for you? You're basically going to need to implement the expression to SQL translation that EF Core is already performing.
