### ISSUE TITLE
 filter at level theninclude

### ISSUE THREAD

**Issue by luigi108** [ardalis/Specification#260]
hello, 

thank you for your contributions; i use ardalis specification in net core 6, I have 3 related classes, Module one to many with Claims and Claims many to one with RolClaims
my sql code :

`select modu.Id, modu.Name,claims.Id, claims.Name, claims.Description
from [Auth].[AuthModules] modu left join [Auth].[AuthClaims] claims on modu.Id = claims.AuthModuleId
left join Auth.AuthRolClaims rol on claims.Id = rol.AuthClaimId
where rol.AuthRolId = '58D43F30-7947-4319-ADE7-C44815ADF9FC'`

my code in Specification :
`public ClaimsByRolSpec(GetClaimByRolQuery filter)
    {
        Query.Include(x => x.AuthClaims).ThenInclude(r => r.AuthRolClaims);

        Query.Where(x => x.AuthClaims.)
    }
`
I do not get the AuthRolId field of the RolClaims entity to perform the filter, What am I doing wrong?, or what is missing in the code?; I appreciate all help provided.

thank you

**Comment by andrewtsybulia** [comment]
bump :)

**Comment by ardalis** [comment]
Whether you're using Specification or EF Core directly, the behavior should be the same. Are you able to make this work using just a dbContext? If not, I suggest asking on StackOverflow. Once you have it working with a DbContext query expression, it should be easy to turn that into a Specification.

**Comment by ardalis** [comment]
See: https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include

Reopen if this isn't working - should work using the syntax shown in the docs.
