### ISSUE TITLE
Docs: "SpecificationEvaluator" seems to be removed but is used in examples

### ISSUE THREAD

**Issue by AndreErb** [ardalis/Specification#261]
Hi there,

[How to use Specifications with the Repository Pattern](https://ardalis.github.io/Specification/usage/use-specification-repository-pattern.html#how-to-use-specifications-with-the-repository-pattern) shows the usage of the "SpecificationEvaluator", but the class seems to not exist, anymore.

Maybe the docs need an update?
Is there a replacement?

**Comment by ardalis** [comment]
The docs are using SpecificationEvaluator.Default, which is still supported today.

**Comment by AndreErb** [comment]
Sorry, but I don't think so.
It's been nearly a year since I reported this but I am quite sure, that VS couldn't find the class.
Also I had a quick look into https://github.com/ardalis/Specification/tree/main/Specification/src/Ardalis.Specification/Evaluators
and still couldn't find it.
Can you point out to the class or what do meany by "it's still supported today"?

**Comment by AndreErb** [comment]
Ok sorry. My bad.

Found it in https://github.com/ardalis/Specification/blob/main/Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Evaluators/SpecificationEvaluator.cs

Might be the reason, that I didn't have that package included.

**Comment by fiseni** [comment]
The evaluators are included in the "plugin" packages. You have to install either of these packages:
- `Ardalis.Specification.EntityFrameworkCore` - if you're using EF Core
- `Ardalis.Specification.EntityFramework6` - if you're using EF6

The base package `Ardalis.Specification` contains only in-memory evaluators.
