### ISSUE TITLE
Is there a way to add Query Tag to the specification?

### ISSUE THREAD

**Issue by AvtsVivek** [ardalis/Specification#263]
If we want to add a [Query Tag](https://docs.microsoft.com/en-us/ef/core/querying/tags)  how  can we do it?

**Comment by ardalis** [comment]
This is something we could possibly support at the baserepository level and allow some configuration to turn on or off for all queries that use specifications.

**Comment by fiseni** [comment]
This is a very niche feature and will increase the memory footprint of the specs. Do we still want this?

**Comment by fiseni** [comment]
The specs and the infrastructure is relatively extendable. We added a sample [here](https://github.com/ardalis/Specification/blob/main/sample/Ardalis.Sample.Domain/Specs/CustomerSpecExtensions.cs) of how to implement this feature by extending the specs. Let us know if this works for you.

I'm closing the issue. Feel free to re-open it if you have further remarks.
