### ISSUE TITLE
Looks like version 6.0.1 is not with same funcionalities (e.g: AddRangeAsync)

### ISSUE THREAD

**Issue by EliveltonRepolho** [ardalis/Specification#264]
Looking at [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb) which is using current latest version (6.0.1) looks like is missing `AddRangeAsync` method...
is this expected ?

**Comment by snax4a** [comment]
AddRangeAsync was added after 6.0.1 release so its not yet available in a nuget package as 6.0.2 was not released yet.
We have to wait for the next release

**Comment by ardalis** [comment]
We'll try to get another release out this week.

**Comment by EliveltonRepolho** [comment]
Closing since was released in https://github.com/ardalis/Specification/releases/tag/v6.1.0

Thank you !
