### ISSUE TITLE
[Question] Retrieve List From Specs

### ISSUE THREAD

**Issue by danijel88** [ardalis/Specification#265]
Dear,

I just want to understand how to use Specification in order to retrieve list from DB.
I had did create like this
```
public sealed class PreparationByModelSpec : Specification<Preparation>
{
    public PreparationByModelSpec(string model)
    {
        Query.Where(w => w.Model2Q == model);
    }
}
```
 But in my code when I use like:
`var preparations = await _preparationRepository.GetBySpecAsync(new PreparationByModelSpec("Model 1"));`
I'm getting an error, which says:

Error	CS0311	The type 'SecondQualityManagement.Specifications.PreparationByModelSpec' cannot be used as type parameter 'Spec' in the generic type or method 'IReadRepositoryBase<Preparation>.GetBySpecAsync<Spec>(Spec, CancellationToken)'. There is no implicit reference conversion from 'SecondQualityManagement.Specifications.PreparationByModelSpec' to 'Ardalis.Specification.ISingleResultSpecification'.

Why is asking me to add ISingleResultSpecification ?

Kind Regards,
Danijel

**Comment by Illusion4** [comment]
Make PreparationByModelSpec inherit to ISingleResultSpecification

**Comment by danijel88** [comment]
If I inherit ISingleResultSpecification I'm getting single result, but I need a list ,because in DB exist a list of records with specific criteria.

**Comment by danijel88** [comment]
I found await _preparationRepository.ListAsync(spec);
Regards,
