### ISSUE TITLE
Why add methods on RepositoryBaseOfT contain SaveChanges 

### ISSUE THREAD

**Issue by kfathy-ys** [ardalis/Specification#266]
Why the framwork don't give the free to developer to save chanes or not , may be i need to write multiple add then call save changed.

_repositroy.AddAsync(tenant1 ); 
_repositroy.AddAsync(tenant2);
_repositroy.SaveChanges();

I you remove SaveChanged method from Add method i can write the example without need to use even unit of work or begin transation

**Comment by ardalis** [comment]
The repository pattern is meant to make access to persistence resemble an in-memory collection with more advanced querying capabilities. When you add an item to a `List<T>` or other collection, you don't need to call `SaveChanges` or anything to commit the operation. So for this **sample** repository we don't, either. If you need UoW you can certainly create your own similar Repository or just wrap the operations in transactions and roll them back if needed.

**Comment by kfathy-ys** [comment]
Thank you @ardalis  for your replay 
So you see the the best practice that core layer don't feel that it work with store engine , so we must build our code as there is no transactions and find some way to make roll back after saving.
please told me  you opinion abou that.

**Comment by ardalis** [comment]
It's up to you how you want to design it. For most systems, especially web APIs that are only doing one operation at a time, typically, having each repo operation save as part of it works fine. For others, you'll want a separate unit of work and/or transaction pattern to wrap around several operations. There's an issue discussing exactly this here:

https://github.com/ardalis/CleanArchitecture/issues/327

Do what works for your needs.
