### ISSUE TITLE
The provider for the source 'IQueryable' doesn't implement 'IAsyncQueryProvider'

### ISSUE THREAD

**Issue by vinaykarora** [ardalis/Specification#270]
I'm getting following error "The provider for the source 'IQueryable' doesn't implement 'IAsyncQueryProvider" 

When I use :
`return await ApplySpecification(specification).FirstOrDefaultAsync(cancellationToken);`

The below code is working and getting the expected output 1
`return await CosmosLinqExtensions.CountAsync(ApplySpecification(specification), cancellationToken);`

```
private IQueryable<T> ApplySpecification(ISpecification<T> specification)
    {
        return specificationEvaluator.GetQuery(AsQueryable(), specification);
    }

private IQueryable<T> AsQueryable()
    {
        return _container.GetItemLinqQueryable<T>();
    }
```
Database: CosmosDB 
Azure.Cosmos SDK: 3.27.2.0
Ardalis.Specification 6.0.1.0

**Comment by pveliz** [comment]
public async Task<int> CountAsync()
        {
            QueryRequestOptions queryRequestOptions = new QueryRequestOptions();

            IOrderedQueryable<TEntity> linqQueryable = _database.Container
                .GetItemLinqQueryable<TEntity>(requestOptions: queryRequestOptions);

            int result = await linqQueryable.CountAsync();

            return result;
        }

**Comment by ardalis** [comment]
Is this still an issue? If so, feel free to reopen.
