### ISSUE TITLE
Adding AsTracking

### ISSUE THREAD

**Issue by DiniMad** [ardalis/Specification#277]
I am trying to set tracking behavior to "NoTracking" globally and override it for some instances.
So I tried using "UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)" in the OnConfiguring method of my DbContext
and override it for specifications like this "Query.AsNoTracking(false)" but it does not work.
I also tried to set it to true for all specifications and override it in another method without setting "UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)" in my DbContext but it didn't work either. (it seems that if AsNoTracking with the value true or without value at all gets called on the query it's sets no tracking to true but if it's gets called with the value false does not do anything)

**Comment by ardalis** [comment]
Is this still something you need? Reopen if someone wants this.

**Comment by codelovercc** [comment]
Up, related issue https://github.com/ardalis/Specification/issues/336
