### ISSUE TITLE
Pagination feature would be very acceptable

### ISSUE THREAD

**Issue by artkrv** [ardalis/Specification#278]
We have [ISingleResultSpecification.cs](https://github.com/ardalis/Specification/blob/main/Specification/src/Ardalis.Specification/ISingleResultSpecification.cs) and [ISpecification.cs](https://github.com/ardalis/Specification/blob/main/Specification/src/Ardalis.Specification/ISpecification.cs), so it would be nice to get something like `IPaginatedResulutSpecification `which will return some `IPaginatedCollection<TEntity> { Data: TEntity, Total: int }`

**Comment by ardalis** [comment]
We have support for implementing paging in the specification but not any particular way of representing a paged result. The means of doing that could vary widely between applications, so we don't want to force a particular implementation on users of this library. Thus, we leave that to you to build but we're happy to accept any samples of how you've done it in the docs / samples in this library to help others.
