### ISSUE TITLE
is it possible to extend the LINQ queries generated by Specifications?

### ISSUE THREAD

**Issue by BenMakesGames** [ardalis/Specification#285]
ex: if "AsNoTracking" did not exist in this library, how would I add it in my project?

I'd like to add caching to some queries, using this library: https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor

doing so requires adding a call to `.Cacheable()` to the LINQ query... but Specifications (appear) to hide LINQ from me.

I already use a custom specification class which extends Specification<T>, but what I _really_ need is to extend `Query` (the `ISpecificationBuilder`)... or that's my current thinking, anyway.

is there some way to do this, or otherwise accomplish the goal?

**Comment by jasonsummers** [comment]
Hi @BenMakesGames,
Issue #250 (fixed in version 6.1.0) exposes the ISpecificationBuilder via the Query property on all ISpecification derived classes.
Does that property give you what you need?

**Comment by BenMakesGames** [comment]
I don't believe so? but maybe I'm not understanding something.

I'm not sure how to use an `IQueryable` extension in a specification.

in my particular use case, EFCoreSecondLevelCacheInterceptor has added the following extension:

```
public static IQueryable<TType> Cacheable<TType>(
            this IQueryable<TType> query, CacheExpirationMode expirationMode, TimeSpan timeout)
```

**Comment by ardalis** [comment]
You can put this logic into your own custom Repository method:

```csharp
// in a method in your own inherited generic repository like ListCached()
var results = await dbContext.MySet
    .Where(x => x.IsWhatIWant)
    .Cacheable() // third-party IQueryable extension!
    .ToListAsync(ct);
```

It won't be a part of the Specification but you will still have access to it within your application.

**Comment by BenMakesGames** [comment]
thanks for the reply. we've since moved away from using this library, on our team, but who knows what the future holds!
