### ISSUE TITLE
Order functionality improvements.

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#29]
For now we can order by max two columns (two levels). We may keep list of expressions, so we don't have such limitation.
We would need initial expressions for `OrderBy` and `OrderByDescending`. These methods probably should return newly defined interface, and then we define extensions to the interface "ThenBy" and "ThenByDescending". These also would return the interface so we can cascade.
We just have to think of the efficiently way to store this information in the BaseSpec.

**Comment by fiseni** [comment]
This is addressed with PR #30. The usage will be as following, we can chain several levels.

```
    public class StoresByCompanyOrderedDescByNameThenByIdSpec : Specification<Store>
    {
        public StoresByCompanyOrderedDescByNameThenByIdSpec(int companyId)
        {
            Query.Where(x => x.CompanyId == companyId)
                 .OrderByDescending(x => x.Name)
                      .ThenBy(x => x.Id)
                      .ThenByDescending(x => x.Title)
        }
    }
```

<strong>Notice:</strong>
If we create several Order chains, they all will be saved in the internal state of the specification, but the evaluator will parse only the last chain. I don't know if it makes sense to create several chains! Anyhow based on the decision, would be easy to change the behaviour in `SpecificationEvaluator`, and parse all of them.

**Comment by fiseni** [comment]
If no one has comments here we can close the issue.
@ardalis are you OK with it, should we keep it this way? Only one Order chain will be evaluated.

**Comment by ardalis** [comment]
Let's close it. We should only allow one chain. Adding another should probably throw a helpful exception.

**Comment by fiseni** [comment]
Sure, we can throw an exception in the evaluator. But, are we sure we want to introduce termination behavior in this package?
We may just leave it with usage notice, or we may write analyzer to catch the ambiguous usages. Or, let's just evaluate all the chains and rely on the default behavior of the ORM (EF Core in this case).

Not sure what's the smartest thing to do.

**Comment by ardalis** [comment]
Let's if nothing else demonstrate the current behavior in some integration tests so that we can look at it and figure out from concrete code examples how we would expect it to behave. What I don't want is for someone to think they have configured it to work a certain way, but transparently we are ignoring a bunch of what they did and only taking the most recent chain. I'd rather the design that only one chain is supported be enforced than documented, since it's much more likely to be missed in docs (and the bug introduced might be a subtle one).

**Comment by fiseni** [comment]
Ok, let's do that way. If there is more than one chain, the evaluator will throw an exception. I'll make the changes the following days.
