### ISSUE TITLE
How to specify distinct in specification query?

### ISSUE THREAD

**Issue by nagtilaklaxman** [ardalis/Specification#296]

**Comment by fiseni** [comment]
Hi @nagtilaklaxman,

What is your use case? `Distinct` makes sense only in the projections when you're fetching a single column. You can possibly just add `DictinctList` repository method.

**Comment by ardalis** [comment]
Closed as inactive.

**Comment by mhd-ahmadi** [comment]
I have problem with this query I have multiple repeated data from query!

`public class DataSetGetByFilterProjectsResultSpec : Specification<DataSet, ProjectViewDto>
{
  public DataSetGetByFilterProjectsResultSpec(DataSetFilter filter)
  {
    Query
      .ApplyFiltering(filter);

    Query
      .Where(w => w.ProjectId.HasValue)
      .Include(c => c.Project)
      ;

    Query
      .Select(ds => new ProjectViewDto(ds.ProjectId!.Value, ds.Project!.Name));
  }
}`
