### ISSUE TITLE
Take advantage of Bulk Operations with ExecuteDelete and ExecuteUpdate

### ISSUE THREAD

**Issue by shahabfar** [ardalis/Specification#298]
Actually, this is a proposal and not an issue.
Now that Entity Framework 7 introduces Bulk Operations with ExecuteDelete and ExecuteUpdate that would be nice to have new methods UpdateBySpecAsync and DeleteBySpecAsync in this great class library.

**Comment by fiseni** [comment]
Hi @shahabfar,

We'll think about this. I don't think the specs should change at all. Do you need new repository methods? `ExecuteDelete` and `ExecuteUpdate`? We're trying to keep the repo implementation as thin and simple as possible. You can extend them with your additional methods.

Did you have something else in mind? How do you envision the usage?

**Comment by shahabfar** [comment]
Hi @fiseni 
Sure I can extend it to use my needs if you want to keep the package thin.

**Comment by marianul** [comment]
Extending the repository it is not so trivial - the context is private:

private readonly DbContext dbContext;

**Comment by ardalis** [comment]
Ah, that could certainly be protected instead.

**Comment by marianul** [comment]
I used Reflection for now, thanks

**Comment by fiseni** [comment]
No, no, you don't have to do that. That `dbContext` is intentionally defined as private since you shouldn't bother working with it. The base repository is an abstract one, and it uses a base `DbContext` as a state, not a specific one. You're the one providing your specific `DbContext`, so you can work with it directly. Here is an example.

```c#
public interface IRepository<T> : IRepositoryBase<T> where T : class
{
    Task SomeExtraMethod();
}

public class Repository<T> : RepositoryBase<T>, IRepository<T> where T : class 
{
    private readonly AppDbContext _dbContext;

    public Repository(AppDbContext dbContext) : base(dbContext) 
    {
        _dbContext = dbContext;
    }

    // If you need to add methods
    public async Task SomeExtraMethod()
    {
        // use the _dbContext here
        _ = _dbContext.Customers;
        await Task.CompletedTask;
    }

    // If you need to override some method
    public override Task<List<T>> ListAsync(ISpecification<T> specification, CancellationToken cancellationToken = default)
    {
        // use the _dbContext here.
        return base.ListAsync(specification, cancellationToken);
    }
}
```

Then you register in DI as follows:

```c#
var connectionString = builder.Configuration.GetConnectionString("AppDbConnection");
builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlServer(connectionString));
builder.Services.AddScoped(typeof(IRepository<>), typeof(Repository<>));
```

**Comment by marianul** [comment]
thank you @fiseni.

**Comment by ardalis** [comment]
We're intentionally keeping the `dbContext` private so that when you inherit from the base repo, if you need an instance of your dbContext, you can have one that is typed with your specific `AppDbContext` and not just the `DbContext` that is in the base field.
