### ISSUE TITLE
How to filter query when using a valueobject with HasConversion?

### ISSUE THREAD

**Issue by fp-jcorriveau** [ardalis/Specification#301]
Let's say I use a ValueObject for a ZipCode, and I have a Converter to save it as a string in the database.

```c#
// EntityTypeConfiguration
builder.Property(p => p.ZipCode)
    .HasConversion<ValueOfConverter<ZipCode, string>>()
    .HasMaxLength(PostalCodeMaxLength)
    .IsRequired();
```

When I'm doing a search, I have to cast like this or else I get and exception

```c#
// Query 
Query.Search(x => (string)(object)x.ZipCode, zipCode);
```

**Comment by fiseni** [comment]
Hi @fp-jcorriveau,

The `Search` feature in our specs translates to `EF.Functions.Like` in EF Core. So, it's usually intended to be used with string properties.
From the usage above, you don't even need the Like functionality. Simply use `Where` clause, `Query.Search(x => x.ZipCode = zipCode);`, where the `zipCode` is not a string but your custom type. EF takes care of the conversion automatically.

**Comment by fp-jcorriveau** [comment]
The Where clause does not translate to EF.Functions.Like and it's want is actually wanted here.
The ZipCode is a "Domain Primitive" represented by a string.

I would expect this to work since there is a Converter `ValueOfConverter<ZipCode, string>`
```
Query.Search(x => x.ZipCode, zipCode);
```

**Comment by fiseni** [comment]
Hi @fp-jcorriveau,

Once you define a value converter, you should work with the custom type only and not access the underlying persisted type. The conversion is done by EF automatically.

In order to understand it better, can you please post the `ZipCode` and `ValueOfConverter` implementations?

Here is a full sample app that demonstrates the standard usage. If possible, update it with your type and converter. Then we'll discuss the usage.

```c#
using Ardalis.Specification;
using Ardalis.Specification.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

var connectionString = "Server=(localdb)\\mssqllocaldb;Database=SpecValueConverterDb;Trusted_Connection=True;";
var dbContextOptions = new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(connectionString).Options;

using (var dbContext = new AppDbContext(dbContextOptions))
{
    await dbContext.Database.EnsureDeletedAsync();
    await dbContext.Database.EnsureCreatedAsync();

    var customers = new List<Customer>
    {
        new Customer {Type = new CustomerType(1)},
        new Customer {Type = null},
        new Customer {Type = new CustomerType(3)}
    };

    dbContext.Customers.AddRange(customers);
    await dbContext.SaveChangesAsync();
}

using (var dbContext = new AppDbContext(dbContextOptions))
{
    var repo = new Repository<Customer>(dbContext);
    var spec = new CustomerSpec(new CustomerType(3));

    var result = await repo.ListAsync(spec);

    Console.WriteLine($"Found {result.Count} records!");
}

class CustomerSpec : Specification<Customer>
{
    public CustomerSpec(CustomerType type)
    {
        Query.Where(x => x.Type == type);
    }
}

interface IRepository<T> : IRepositoryBase<T> where T : class
{
}

class Repository<T> : RepositoryBase<T> where T : class
{
    public Repository(AppDbContext dbContext)
        : base(dbContext)
    {
    }
}

class CustomerType
{
    public int Value { get; }

    public CustomerType(int value)
    {
        Value = value;
    }
}

class Customer
{
    public int Id { get; set; }
    public CustomerType? Type { get; set; }
}

class AppDbContext : DbContext
{
    public DbSet<Customer> Customers => Set<Customer>();

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>().Property(x => x.Type).HasConversion(x => x!.Value, x => new CustomerType(x));
    }
}
```

**Comment by fp-jcorriveau** [comment]
It is understood.
As stated, my problem `is not` using the `Where` clause, but the `Search` method that should be translated to a SQL LIKE function.

Try replacing this 
```c#
class CustomerSpec : Specification<Customer>
{
    public CustomerSpec(CustomerType type)
    {
        Query.Where(x => x.Type == type);
    }
}
```

With this instead
```c#
class CustomerSpec : Specification<Customer>
{
    public CustomerSpec(CustomerType type)
    {
        Query.Search(x => x.Type, type); // compilor error ??
    }
}
```

To get rid of this error, as a workaround I have to cast as object and as string. It works since it's not really executing the expression, it only use it to translate to SQL.

**Comment by fiseni** [comment]
I'm trying to explain that you can't do that. The `Like` operator should be used only with string properties, and you don't have a string property, you have a custom type `ZipCode`. It's not about this library. You can't do the following in EF, and you'll get a compile error.

```c#
await dbContext.Customers
        .Where(x => EF.Functions.Like(x.Type, "%ype%"))
        .ToListAsync();
```

Yes, you can box it to an object first and trick the EF, but it accidentally works with this version. There is no guarantee it will work in the next version, they may decide to interpret the expression tree differently. The API is clear, it expects the property to be a string. 

So, if you need to search the content of the column partially (e.g. Like), then perhaps should not be represented with a value object. It should be a pure string property.

**Comment by ardalis** [comment]
@fp-jcorriveau is there anything else we can do to help you? reopen if so.
