### ISSUE TITLE
Specification pagination properties

### ISSUE THREAD

**Issue by VusalDev** [ardalis/Specification#304]
What is the meaning of these properties? These properties are internal, and nothing can be done with them.
```
public class Specification<T> : ISpecification<T>
  {
     /// <inheritdoc/>
    public int? Take { get; internal set; } = null;

    /// <inheritdoc/>
    public int? Skip { get; internal set; } = null;
}
```
All the examples I've seen use parameters from the constructor 
`Query.Skip(skip).Take(take)`

**Comment by r2baka** [comment]
It's for paging. .Skip(100).Take(10); // to get the 11th page of records; telling the database to only send 10 records, not 110, and then just looping over the first hundred in code. Saves a lot of database network traffic and lots of other goodies. Optimizes everything.

**Comment by VusalDev** [comment]
I mean these properties cannot be used in a child class, because they are internal. Therefore, it is not clear to me why these properties were added to the Specification class.

**Comment by tnlthanzeel** [comment]
isnt skip take pagination slow? should we move to keyset keyset pagination as explain here https://learn.microsoft.com/en-us/ef/core/querying/pagination#keyset-pagination?

**Comment by VusalDev** [comment]
> 

I guess it doesn't work with GUID primary keys
