### ISSUE TITLE
EF Hierarchy, OfType

### ISSUE THREAD

**Issue by muratyuceer** [ardalis/Specification#305]
Hello,

How can I use OfType feature in the specification?

**Comment by fiseni** [comment]
No. Specifications are intended to be very simple and built for a specific entity.

What is your use case?

**Comment by muratyuceer** [comment]
For example
You have
User class
Customer : User
Employee : User
Then if you want to create GetUsersByTypeSpec(User userType) you cant use OfType

**Comment by fiseni** [comment]
That would require creating the generic spec type by reflection, and we try to avoid it if there is no significant benefit.
In your case, you can simply have a base specification for `User`, and then have separate specific specs for `Customer` and `Employee` inheriting the base spec.

**Comment by muratyuceer** [comment]
Thanks for help. I thinked like
GetUsersByTypeSpec<T> where T : User

**Comment by fiseni** [comment]
Yes, that's what I meant with the base class. For example, you may have this specification

```c#
public class UserSpec<T> : Specification<T> where T : User
{
    public UserSpec(int id)
    {
        Query.Where(x => x.Id == id);
    }
}
```

Then, either use that one directly, like `var spec = new UserSpec<Customer>(1);`. Or you may define a specific specification for `Customer` and `Employee`, and simplify the usage as `var spec = new CustomerSpec(1);`

```c#
public class CustomerSpec : UserSpec<Customer>
{
    public CustomerSpec(int id) : base(id)
    {
    }
}
```

Let me know if you're ok with these answers and whether we should close the issue.

**Comment by muratyuceer** [comment]
Thank you for your help, you can close 

```
public class UserSpec<T> : Specification<T>, ISingleResultSpecification<T> where T : User
{
    public UserSpec(Guid userId)
    {
        Query.Where(c => c.Id == userId);
    }
}
```

**Comment by fiseni** [comment]
You can use the `SingleResultSpecification<T>` to simplify it a bit. It implements the interface.

```c#
public class UserSpec<T> : SingleResultSpecification<T> where T : User
{
    public UserSpec(Guid userId)
    {
        Query.Where(c => c.Id == userId);
    }
}
```
