### ISSUE TITLE
Keyset pagination

### ISSUE THREAD

**Issue by tnlthanzeel** [ardalis/Specification#306]
Hi, is there any thought to implement keyset pagination which is explain here https://learn.microsoft.com/en-us/ef/core/querying/pagination#keyset-pagination to replace the skip() take() pagination which is very slow?

**Comment by fiseni** [comment]
Hi @tnlthanzeel,

If you want to utilize keyset pagination, nothing prevents you to do it even now. Keyset pagination is a concept based on filtering, and you already can apply `Where` clauses.

Did you mean something else?

**Comment by tnlthanzeel** [comment]
what you said was correct, yea, we have to do the keyset pagination. what you said makes sense, thanks.
