### ISSUE TITLE
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed.

### ISSUE THREAD

**Issue by cwbrandsdal** [ardalis/Specification#307]
I get the error message "System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext" sometimes when I have a blazor server page that uses sub components that have different IRepository injected into them. And they all have code that gets data from the db on OnInitializedAsync.

I guess I'm using repositories all wrong. How can I make this safe? When I use the DBContext directly it all works fine. How can I work around this?

So sorry if this is a completely wrong place for this post.

**Comment by fiseni** [comment]
Hi @cwbrandsdal,

What is the scope of the registered services in DI? I haven't used Blazor sub-components, do they all run within the same scope? If that's the case, and if they are run in separate threads, then yea you'll face that issue.

When using DbContext directly, it works fine? Are you injecting the DbContext, or you're creating it manually? If you're injecting it, is it registered as transient or scoped? If you register the DbContext and the repository implementations as transient services, then you won't have that issue. But, be aware that each action will be "atomic", if you have some sort of chaining, then you'll lose the state.

**Comment by adriandrei** [comment]
Without seeing any code, I'm guessing that the blazor sub component is either getting its IRepository instances injected through component injection `(@inject IRepository<T>)` or being passed through parameters `[Parameter]` by the parent component , but in either case, if the DbContext is added to the IoC container as scoped (which is the default setting when using the default `builder.Services.AddDbContext(Action<DbContextOptionsBuilder> options)`), then that exception is thrown when trying to do something like: 

```cs
var taskA = firstRepository.ListAsync(); 
var taskB = secondRepository.ListAsync();
await Task.WhenAll(taskA, taskB)
```

To get around this, you'll either have to update the IoC injection and add the DbContext and IRepository types as transient or individually and sequentially await the tasks you might be awaiting together like in the above example.

**Comment by ardalis** [comment]
@cwbrandsdal let us know if this didn't fix your issue.
