### ISSUE TITLE
Is this suitable for use with Blazor?

### ISSUE THREAD

**Issue by mojoejoejoe** [ardalis/Specification#315]
I understand its better to use a context factory with Blazor to avoid scope issues. I currently use it and get "a second operation was started on this context.." warnings

**Comment by yoshiyes** [comment]
Hello,

The problem does not come from the library, but the way EntityFramework works with Blazor. 
I didn't recommend to use Ardalis Specification with Blazor Server.

Maybe, this PR #289 will introduce a new way to work with.

**Comment by ardalis** [comment]
I recommend my clients avoid Blazor Server because of the EF lifetime issues it has. Blazor WebAssembly avoids all such issues by working with APIs, and EF (and Specifications) work great in APIs.

**Comment by pavloss** [comment]
While I do agree with the API first approach, the PR #289 looks quite useful and worth looking into.
