### ISSUE TITLE
Managing multiple chained sorting options

### ISSUE THREAD

**Issue by cotepatrice** [ardalis/Specification#321]
In our app that uses the Ardalis Specification implementation we have a lot of client DataGrids that are bound to "ListResults" Dto. The backend service use an ApiEndpoint with a "ListRequest" Dto from query that is then used in a custom specification.

Since all the grids can be ordered by all their fields, with chained priority (OrderBy("fieldA").ThenByDescending("fieldB").ThenBy("fieldC"), etc.) we implemented an OrderByExtension, based on the thread #53. So the client web app can use a string with field names and sort order separated by comas. It works very well. BUT, this is far from perfect, since I use reflection on the Type T to build my OrderExpressionInfo. And since it comes from the specification, it uses the Entity type and properties. So if there is a difference between the property name in the ListResult (which the DataGrid uses to build it's query params in the endpoint URI) and the Entity's property name, it won't work.  

Here's a sample code to show you. You will see that the client will use the **FirstName** property to make its query param (it will look like "_<service_uri>_/api/customers?StoreId=234&**OrderBy="Name ASC,FirstName DESC"**) while this doesn't exists on the Entity since the corresponding property is "**Surname**".  My question is : is there a way to validate the field names on the Dto type BUT map it somehow to the entity property to build the OrderExpressionInfo? To keep Core implementation of the domain objects abstracted from clients.

Endpoint

```csharp
[HttpGet("api/customers")]
    public override async Task<ActionResult<IEnumerable<ListDemoResult>>> HandleAsync(
        [FromQuery] ListDemoRequest request,
        CancellationToken cancellationToken = new())
    {
        CustomerFilter filter = new CustomerFilter { StoreId = request.StoreId };
        List<Customer> customer = await _repository.ListAsync(new CustomerListSpecification(filter, skip: request.Skip, take: request.Take, orderBy: request.OrderBy),
            cancellationToken);

        return Ok(customer.Select(ListDemoResult.FromCustomer));
    }
```

Specifications

```csharp
public class CustomerListSpecification : ListDemoSpecification<Customer>
{
    public CustomerListSpecification(CustomerFilter filter, int? skip = null, int? take = null, string? orderBy = null)
        : base(skip, take, orderBy)
    {
        Query.Where(p =>
            p.Name == filter.Name || p.Surname == filter.Surname);
        
        if (!string.IsNullOrWhiteSpace(orderBy))
        {
            Query.OrderBy(orderBy);
        }
    }
}

public class ListDemoSpecification<T> : Specification<T>
{
    public ListDemoSpecification(int? skip = null, int? take = null, string? orderBy = null)
    {
        if (skip.HasValue)
        {
            Query.Skip(skip.Value);
        }

        if (take.HasValue)
        {
            Query.Take(take.Value);
        }
    }
}
```

Request and Result Dtos

```csharp
public class ListDemoRequest
{
    public Guid StoreId { get; set; }
    
    public Guid CustomerId { get; set; }
    public string OrderBy { get; set; } = nameof(EntityBase.Id);
    public int? Skip { get; set; }
    public int? Take { get; set; }
}

public class ListDemoResult
{
    public Guid StoreId { get; set; }
    public Guid CustomerId { get; set; }
    public string? Name { get; set; }
    public string? FirstName { get; set; }
    public int Age { get; set; }
    public DateTime BirthDate { get; set; }
    public static ListDemoResult FromCustomer(Customer customer)
    {
        return new ListDemoResult()
        {
            StoreId = customer.StoreId,
            CustomerId = customer.CustomerId,
            Name = customer.Name,
            FirstName = customer.Surname,
            Age = customer.Age,
            BirthDate = customer.BirthDate
        };
    }
```

And last but not least, the OrderByExtension made from the issue #53 

```csharp
public static class OrderByExtensions
{
    public static OrderedSpecificationBuilder<T> OrderBy<T>(
        this ISpecificationBuilder<T> specificationBuilder,
        string orderByFields)
    {
        if (ParseOrderBy(orderByFields) is { } fields)
        {
            foreach (var field in fields)
            {
                var matchedProperty = typeof(T).GetProperties().FirstOrDefault(p => p.Name.ToLower() == field.Key.ToLower());
                if (matchedProperty == null)
                    throw new ArgumentNullException(paramName: field.Key);
    
                var paramExpr = Expression.Parameter(typeof(T));
                var propAccess = Expression.PropertyOrField(paramExpr, matchedProperty.Name);
                var propAccessConverted = Expression.Convert(propAccess, typeof(object));
                var expr = Expression.Lambda<Func<T, object?>>(propAccessConverted, paramExpr);

                ((List<OrderExpressionInfo<T>>)specificationBuilder.Specification.OrderExpressions)
                    .Add(new OrderExpressionInfo<T>(expr, field.Value));
            }
        }
        var orderedSpecificationBuilder = new OrderedSpecificationBuilder<T>(specificationBuilder.Specification);
    
        return orderedSpecificationBuilder;
    }
    
    private static IDictionary<string, OrderTypeEnum> ParseOrderBy(string orderByFields)
    {
        var result = new Dictionary<string, OrderTypeEnum>();
        var fields = orderByFields.Split(',');
        for (var index = 0; index < fields.Length; index++)
        {
            var fieldAndOrder = fields[index].Split(' ');
            var field = fieldAndOrder[0];
            var order = fieldAndOrder.Length > 1 ? fieldAndOrder[1] : string.Empty;
            var orderBy =  order.ToUpper() == "DESC" ? OrderTypeEnum.OrderByDescending : OrderTypeEnum.OrderBy;
            if (index > 0)
            {
                orderBy = order.ToUpper() == "DESC" ? OrderTypeEnum.ThenByDescending : OrderTypeEnum.ThenBy;
            }
            result.Add(field.Trim(), value: orderBy);
        }
        return result;
    }
}
```

**Comment by fiseni** [comment]
Hi @cotepatrice 

This is a common problem. It has nothing to do with this library, but with the concept of ordering in general; and the fact that the exposed properties in API model do not necessarily have the same names as the properties in the entities. Usually, I highly discourage using these generic solutions. At first glance, it seems very appealing, but in practice, it's not. Let me list a few possible drawbacks:

- The property names in your API models and entities may not match. So, the `orderBy` query parameter simply refers to a non-existent property/column. The exact issue that you're facing.
- The ordering is an expensive operation (especially multi-level ordering), and you should have indexes for those columns in the database.
- The possibility for server-side ordering by all columns, it's not a feasible feature in practice. You'll have to define indexes for all columns. That's not a great DB design.
- Trying to implement this generically will involve a lot of reflection, which will additionally slow the execution.

A much more practical solution would be:
- Define the columns that support ordering, a few of them. This can be implemented as a dropdown in UI perhaps?
- The grid may additionally support ordering for all columns, but only client-side (the data that is already fetched).
- Create the mapping manually for the defined columns.

Here is a sample solution. Create an extension to the builder, so you can reuse the same logic in all your customer specifications.

```csharp
public static class CustomerSpecificationExtensons
{
  public static IOrderedSpecificationBuilder<Customer> ApplyOrdering(this ISpecificationBuilder<Customer> builder, string sortBy, string orderBy)
  {
    var isAscending = !orderBy?.Equals("desc", StringComparison.OrdinalIgnoreCase) ?? false;

    return sortBy switch
    {
      "FirstName" => isAscending ? builder.OrderBy(x => x.FirstName) : builder.OrderByDescending(x => x.FirstName),
      "LastName" => isAscending ? builder.OrderBy(x => x.Surname) : builder.OrderByDescending(x => x.Surname),
      _ => builder.OrderBy(x => x.Id)
    };
  }
}

public class CustomerSpec : Specification<Customer>
{
  public CustomerSpec(string sortBy, string orderBy)
  {
    Query.ApplyOrdering(sortBy, orderBy);
  }
}
```

This is just a sample to demonstrate how to create extensions to the builder. I assume you'll be passing a single string that contains many columns and their orientation, so you have to work on the implementation.

**Comment by fiseni** [comment]
Btw, if you still want to have that generic solution, then just create a mapper that holds a dictionary. You can define it as a singleton since it's not a mutable object anyway. Pass it to the spec and down to your order extension. Then, you just get the corresponding entity property name and keep the existing logic you have.

```csharp
public class CustomerMapper
{
  public static CustomerMapper Instance { get; } = new CustomerMapper();
  private CustomerMapper() { }

  public Dictionary<string, string> Map { get; } = new()
  {
    [nameof(CustomerDto.FirstName)] = nameof(Customer.FirstName),
    [nameof(CustomerDto.LastName)] = nameof(Customer.Surname),
  };
}
```

If you have separate projects, and your domain project doesn't have access to dtos, then perhaps just define an interface and let the consumer provide the implementation (CustomerMapper will live in the API layer). Or, even simpler, pass the dictionary to the spec.

```csharp
public interface ICustomerMapper
{
  Dictionary<string, string> Map { get; }
}
```

**Comment by fiseni** [comment]
Closing the issue due to inactivity. Feel free to re-open if you have further questions.
