### ISSUE TITLE
Example using dbcontextfactory?

### ISSUE THREAD

**Issue by marcusjm** [ardalis/Specification#325]
Is it possible to use this in conjuction with Dbcontextfactory? I am just wondering since RepositoryBase uses the regular DbContext.

**Comment by marcusjm** [comment]
Nevermind, I just realised there is a Factory version now. It wasn't in the eshop example so I missed it

**Comment by pavloss** [comment]
This isn't available in the current release, but you can have a look at this [PR 289](https://github.com/ardalis/Specification/pull/289).
I believe this is what you are looking for.

**Comment by marcusjm** [comment]
I realised too late that this was scheduled for 15/5. I will wait :)

**Comment by joedirt** [comment]
Is there an example of this?  I'm trying to figure out how to get my functioning code, which uses DI and IRepository converted to the dbcontextfactory concept.  I'm not succeeding and an example would be appreciated.  Thanks

**Comment by fiseni** [comment]
The feature is already published some time ago in version 7. The feature was a contribution from a community member, and there are a few tests [here](https://github.com/ardalis/Specification/blob/main/Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/EFRepositoryFactoryTests.cs) where you can see the usage.

Feel free to reopen the issue if you have further questions.
