### ISSUE TITLE
Missing XML comments.

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#33]
We should add XML comments for all publicly visible types or members. This will improve the usage, intellisense will provide information to the end users. If you want to contribute, you are welcome to do so.

Instructions:
- On each public class, public property, public method, we should add XML comment.
- Just on top o the name of class/property/method start typing three slashes `///`. The VS automatically will create the skeleton for the XML comment. It looks as following:
```
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
```
- Try to analyze what that class or method does, and accordingly write in the comment.

In the end, anyhow we will try to review it, so don't get stuck too much :)

**Comment by ConnerOrth** [comment]
If the current style of xml comments/docs that I made is OK with you guys.
Then I'll try to add some more whenever I have some spare time ;)

**Comment by fiseni** [comment]
Oh great! Thanks @ConnerOrth.
Please go ahead, it's appreciated. Once we complete documenting it, we may revise it all together.

**Comment by ConnerOrth** [comment]
Would you prefer a single PR for all docs? Or shall I make a PR for each file?
Im guessing the single PR right?

**Comment by fiseni** [comment]
Whatever fits you better, it's not an issue. You can PR batches, not necessarily one file.

**Comment by ConnerOrth** [comment]
I'll try to get some more documentation going in the upcoming weeks/months.
Have been and still am going through some personal stuff, so sorry I and the documentation process just 'fell of the earth' for a while.

**Comment by fiseni** [comment]
No worries, take care of yourself. We thank you for your help so far.
