### ISSUE TITLE
Help about reuse includes

### ISSUE THREAD

**Issue by AlessandroMenchiniTmaxLab** [ardalis/Specification#330]
I can't figure out how to fix this: suppose I have a Customer with his contact details. I can create a Customer specification that includes contact details. But when the Customer appears in a LINQ query of an Order, if I wanted to get the Order with the Customer's details (including its contact details) how can I reuse the Customer specification without having to redo the inclusions in the Order? contact details? Maybe I didn't understand something...

Regards
Alessandro

**Comment by ardalis** [comment]
If you're using the Aggregate design pattern you probably will have separate aggregates for Order and Customer, and the two will only be linked by an ID (e.g. Order would have a `CustomerId` property of type `int` or `Guid` not of type `Customer`). Then if you needed to get details from customer in addition to order you would typically need to load the Customer aggregate(s) individually for each ID. Note that aggregates are all about maintaining invariants and business rules which 99% of the time apply only when you're mutating the state of the system.

If you are just querying data and you need a list of results (not an Aggregate) then a lot of the time you don't want to use Specifications. You're better of to use a separate abstraction (or no abstraction at all) that allows you to just fetch the data you need in the shape you want. For instance you could use the dbContext directly or Dapper plus some custom SQL or a stored procedure, and your result wouldn't be Orders or Customers but would instead by a DTO like `OrderSearchResult` which would have just exactly the data you needed in it.

Does that help?

**Comment by fiseni** [comment]
Closing the issue due to inactivity. Feel free to re-open the issue if you have further questions.
