### ISSUE TITLE
IDbCommandInterceptor not catching queries 

### ISSUE THREAD

**Issue by 4m-world** [ardalis/Specification#334]
I've added an ecryption layer to my DB context and at some point I want to query some records based on the encrypted value, hence I built a IDbCommandInterceptor that should catch these queries and modify passed relevant with an encrypted value.
after debugging the code I found that specification queries not catched by the interceptor, could you suggest a solution to handle this issue

**Comment by 4m-world** [comment]
Thank @fiseni 

Below the implementation of the repository:

`
public interface IRepository<T> : IRepositoryBase<T>
    where T : class, IAggregateRoot
{
}

public class ApplicationDbRepository<T> : RepositoryBase<T>, IReadRepository<T>, IRepository<T>
    where T : class, IAggregateRoot
{
    public ApplicationDbRepository(ApplicationDbContext dbContext)
        : base(dbContext)
    {
    }

    public virtual async Task<TResult> MaxAsync<TResult>(
        Expression<Func<T, TResult>> selector, 
        ISpecification<T> specification = null,
        CancellationToken cancellationToken = default)
    {
       return await ApplySpecification(specification, true)
             .MaxAsync(selector, cancellationToken);
    }

    // We override the default behavior when mapping to a dto.
    // We're using Mapster's ProjectToType here to immediately map the result from the database.
    protected override IQueryable<TResult> ApplySpecification<TResult>(ISpecification<T, TResult> specification) =>
        specification.Selector is not null
        ? base.ApplySpecification(specification)
        : ApplySpecification(specification, false).ProjectToType<TResult>();
}
`

Specification: 

`
internal class GetBankingDetailByAccountNrSpec : Specification<StoreBankingDetails>
{
    public GetBankingDetailByAccountNrSpec(string accountNumber, string excludeId = null)
    {
        Query.Where(e => e.AccountNumber.ToLower() == accountNumber.ToLower(), !string.IsNullOrWhiteSpace(accountNumber));
        Query.Where(e => e.Id != excludeId, !string.IsNullOrWhiteSpace(excludeId));
    }
}
`

DB Context
`
public abstract class BaseDbContext : MultiTenantIdentityDbContext<ApplicationUser, ApplicationRole, string, IdentityUserClaim<string>, IdentityUserRole<string>, IdentityUserLogin<string>, ApplicationRoleClaim, IdentityUserToken<string>>
{
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // TODO: We want this only for development probably... maybe better make it configurable in logger.json config?
        optionsBuilder.EnableSensitiveDataLogging();

        optionsBuilder.AddInterceptors(new EncryptedCommandExecutor(_encryptionProvider));

        if (!string.IsNullOrWhiteSpace(TenantInfo?.ConnectionString))
        {
            optionsBuilder.UseDatabase(_dbSettings.DBProvider!, TenantInfo.ConnectionString);
        }
    }
}

`

The call that does not trigger the command using the specification

`_repository.CountAsync(new GetBankingDetailByAccountNrSepc(value))`


Command interceptor implemented methods:
* ScalarExecuting/Asyc
* NonQueryExecuting/Asyc
* ReaderExecuting/Async

**Comment by 4m-world** [comment]
The issue was resolved after I restarted the workstation, apologies for the inconvenience, and thank for the support.

**Comment by fiseni** [comment]
Not a problem, enjoy. Glad that you fixed it.
