### ISSUE TITLE
Query.Dstinct()

### ISSUE THREAD

**Issue by samiyariceboy** [ardalis/Specification#341]
Hi
In the implementation of queries, there are the part where you need to use **Distinct** on the Sql side
And in your development library, it is not implement
Is it possible to explain or if it seems reasonable, add this to the code?

**Comment by fiseni** [comment]
Hi @samiyariceboy,

There are many features that are not supported. We don't pretend to be an ORM, or support every single feature of various ORMs. The specifications are designed for simple queries, and usually for fetching entities/aggregates that you intend to modify.

If you have complex queries, you should have dedicated query objects and use the full potential of the ORM you're using. I know folks are using specs also for read operations, but I discourage that. There is no reason to fetch entities and utilize the domain model for read operations, instead, you should project directly to the result.

Btw, you can also use the specs directly (without repositories) while building your queries and projecting the results. Here is an example of how to combine all that. You apply your spec, continue building it (distinct doesn't make sense here, but just for the sake of demonstration), and projecting (in this case Automapper just as an example)

```c#
var spec = new CustomerSpec(1);
var result = await _dbContext.Customers
  .WithSpecification(spec)
  .Distinct()
  .ProjectTo<CustomerDto>(_mapper.ConfigurationProvider)
  .ToListAsync();
```
