### ISSUE TITLE
Using library for non-SQL data sources

### ISSUE THREAD

**Issue by ps-tb** [ardalis/Specification#35]
Is it possible to use this library for building requests to non-SQL data sources? In the eShopOnWeb, example I see that the `EfRepository` uses an `EfSpecificationEvaluator`: 
![image](https://user-images.githubusercontent.com/45601014/88827321-d3172e00-d197-11ea-93b0-581b546ee891.png)

If I wanted to create a Repository that had an HTTP-based API source, is that possible using this library? As an example, if the HTTP-based API allowed me to search for users or their pets, each by their ID, I'd like to build a specification for each of those because their query parameters would be different (?user=<id> or ?pet=<id>). Or if I hated myself, could i use this library to build SOAP requests that a repository implementation used?

**Comment by ardalis** [comment]
Yes, theoretically if you can translate from the various elements of the Specification (filter, order, paging, etc) into platform specific operations, you would be able to use it for non-EF, non-SQL data stores. There's work coming soon that will better split out the packages to make it clear the EF stuff is separate. See: https://github.com/ardalis/Specification/tree/version4

**Comment by ps-tb** [comment]
Thanks for the quick response. I'll evaluate the effort to do this and if it fits with my goals.
