### ISSUE TITLE
Shadow properties

### ISSUE THREAD

**Issue by lars-lindstrom** [ardalis/Specification#364]
Sometimes it can be usefull to query against shadow properties, using either `Where` or `Search`.

Let's say we have an entity

```
public class TEntity
{
    public string Firstname {get; set;}
    public string Lastname {get; set;}
}
```

Currently I can only do `Where` or `Search `on either property not on "full name".
To solve this, I create a shadow property "Fullname" in EF.Core using modelbuilder and access this using `EF.Property<string>("Fullname")`

Unfortunately I cannot use EF.Property in the specification and perform i.e.
`Query(person=>EF.Property<string>("Fullname").Contains("Searchname"))`

Would it be possible to extend class to achieve this, or do I have to use `DbContext` (which I try to avoid)

**Comment by r2baka** [comment]
>do I have to use DbContext (which I try to avoid)
I do know the answer to that is no.

You can do something like q.Where(p => (p.Firstname + ' ' + p.Lastname).Contains(searchname));

That doesn't solve problems like the duplication of code to calculate the fullname, but it does help you avoid DbContext.

For the general case like this, where I want to avoid DbContext, but still have deeper flexibility on my queries, I just made a ListBySQL method on the repository, which comes in very handy for difficult use cases for the Query. but you kinda have to like SQL.

    public class EfRepository<T> : IAsyncRepository<T> where T : BaseEntity, IAggregateRoot
    {
...
        public async Task<IReadOnlyList<T>> ListBySQLAsync(string sql, object[] parameters)
        {

                return await _dbContext.Set<T>().FromSqlRaw(sql, parameters).ToListAsync();

        }

Alternatively, you could also create a calculated field on the data set where a column FullName = Firstname + ' ' + Lastname
https://learn.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver16

**Comment by fiseni** [comment]
Hi @lars-lindstrom 

You can have the following specification

```csharp
public class CustomerSpec : Specification<Customer>
{
    public CustomerSpec(string someValue)
    {
        Query.Where(x => EF.Property<string>(x, "Fullname").Contains(someValue));
    }
}
```

Also, you have to configure the shadow properties in your `EF Core` configuration. It would be something as follows:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Customer>().Property<string>("Fullname");
}
```

You don't depend on `DbContext` in the specification, but still, you depend on the static `EF` class which is defined in `Microsoft.EntityFrameworkCore`. So, you'll depend on `EF Core`, if that's what you mean.
If you're asking for a mechanism to abstract that dependency, then we don't plan to implement that, unfortunately. It can be implemented through reflection and dynamically build the expression. But, we're trying to avoid reflection as much as possible, especially now that .NET is serious about AOT. Also, there is no good way to generalize the usage. You're thinking only in terms of `Contains`, but the expression inside the `Where` can be anything (e.g. `Any`, `Equals`, etc.). What would the new API look like?

Specifications are intended to operate against a defined domain model. The shadow properties, by definition, are not part of it. You might reconsider the need for a shadow property. What's exactly your case? I assume you have such a column in the database right? Then, why not add the property to the model?

**Comment by fiseni** [comment]
Hey @lars-lindstrom,

Do you have any further questions or comments? Should we close this issue?

**Comment by fiseni** [comment]
Closing the issue due to inactivity. If you have further questions or comments, please feel free to reply.
