### ISSUE TITLE
Question: Can I some how join table "B" when my entity T does not have a navigation property to "B" ?

### ISSUE THREAD

**Issue by nschoenberg** [ardalis/Specification#366]
Hi,

I have a scenario where I need to join a Table and my entity T that I have in my specification does not know about "B" in terms of navigation or relation.
I am able to write the desired query when using DbContext where I have DbSet<T> and DbSet<B> available. 

Is it some how possible? I am unable to find a way :)

Thanks in advance

**Comment by fiseni** [comment]
Hi @nschoenberg,

Whatever expression is supported in the `Include` statement, you'll be able to use it with this library too.
When you have not defined navigations, usually you have to switch to LINQ query syntax. It would be something as follows:

```csharp
var query = from c in dbContext.Customers
            join a in dbContext.Addresses on c.Id equals a.CustomerId
            select new { c.Id, c.Name, a.Street };
```

This is not supported in this library. The specifications are intended to be used against your domain model. I assume in your case, you have some complex read operation (perhaps for reporting). For such scenarios, I'd not suggest using specifications, or your domain model at all. Instead, utilize the full potential of your ORM (or even have pure SQL statements) and project directly to response models.

**Comment by nschoenberg** [comment]
@fiseni Thanks a lot!
