### ISSUE TITLE
Expression Evaluation

### ISSUE THREAD

**Issue by Jimmy-Ahmed** [ardalis/Specification#367]
Hi, 

Is there a way to evaluate/convert the `IEnumerable<WhereExpressionInfo<T>> WhereExpressions`  to `Expression<Func<T, bool>> ` 

Thanks,

**Comment by fiseni** [comment]
Not sure what are your requirements, but if you're trying to apply a given specification against in-memory data, that is already available out of the box. Here is a sample

```csharp
var spec = new CustomerSpec();
var customers = new List<Customer>();
var evaluatedCustomers = spec.Evaluate(customers);
```

**Comment by Jimmy-Ahmed** [comment]
Thanks for your quick reply. I am asking if I can  evaluate/convert **to** `Expression<Func<T, bool>>` meaning reducing all the `IEnumerable<WhereExpressionInfo<T>> WhereExpressions` to a single `Expression`

The reason I want to do this I wanna use the Specification against AzureTableStorage but their API does not support `IQuerable` they only accept `Expression<Func<T, bool>>` So I want to convert `IEnumerable<WhereExpressionInfo<T>> WhereExpressions`  to `Expression<Func<T, bool>>` and pass it as a parameter to their API

**Comment by fiseni** [comment]
Hey @Jimmy-Ahmed,

Yea, it can be done. It's not directly related to this library, you just need to merge the expressions.
Here is an extension for you

```csharp
public static class SpecExtensions
{
    public static Expression<Func<T, bool>>? MergeWhereExpressions<T>(this ISpecification<T> spec)
    {
        Expression? result = null;
        var parameter = Expression.Parameter(typeof(T), "x");

        foreach (var expression in spec.WhereExpressions.Select(x => x.Filter))
        {
            var expr = ParameterReplacerVisitor.Replace(expression, expression.Parameters[0], parameter) as LambdaExpression;
            _ = expr ?? throw new InvalidExpressionException();

            result = result is null
                ? expr.Body
                : Expression.AndAlso(result, expr.Body);
        }

        return result is null
            ? null // If the input is empty collection, what do you want to return? null?
            : Expression.Lambda<Func<T, bool>>(result, parameter);
    }
}
public class ParameterReplacerVisitor : ExpressionVisitor
{
    private readonly Expression _newExpression;
    private readonly ParameterExpression _oldParameter;

    private ParameterReplacerVisitor(ParameterExpression oldParameter, Expression newExpression)
    {
        _oldParameter = oldParameter;
        _newExpression = newExpression;
    }

    public static Expression Replace(Expression expression, ParameterExpression oldParameter, Expression newExpression)
      => new ParameterReplacerVisitor(oldParameter, newExpression).Visit(expression);

    protected override Expression VisitParameter(ParameterExpression p)
      => p == _oldParameter ? _newExpression : p;
}
```

And the usage
```csharp
var spec = new CustomerSpec();
var expr = spec.MergeWhereExpressions();
```

**Comment by Jimmy-Ahmed** [comment]
Thanks a lot! This works like a charm :) I have a final question is there a way to convert/evaluate `Expression<Func<T, TResult>> Selector` to a list of strings meaning if you have a selector to get Prop1, prop2, prop3 for example and you called something like
`Selector.ToStringSelector()` this would return a list of strings containing "Prop1", "Prop2", "Prop3"
Thanks in advance...

**Comment by Jimmy-Ahmed** [comment]
It failed on the edge cases like `Score = p.Scores[0]` however it was a good start. Thanks for sharing :)

**Comment by fiseni** [comment]
Hey, @Jimmy-Ahmed. 
I assume Steve's suggestion gave you some hints on how to move forward. I'm closing this issue. If you have further questions regarding the library, let us know.
