### ISSUE TITLE
Specification - Include with Where clause

### ISSUE THREAD

**Issue by radoslavrobes** [ardalis/Specification#376]
Hi 
i'd like to ask reg. Include and Where clause. I was looking into your old issues, and i think it might work, but for some reason, when I use following spec:
```

public class SearchSchoolsWithEventSpec : EntitiesByBaseFilterSpec<F3.Domain.Entities.School, SchoolDto> 
{
    public SearchSchoolsWithEventSpec(SearchSchoolsWithEventRequest request)
        : base(request) =>
        Query
        .Include(x => x.Events.Where(p => p.EventStatusId == 2))
        .Where(p => p.Name.ToLower().Contains(request.Filter));
}

```

It returns me all schools, but filter for Event's doesn't work probably, as it returns all Events with all statuses.
Any idea what migth be the issue?

At the end, i would need to return only school with event with that specific ID. Maybe if i can filter out all event with status 2, then another filter where if there are no events would remove that school.
Thanks a lot for your help

**Comment by fiseni** [comment]
Hi @radoslavrobes 

I'm not sure if I understood you correctly, but you want to get all schools that have at least an event with a given status, right?
If that's the case, then the filter in `Include` won't help you. That doesn't filter the schools, but which events to include.

I believe you'd need the following query.

```csharp
public class SearchSchoolsWithEventSpec : EntitiesByBaseFilterSpec<F3.Domain.Entities.School, SchoolDto>
{
    public SearchSchoolsWithEventSpec(SearchSchoolsWithEventRequest request)
        : base(request) =>
        Query
        .Where(p => p.Events.Any(p => p.EventStatusId == 2))
        .Where(p => p.Name.ToLower().Contains(request.Filter));
}
```

Btw, this is not specific to this library. It's how EF works. You can also cross-check EF docs whenever you want to customize some query.
