### ISSUE TITLE
Strange behavior when compare DateTime

### ISSUE THREAD

**Issue by Arestis** [ardalis/Specification#377]
Hi. Next line works fine
`Query.Where(s => s.Id == id && listOfDate.Any(d => d == s.Date));`
but this one `Query.Where(s => s.Id == id && listOfDate.Any(d => d > s.Date));` throw invalidOperationException     which said that can`t translate query
if thats normal behavior please explain why second line doesnt work?

**Comment by ardalis** [comment]
If you try the same thing directly with a dbContext, I assume you will see the same error. It's an issue with how EF Core translates LINQ to SQL and what it supports (I'm 99% sure).

**Comment by Arestis** [comment]
Thanks. I found that I can use PostProcessing for my case

**Comment by fiseni** [comment]
Closing the issue.
