### ISSUE TITLE
InMemory SearchExtension bug

### ISSUE THREAD

**Issue by Jordy84** [ardalis/Specification#390]
There is a bug in the `SearchExtension` class used by the InMemory SearchEvaluator.

When the input string contains the requested pattern, BUT the first character of said pattern is used in the power of 2, the result is false.

Note the amount of 'a' characters in the screenshot

![image](https://github.com/ardalis/Specification/assets/4329963/a60890f4-fc84-484f-95cc-00eec7fd75b6)

**Comment by fiseni** [comment]
Hi @Jordy84,

We're aware that the in-memory implementation might fail in certain edge cases. The `Like` operator is quite complex, and it lacks standardization across different database providers. So, it's unlikely that we'll ever have 1:1 match in functionality.

But, your case contains quite basic usage, and it's an obvious bug. We must fix it. Thanks for reporting it.

**Comment by fiseni** [comment]
Ok, this turned out to be trickier than I anticipated.
I implemented it using regex (after many trials and errors). It will not be as performant as the previous version, but at least it behaves correctly.

**Comment by Jordy84** [comment]
Thank you for the quick fix!
