### ISSUE TITLE
Еnhancement Request: Support for Multiple ThenInclude in a Single Include

### ISSUE THREAD

**Issue by Zheorgyan** [ardalis/Specification#404]
**Issue:** Currently, when using Entity Framework Core with Ardalis library, there seems to be a limitation on how multiple ThenInclude statements can be used for a single Include. Or Maybe i am doing something wrong, if so could you please provide information for that topic

**Request:** I would like to suggest enhancing to support multiple ThenInclude statements chained together for a single Include statement. This would provide more flexibility and simplify querying related entities with multiple levels of navigation properties.

**Example:**

**Before:**
```
var result = dbContext.ParentEntities
                    .Include(p => p.ChildEntity)
                        .ThenInclude(c => c.GrandChildEntity)
                    .Include(p => p.ChildEntity)
                        .ThenInclude(ac => ac.AnotherGrandChildEntity)
                    .ToList();
```

**After:**
```
var result = dbContext.ParentEntities
                    .Include(p => p.ChildEntity)
                        .ThenInclude(c => c.GrandChildEntity)
                        .ThenInclude(ac => ac.AnotherGrandChildEntity)
                    .ToList();
```

**Expected Behavior:** This should allow chaining multiple ThenInclude statements after a single Include statement to load multiple levels of related entities in a single query.

Thank you for considering this enhancement request.

**Comment by fiseni** [comment]
Hey @Zheorgyan,

These are two separate scenarios. We do have support for multiple `ThenInclude` statements, but that's for the scenario when your `GrandChildEntity` entity contains a navigation to `AnotherGrandChildEntity`.

I suppose you have an entity `ChildEntity` which has two navigations `GrandChildEntity` and `AnotherGrandChildEntity`. If that's the case, then you need option 1 in your example. The option 2 has a completely different meaning.

Makes sense?
