### ISSUE TITLE
AllAsync with Specification in RepositoryBaseOfT

### ISSUE THREAD

**Issue by HamedFathi** [ardalis/Specification#409]
Hi, 

In `RepositoryBaseOfT`, how can AllAsync be implemented with Specification?

```cs
    return await ApplySpecification(specification).AllAsync( ???, cancellationToken);
```

What should we do with the predicate parameter?

**Comment by fiseni** [comment]
Hey @HamedFathi,

The `AllAsync` API is defined as follows in EF.

```
public static Task<bool> AllAsync<TSource>(
	this IQueryable<TSource> source,
	Expression<Func<TSource, bool>> predicate,
	CancellationToken cancellationToken = default)
```

It's an extension to `IQueryable`, so you can apply your spec as you are doing above, but also you have to provide an additional predicate. This predicate may be supplied as a parameter to the repository method.

What is your actual use case here? I'd avoid using AllAsync, to be honest.

**Comment by HamedFathi** [comment]
Hi @fiseni 

As you mentioned this is an AllAsync API
```cs
public static Task<bool> AllAsync<TSource>(
	this IQueryable<TSource> source,
	Expression<Func<TSource, bool>> predicate,
	CancellationToken cancellationToken = default)
```

but when we are using a specification we have to define it like (if I am not wrong)

```cs
public static Task<bool> AllAsync<TSource>(
	this IQueryable<TSource> source,
	ISpecification<TSource> specification,
	CancellationToken cancellationToken = default)
```

So here `predicate` is replaced with `specification` so I have no extra predicate condition!

In other Specification implementations, we have a simple `ToExpression` for a specification class and then use it instead of a `predicate` clause so I wonder how this library works.

I have no practical use case I just to learn more about this library.

**Comment by fiseni** [comment]
I think there is a bit of a misconception here. I'll try to clarify better.
All termination methods (almost all) in EF do not require additional parameters. They act upon whatever is already in the `IQueryable` state. For instance, when you apply `Where` to DbSet, you get back `IQueryable` that already contains all your criteria. So, `ToList`, `FirstOrDefault` simply materializes the `IQueryable` state. That's how the specifications work too. They just build the IQueryable state for you.

On the other hand, the `AllAsync` on top of that state, requires additional predicate. I assume EF team did that to ensure that there will be at least one predicate in your query.

To summarize, if you do this, you will always get true as a result. EF will still apply whatever it is in the `IQueryable`, it's not ignoring that.

```c#
var result = await context.Customers
.Where(x => x.Age =40)
.AllAsync(x => x.Age = 40)
```

Back to your case, if you're sure that the specification will always contain a single `Where` clause, then you don't evaluate the specification at all, just pass the expression directly.

```c#
public virtual async Task<bool> AllAsync(Specification<T> specification, CancellationToken cancellationToken = default)
{
    return await _dbContext.Set<T>().AllAsync(specification.WhereExpressions.First().Filter, cancellationToken);
}
```

So, it all depends on what you're trying to achieve, and what stuff you want to use from the specification.
