### ISSUE TITLE
Lambda expression for multiple Include

### ISSUE THREAD

**Issue by ovation22** [ardalis/Specification#41]
Hi Steve,

I appreciate all the work on this that you (and community) have put into this. 

Is it possible to have multiple includes using expression syntax? I was able to chain includes using string then expression, but would really like to use the typed expressions if possible.

Expected behavior:

`Query.Include(x => x.foo).Include(x => x.bar)`

should compile and produce the same results as:

`Query.Include("foo").Include(x => x.bar)`

I'm happy to look into what it would take and will try to spend some time with it this weekend.

**Comment by fiseni** [comment]
Hi @ovation22,

Sure, you can do that. Just start with `Query` once again. In case of `Include` and `Order` functionalities, once you enter the second level, you can use only "Then" definitions, so you have to start over with `Query`.

```
Query.Include(x => x.foo);
Query.Include(x => x.bar);
```

It doesn't matter in which order you define the statements, or if you use chaining, or if you writing everything in separate statements. Whatever you add through the builder (named as `Query`), will be evaluated in predefined order.

Examples:

```
Query.Where(x => x.Name == "Something")
     .Paginate(10, 20)
     .Include(x => x.SomeProperty1)
         .ThenInclude(x => x.SecondLevelProperty1)
         .ThenInclude(x => x.ThirdLevelProperty1);
Query.Include(x => x.SomeProperty2);
```

The same can be written with all separate statements:

```
Query.Where(x => x.Name == "Something")
Query.Paginate(10, 20)
Query.Include(x => x.SomeProperty1)
          .ThenInclude(x => x.SecondLevelProperty1)
          .ThenInclude(x => x.ThirdLevelProperty1);
Query.Include(x => x.SomeProperty2);
Query.OrderBy(x => x.SomeProperty1)
         .ThenByDescending(x => x.SomeProperty2)
         .ThenBy(x => x.SomeProperty3;
```

**Comment by ovation22** [comment]
Ah, ok, that makes sense. Thank you so much!

**Comment by ShadyNagy** [comment]
Hello @fiseni 
is that possible? SecondLevelProperty1 and SecondLevelProperty2 from SomeProperty1 can get by this way or there is another way to get it?
```csharp 
Query.Where(x => x.Name == "Something")
     .Paginate(10, 20)
     .Include(x => x.SomeProperty1)
         .ThenInclude(x => x.SecondLevelProperty1)
     .Include(x => x.SomeProperty1)
         .ThenInclude(x => x.SecondLevelProperty2);
```

**Comment by ShadyNagy** [comment]
@fiseni Thanks so much
I will try to see how the EF will translate this code to SQL :)
