### ISSUE TITLE
Nullable reference types enabled, but not used

### ISSUE THREAD

**Issue by mrukas** [ardalis/Specification#42]
I noticed that nullable reference types are enabled in the project, but are not used where it would be necessary.
Shouldn't the methods of the IRepositoryBase interface for example somtimes declare their return types as nullable?

For example in this case: [Link](https://github.com/ardalis/Specification/blob/master/ArdalisSpecification/src/Ardalis.Specification/IRepositoryBase.cs#L16)
It would be more appropriate for this method `Task<T> GetByIdAsync(int id);` to be declared with a nullable return type like this: ` Task<T?> GetByIdAsync(int id);`. The ef implementation of the repository uses the `FindAsync` method for this under the hood and this method returns null if the entry has not been found. With the current implementation someone would get wrong warnings in Visual Studio like this:

![grafik](https://user-images.githubusercontent.com/12882255/90400476-d158d000-e09c-11ea-92c4-94e56483c859.png)

**Comment by fiseni** [comment]
Hey @mrukas 

Yes, you're right. We're not fully supporting it, just fixed the initial warnings. All public constructs should be analyzed and updated accordingly.

Want to work on this issue? If you're not available, I'll try to fix it for the weekend maybe.

**Comment by mrukas** [comment]
@fiseni
I can fix these things and submit a pull request. But I am not sure if this will happen before the weekend.

**Comment by mrukas** [comment]
@fiseni @ardalis 
Is there a reason why you avoid project references? Usually visual studii recognizes tjose and references them as nuget dependencies if you publish both separately.
Link

**Comment by fiseni** [comment]
Thabks, that's great. As I said, I'd love not to, I just wasn't sure if that would work. This section in the link clarifies that (I've missed this)

> If a referenced project includes a .nuspec file of its own, then NuGet adds that referenced project as a dependency instead. You need to package and publish that project separately.

We should try it. We just to fix the project build order for the solution.

**Comment by mrukas** [comment]
It works really great. I've done that already. I just wanted to ask because i saw that my changes didn't get recognized.

**Comment by fiseni** [comment]
Great. If @ardalis is Ok with it, you can add additional commit in the PR where you remove the nuget package and add project ref instead.

**Comment by ardalis** [comment]
I have nothing against project references, I just didn't think they worked well for dependencies between Nuget packages. For instance, how does Nuget decide which version to use, since project references aren't versioned?

**Comment by fiseni** [comment]
That's good point. I just did some quick tests. If you add the project reference (instead of nuget dependency), this is the nuspec generated for the EF package (nuspec is located within the .nupkg file in the bin folders).

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Ardalis.Specification.EntityFrameworkCore</id>
    <version>4.0.0</version>
    <title>Ardalis.Specification.EntityFrameworkCore</title>
    <authors>Steve Smith (@ardalis),Scott DePouw</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <icon>icon.png</icon>
    <projectUrl>https://github.com/ardalis/specification</projectUrl>
    <description>EF Core plugin package to Ardalis.Specification containing EF Core evaluator and abstract repository.</description>
    <releaseNotes>New API for building the specifications.</releaseNotes>
    <tags>spec specification repository ddd ef ef core entity framework entity framework core</tags>
    <repository type="git" url="https://github.com/ardalis/specification" commit="d237a864fcba656fa8ed09f6759bd49ac0c56964" />
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Ardalis.Specification" version="4.0.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.EntityFrameworkCore" version="3.1.6" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

As we can see, indeed the project ref is converted into nuget package dependency. But, the referenced version is defined as the version written under the base project file. More precisely, whichever version is defined within the generated nuspec file of the base project.

```
  // Whatever we write here in the base project file, will be translated into version of the nuget dependency in EF package
  <PropertyGroup>
    <Version>4.0.0</Version>
  </PropertyGroup>
```

So, if you just write a version 5.0.0, that will be picked up, even though that version is still not available on nuget.org. Probably it's not a big issue, but whenever we do changes in both projects, base package should be published first to nuget.org, and only then the EF package.

We can't reference older versions, though. I'm not sure if we need that at all, can't think of a specific case now.

**Comment by mrukas** [comment]
I think this sounds like a bigger problems than it will be. I tried it with a sample solution that looks like this: 
![grafik](https://user-images.githubusercontent.com/12882255/91231884-5d6a9780-e72e-11ea-953f-c0e2b184fa25.png)

The parent library has the version 2.1.0 and is referenced by the child library. If you now package the child library as a nuget package, the dependency gets translated to this:
![grafik](https://user-images.githubusercontent.com/12882255/91232045-a1f63300-e72e-11ea-8546-326be7ca238d.png)

So in fact nuget does not pin this to a specific version but uses the following resolution algorithms: [Link](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution)

As written in the document the version downloaded should be the lowest applicable version it can find. That would mean as long as your ef package references for example version 4.0.0 of you base package it should only install version 4.0.0 as long as you're not manually installing a newer version of it.

How do you currently increase the versions of your packages? Is this done by the CI/CD pipeline of do you increase them manually? 
The only problem i can think of is when you increase the version of your base package and your ef package, but you only publish your ef package. This would lead to a dependency that could not get fulfilled i think. But this shouldn't be the case right? 😁

**Comment by ardalis** [comment]
That's actually great news, thanks! What we've been doing is having the primary/base package deploy first (with manual version update to project file), and then CI/CD publishes it. This takes 5-10 minutes typically. Then we update the dependent projects to use the new version (manually) and make whatever updates are needed to them, and then publish them using the same process.

It sounds like just using project references everywhere should let us make version updates that impact multiple related packages in a single commit. Nice!

**Comment by fiseni** [comment]
The PR #14 is merged. Additionally, the project is updated to use project references instead of nuget package.
Closing the issue.
