### ISSUE TITLE
Public endpoint for IQueryable

### ISSUE THREAD

**Issue by Grentry** [ardalis/Specification#429]
Hi,

I use this project a lot and it is really nice, at some point it would be really useful to get the Queryable instead of the list for pagination for example.
Would it be possible to expose an endpoint like AsQueryable?

best regards

**Comment by fiseni** [comment]
Hi @Grentry,

I assume you're talking about repositories. You can extend those repositories and add the methods you want. We do not plan to explode the `DbSet` or `IQueryable`. The whole concept of the repositories doesn't make much sense if you expose it.

PS. The repositories are just provided as a sample. The library is focused on specifications. Whether you use specs with repositories or you evaluate them on top of IQueryable it's up to the consumers.
