### ISSUE TITLE
GetBySpec with select missing

### ISSUE THREAD

**Issue by mrukas** [ardalis/Specification#43]
I noticed that there is a `Task<T> GetBySpecAsync(ISpecification<T> specification)`.
Shouldn't there also be a `Task<TResult> GetBySpecAsync<TResult>(ISpecification<T, TResult> specification)`.

Otherwise the select is not working when returning a single entity given a specification.

**Comment by fiseni** [comment]
We have added only `ListAsync` for Select functionality. I assume a lot of people want to use Select with single entity, so we may add overload for `GetBySpecAsync` as well. Perhaps we might create new `SelectNotFoundException`, not to throw base `Exception` here.

[RepositoryBase](https://github.com/ardalis/Specification/blob/master/ArdalisSpecificationEF/src/Ardalis.Specification.EF/RepositoryBase.cs) is just an optional base repository, users are not enforced to use it. But, yea would be nice to cover all usages.

**Comment by ardalis** [comment]
Agreed. We also need to work on some more documentation for how to use the library, both with the built-in RepositoryBase and without it. I don't see any reason not to add this as an option for the built-in one, to show how it would work. Do you want to submit a PR, @mrukas ?

**Comment by mrukas** [comment]
@ardalis 
I will try to submit a PR in the next days if I find the time. :)

**Comment by fiseni** [comment]
@mrukas, I added this now, along with the other changes.
Closing the issue.

**Comment by mrukas** [comment]
@fiseni 
Perfect! Thanks!
