### ISSUE TITLE
Using SpecificationBuilder for nested sublcasses

### ISSUE THREAD

**Issue by dgeller-OUHSC** [ardalis/Specification#430]
Given the example class below:

```
public class FooSpec : Specification<Foo>, ISingleResultSpecification<Foo>
{
  public FooSpec WithMultipleBarElementsSaturated()
  {
          Query.Include(q => q.Class1).ThenInclude(q => q.SubClass1);
          Query.Include(q => q.Class1).ThenInclude(q => q.SubClass2);
          Return this;
  }
}
```

Two questions: 

1. What are the performance implications (if any) for the duplicated Class1 Include statements?
2.  Is there a better way (or can one be developed) to compress those queries? Something like:

`Query.Include(q => q.Class1).ThenInclude(q => q.SubClass1).AndInclude(q=>q.SubClass2)`

**Comment by ardalis** [comment]
This is really an EF (Core) question, as that's where this will be implemented (typically).

I tried a quick google search of "performance impact ef core multiple duplicate includes" but didn't find anything. I expect EF Core would *not* add another join for no reason but you'd probably have to test and benchmark it yourself.
