### ISSUE TITLE
How can I filter the included entity?

### ISSUE THREAD

**Issue by abircan** [ardalis/Specification#49]
According to this [documentation ](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include), filtering is possible when including with the ef core.

I checked the repo and from what I saw this feature was not added (or I could not see it).

I wonder what kind of solutions those who use the repo have come up with for such situations.

@ardalis do you plan to add this feature too?

**Comment by abircan** [comment]
Sorry everbody,
This feature comming on EF 5 [documentation](https://docs.microsoft.com/en-us/ef/core/querying/related-data#filtered-include) .

**Comment by fiseni** [comment]
Filtered Includes were a desired feature for very long in Entity Framework. They have been added in EF Core 5 (RC1 is released just few days ago). Once we have final release, we may add a plugin package for that as well.

**Comment by abircan** [comment]
Thanks @fiseni

**Comment by mohdali** [comment]
Hi, was a plugin package created for this?
