### ISSUE TITLE
Is there any way I can OrderBy a SmartEnum name?

### ISSUE THREAD

**Issue by RandomUser99** [ardalis/Specification#50]
Hi,

So I'm using both this library in addition to Steve's SmartEnum. I have a SmartEnum Status class in my .Net CORE 3.1 project:

 ```
public class BookingStatus : SmartEnum<BookingStatus>
    {
        public string ShortName { get; }
        public bool IsConfirmed { get; }
        public StatusUpdateType UpdateUpdateType { get; }

        public static readonly BookingStatus Submitted = new BookingStatus("Booking request submitted", "Submitted", 0, false);
        public static readonly BookingStatus Confirmed = new BookingStatus("Booking confirmed", "Confirmed", 1, true);
        public static readonly BookingStatus Cancelled = new BookingStatus("Booking cancelled", "Cancelled", 2, false);
        public static readonly BookingStatus ConfirmedDateChanged = new BookingStatus("Confirmed date amended", "Confirmed date amended", 3, true, StatusUpdateType.LogOnly);

        private BookingStatus(string name, string shortName, int value, bool isConfirmed) : base(name, value)
        {
            ShortName = shortName;
            IsConfirmed = isConfirmed;
            UpdateUpdateType = StatusUpdateType.LogAndUpdate;
        }
    }
```

I also have a Specification class which I want to OrderBy the BookingStatus.ShortName property. EF doesn't like this in 3.1 due to the error "Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly".

I could do this client side using LINQ, but I am using the Skip() and Take() feature of this library for pagination, so I cannot order client side as the results set is incorrect

Is there any way around this or force my query to use client side evaluation or another solution possibly?

Thanks.

**Comment by fiseni** [comment]
Hi @RandomUser99,

I haven't used SmartEnum extensively and I don't know if it has support for EF persistence, @ardalis will answer you on that.
As for the specifications, whatever you define within a spec, everything will be sent to the ORM, and the translation is done on the ORM. So, you have to be careful while building the specs, and be aware what can be translated to an actual query and what not. The last version of EF Core 5, is quite powerful and will translate quite complex stuff. But, still there are limitations.

Lately, based on my own experience, I've been thinking to incorporate the capability for InMemory operation in specifications. As a matter of fact, the specifications will just hold the information what to be executed after data is retrieved from persistence.
The usage might something like this
```
public class CompanySpec : Specification<Company>
{
    public CompanySpec(int countryId)
    {
	Query.Where(x => x.CountryId == countryId)
             .Include(x => x.Stores);

        Query.InMemory.Where(x => x.Name.Length > 10);
    }
}
```

But, in this case the Repository also should be a bit "smarter", and should know what to after the data is retrieved. As an example, the ListAsync method will have the following implementation

```
public async Task<List<T>> ListAsync(ISpecification<T> specification)
{
    return await ApplySpecification(specification).ToListAsync().ApplyInMemoryConditions(specification);
}
```

We might refine this idea, but if there is an interest for this, we might think of implementing it.

**Comment by RandomUser99** [comment]
Hi @fiseni,

SmartEnum persistence using EF works fine and I have been using them together for a while with no issues. 

The capability for InMemory operations sounds good as it gives this library more versatility when you do hit a wall with something that needs to be done client side like I have found here.

For now, I have resolved my issue by writing my some T-SQL and using dapper to do the leg work.

Appreciate your response.

**Comment by fiseni** [comment]
I gave a second thought to this, and did some internal tests.
For InMemory manipulations, probably we shouldn't complicate and construct complex builders. Specification can simply hold predicate `Func<List<T>, List<T>>`. We will pass the result of the query, manipulate the list as we wish, and just return a list as a final result.
The usage would be as following

```
public class CompanySpec : Specification<Company>
{
    public CompanySpec(int countryId)
    {
        Query.Where(x => x.CountryId == countryId)
             .Include(x => x.Stores);

        Query.InMemory(x =>
        {
            // Here you are not constrained to the specification builder.
            // You can use everything that .NET offers in order to manipulate List
        });
    }
}
```

And, the way you will actually materialize and make use of this is as following

```
public async Task<List<T>> ListAsync(ISpecification<T> specification)
{
    var queryResult = await ApplySpecification(specification).ToListAsync();
    return specification.InMemoryAction(queryResult);
}
``` 

I think this will offer complete new usage for specifications. No longer will be used primarily for querying data, but it can be used for holding business rules and acomplish various business manipulations.

@ardalis any thoughts on this? Would you like this as a part of the package?

**Comment by ardalis** [comment]
Sure, let's include it. Maybe you and I can do a stream just going through some of these newer features and usage scenarios some time soon and link to the recording on the README.

**Comment by fiseni** [comment]
Sure, we can do that!

**Comment by fiseni** [comment]
Hey @RandomUser99,

I'm closing this issue. We added support for `InMemory` feature. It doesn't solve your problem completely, but it offers the capability of client-side ordering. In order to be correctly translated, I do think we have to provide better support in `SmartEnum` project (my guess, not quite sure).
