### ISSUE TITLE
Skip not working together with Include

### ISSUE THREAD

**Issue by fingers10** [ardalis/Specification#51]
I have `one-to-many` relationship configured in my entities. I'm trying to Include parent entity from child entity and also doing pagination. But I'm getting compile time error as shown below

> 'IIncludableSpecificationBuilder<ItemEntity, CategoryEntity>' does not contain a definition for 'Skip' and no accessible extension method 'Skip' accepting a first argument of type 'IIncludableSpecificationBuilder<ItemEntity, CategoryEntity>' could be found (are you missing a using directive or an assembly reference?)

**Item Entity:**
```c#
public sealed class ItemEntity : BaseEntity
{
    public ItemName Name { get; private set; }
    public ItemCode Code { get; private set; }
    public ItemBarCode BarCode { get; private set; }
    public ItemHsnCode HsnCode { get; private set; }
    public ItemQuantity Quantity { get; private set; }
    public Money UnitPrice { get; private set; }
    public Money Tax { get; private set; }
    public bool TaxIncludedWithPrice { get; private set; }
    public bool Product { get; private set; }

    public Guid CategoryId { get; private set; }
    public CategoryEntity Category { get; private set; }
}
```

**Specification:**
```c#
public class ItemFilterPaginatedSpecification : Specification<ItemEntity>
{
    public ItemFilterPaginatedSpecification(int skip, int take,
        string? itemName, string? itemCode)
        : base()
    {
        Query
            .Where(c => (string.IsNullOrWhiteSpace(itemName) && string.IsNullOrWhiteSpace(itemCode)) ||
                        (c.Name == itemName) || c.Code == itemCode)
            .Include(c => c.Category)
            .Skip(skip)
            .Take(take);
    }
}
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/43729469/96357299-c8759080-1117-11eb-9c4a-e34c31571bbe.png)

Please assist on what I'm doing wrong?

**Comment by fiseni** [comment]
Hi @fingers10,

In case of `Include` and `Order` functionalities, once you enter the second level, you can use only "Then" definitions, so you have to start over with `Query`. Refer to #41 for more details. 
Actually, even while writing it, the intellisense won't list you anything other than `ThenInclude`. So, this is what you'll need to do
```
Query.Include(c => c.Category);
Query.Skip(skip)
     .Take(take);
```

Other than that, I'd strongly recommend not to use unnecessary conditions as part of `Where`. For an instance, `string.IsNullOrWhiteSpace(itemName)` has nothing to do with the query itself, it's just validating the argument. Keep it simple, and try not to push the limits of the ORM.

You might write the specification as following

```
public class ItemFilterPaginatedSpecification : Specification<ItemEntity>
{
    public ItemFilterPaginatedSpecification(int skip, int take,
        string? itemName, string? itemCode)
    {
        if (!string.IsNullOrWhiteSpace(itemName) && !string.IsNullOrWhiteSpace(itemCode))
        {
            Query.Where(c => c.Name == itemName || c.Code == itemCode);
        }

        Query.Include(c => c.Category);
        Query.Skip(skip)
             .Take(take);
    }
}
```

**Comment by fingers10** [comment]
@fiseni Many thanks for the support and inputs
