### ISSUE TITLE
Answers to some common questions!

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#60]
This is not an issue per se. I'll just try to provide some additional information and answer some questions I received regarding the topics we had in the following [stream](https://www.youtube.com/watch?v=BgWWbBUWyig).

### Does the use of filters break the Open-Close Principle?

This is a totally valid question. If the intention by using the specifications is to conform to this principle, then by adding the concept of filters, aren't we doing the opposite? We go back and update the specification by adding additional conditions.
As a brief recap, the OCP predicates that we should have constructs that are open to extensions and close to changes. This means, if we need to add a "behavior" to a class, we should be able to do that without changing the class itself. Even more simplified, if you have switch statements and too many conditional logic; it might be a sign that the behavior is too much hardcoded, and might be refactored in a better way.

In our case, indeed we have too many conditions within the specification, so this concern is partially true. The catch here is that we have to do with single and atomic business requirement. The user has demanded from us that we change the behavior and add an additional condition by which the customers can be queried. The requirement is that the filters on the customer's UI page be extended. Whenever you have business requirement changes, undoubtedly you will have code changes in the domain model as well. That particular specification will change only when this exact business requirement changes, and never otherwise; it's wired up to this functionality only. Even though not the perfect structure, I might say it's an acceptable solution.

This is quite different from the case when you have to change/add/delete behavior in a "classic" repository, in which case in order to update one business requirement, you're forced to update a construct that holds a collection of business requirements. That clearly violates SRP and OCP.

### Why using `ThenInclude` in one instance broke the application? What is the proper usage?

In one instance, while describing different usages we updated the specification by adding `ThenInclude` (as shown below), which in turn resulted in a runtime error.

```
Query.Include(x => x.Stores).ThenInclude(x => x.Address);
```

The error here has to do with the fact that `Address` property is not navigation, but a string property. Obviously, you should not include simple properties. And, this is the same behavior that you will have by using EF directly. Including simple properties won't result in a compile-time error but a runtime error. It's up to you to be careful, make proper usage of it, and thoroughly test your queries.
We can constrain this usage and throw an exception, but we don't want to alter the behavior that much. What if the EF in some further version makes use of this usage? So, the ultimate usage constraints should be the responsibility of the ORM you're using.

### How many Include statements are OK to have?

This is not directly related to this package, but I'll try to answer anyhow.
While creating JOINs in SQL, the real issue is not about how many tables, but the cardinality. If the dependent tables are configured as one-to-one relationships, that's quite OK. But if you're including dependent tables, where there are many rows for each principal row, then it can have quite an impact on the performance. On top of that, you should be careful what SQL queries are being produced by EF as well. The EF Core 1&2 uses split queries, while EF Core 3 uses a single query. If you have a lot of 1:n relationships and use a single query, then you might end with a "cartesian explosion" (consider split queries in these cases).

During the stream, I showcased the following specification, and the question was if this is OK?

```
public class AwbForInvoiceSpec : Specification<Awb>
{
    public AwbForInvoiceSpec(int ID)
    {
        Query.Where(x => x.ID == ID);
        Query.Include(x => x.Packages);
        Query.Include(x => x.AwbCargoServices);
        Query.Include(x => x.AwbPurchase);
        Query.Include(x => x.CargoManifest);
        Query.Include(x => x.Customer).ThenInclude(x => x.Addresses);
    }
}
```

In the context of that particular application, the `Awb` has quite significant importance in the overall business workflow, and it might be a bit more complicated than it should be. First of all, the `AwbPurchase` and `CargoManifest` represent 1:1 relationships. So, we end up with two 1:n navigations. This is relatively OK if you're retrieving one Awb record (as in this case). On the other hand, if you're trying to get a list of records, then you should reconsider if you need the child collections or not. Try to measure the performance, consider the usage of the application, number of users, peak usages, etc, and then you can decide if that meets your criteria or not.

### Anti-pattern usage

In the above example, the actual anti-pattern is not the usage of several Include statements, but including the `Customer`. That implies that Awb aggregate has direct navigation to the `Customer` aggregate. If you follow DDD, you should strive to have as independent aggregates as possible. If required, one particular aggregate should hold only the identifier of some other aggregate root and not have a direct reference.

In our case, it was a deliberate design decision to break this rule (for `Customer` aggregate), in order to improve the performance in particular cases and to reduce roundtrips to DB. But, it's not something I would advise you to do. Anyhow, it's up to you to weigh the pros/cons and make your own elaborate decisions for your applications.

### Do I need private constructors for the entities (e.g. for the EF code-first approach)

I got this question related to one particular scenario which happened during the stream. Once we added the `DateTime birthdate` parameter in the constructor, we were forced to add an additional parameterless constructor so the EF could work properly.

EF requires a parameterless constructor, so it can create the instance of the entity and then populate the properties. So, it might be wise always to add one private parameterless constructor.
In our case it was working totally fine without it since all the parameters were of type `string`, and EF could just pass `null` values while creating the instance. But, once the DateTime parameter was added, that was no longer true, EF no longer could create the instance.

**[EDIT]**
The above explanation is completely wrong :), so just ignore it.
It turns out EF is smart enough to utilize the constructor and will try to pass the values as ctor arguments. That's how EF handles the immutability (if your props have only getters). But, the ctor arguments should be named the same as the properties. The first character can be lowercase, and that's ok, EF will map to it correctly. But, the case of the rest of the characters should be exactly the same. So, in our case, if we have named the argument `birthDate` instead of `birthdate`, would have worked with no issues.

```
public Customer(string name, string email, string address, DateTime birthdate)
{
    Guard.Against.NullOrEmpty(name, nameof(name));
    Guard.Against.NullOrEmpty(email, nameof(email));

    this.BirthDate = birthdate;
    this.Name = name;
    this.Email = email;
    this.Address = address;
}
```

**Comment by ardalis** [comment]
We should put this somewhere more accessible and discoverable, and link to it from the README where we mention the stream recording. What do you think about using a wiki in this repo, or perhaps posting this on your blog? Or as a guest post on my blog if you'd rather?

**Comment by fiseni** [comment]
Sure, please use it as you wish. In your blog or wherever you find it convenient.

Honestly, I was lazy, the easiest way was just to post it as an issue :)

**Comment by ardalis** [comment]
Included in README

**Comment by vzehirev** [comment]
Hi! Not sure how I stumbled upon this, but since I'm here, will ask. I have a big amount of data, which can't be loaded and filtered/sorted entirely on the client. However, very specific to the grid plugin, which I'm using filters/sorts are being applied and send to the API. These filters/sorts should eventually go to the specification, which is in my domain project, so the query can be build, but in this case my domain will start knowing about and using filters/sorts entirely dependent on the front-end. I think of building such client-related specifications in the web app and passing it to the domain, or using some complex reflection to build the queries dynamically. What would you suggest? Thanks!

**Comment by fiseni** [comment]
If I understood correctly, you have some filter object and your concern is where to place it?
It all depends on your solution structure. First of all, I want to emphasize that you can have one single project and still do DDD. Having multiple projects is not a prerequisite for DDD. Clean/onion/hexagonal architecture is just a convenience let's say, it will force you to clearly separate your domain model. If you follow such a structure, then you have a few options:
- Keep your filter objects in your Core project, and directly reference them from your UI layer (web/desktop whatever it is). These are dummy objects (with no behavior) and there is no issue if you use them from your UI layer directly.
- Have copies of these objects in both UI and Core projects, and then you map them back and forth. We have a sample app within this repository, and we've used this approach. You can find the code snippet [here](https://github.com/ardalis/Specification/blob/66c2d90be82f3e77556040c944c4f1fa6f3e4039/sample/Ardalis.SampleApp.Web/Services/CustomerUiService.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L56)
- Have a common project where you place all these filter constructs. I really don't prefer this.

Let me know if this helps.

**Comment by vzehirev** [comment]
Hi! Thank you very much. I have the current dilemma: Front-end is using Angular with PrimeNG tables, these tables have some very specific filters, which are kind of: First name "contains" something, or Email "equals" something, etc. When I query the database I should do something like: if (firstNameFilter == "contains") Query.Where(x => x.FirstName.Contains(something)). The query is in the specification, the specification is in the domain model, the filters ["contains", "equals", etc.] are strongly specific and coming from the native PrimeNG tables and I'm in the case of my domain model getting coupled and understanding the UI, because the domain model should know what is filter = "contains", or filter = "equals", or filter = "notEquals", etc. If tomorrow I decide to change the UI and use another grid solution, its filters might be "isEqual", or "isContains" and then I should change my domain model logic.

**Comment by fiseni** [comment]
Oh OK. When I was referring to the UI layer, I meant it from a backend perspective, and in that case, that's the controllers. Your question is actually broader. You have a SPA and you wanna know how to make the frontend (Angular) and backend completely independent. The answer is: <strong>not possible</strong> 😄 I mean, technically the code may be completely separate, but inevitably you'll have an "implicit coupling", you must define which side will "lead" the API design. Either the frontend will adapt to the exposed backend API, or you'll design the API based on the frontend wishes!
What's the alternative? Well, we as industry love standards 😄 You let the standard be a "thing", and then both the frontend and backend comply with the standard specification. There is no right or wrong way of doing it. You can come up with your own internal rules, or you just try to adopt some of the industry-accepted standards for queryable APIs (e.g. OData).

We had a similar discussion in [this issue](https://github.com/ardalis/Specification/issues/121#issuecomment-830890194)
> That said, your problem is not the specifications, or any other backend construct you might have. The real problem you have is the API design. Once you crack that down, the rest would follow naturally. Your requirement actually is designing queryable APIs. You do not necessarily should implement it if you don't like it, but you can look and adopt some ideas from GraphQL. Also, OData is all about that, creating and consuming queryable and interoperable RESTful APIs. So, you certainly can steal whatever you like from those concepts.

**Comment by vzehirev** [comment]
Thank you very much for the information and attention. All the best wishes!

**Comment by JorgePinetta** [comment]
Thanks, great article.
