### ISSUE TITLE
Cast specification 

### ISSUE THREAD

**Issue by lehoangphan** [ardalis/Specification#61]
If 

```
Dog : Animal
``` 

So are there some way to cast/convert/parse 

`Specification<Animal> to Specification<Dog> ?`

Thanks!

**Comment by fiseni** [comment]
Hi @lehoangphan,

There is no straightforward way of doing that. I'm not even sure how EF would behave in that case. Also, we might need contravariant generics.

Can you explain what is your use case and why would u need that?

**Comment by ardalis** [comment]
Closing this - feel free to reopen if you want to keep discussing.
