### ISSUE TITLE
How to use Caching here?

### ISSUE THREAD

**Issue by fingers10** [ardalis/Specification#63]
I can see options for caching in `ISpecification` like `CacheEnabled` and `CacheKey`. Please can you assist with any examples or docs?

**Comment by fiseni** [comment]
If I'm not wrong, I think there is a usage example in EShopOnWeb project.

Anyhow, we'll work on better documentation, and improve the sample app here. This month I'm quite tight with deadlines. Once I find some free time, I'll try to help.

**Comment by ardalis** [comment]
I don't know that we have a full sample. I would use it with my CachedRepository pattern:
https://ardalis.com/building-a-cachedrepository-in-aspnet-core/

Like @fiseni said, though, we can try and add a sample showing it here.

**Comment by ardalis** [comment]
I updated the sample to show how to use caching with a cachedrepository.

See #65 

See also https://github.com/ardalis/CachedRepository and https://ardalis.com/building-a-cachedrepository-in-aspnet-core/
