### ISSUE TITLE
running Raw queries inside specification

### ISSUE THREAD

**Issue by Itsamirmasoud** [ardalis/Specification#68]
Hi, I have a case where i need to access the [FromSqlRaw](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) on DbSet in order to get the result i need.

apart from passing the dbset to specification as a parameter is there a way to do this?

**Comment by fiseni** [comment]
I don't think you should be doing this through specifications.
1. The whole point of specifications is to create ORM independent abstractions. You shouldn't have DbSet inside the spec. Generally, you shouldn't reference EF namespaces. If you do it, then it defies the purpose.
2. Even if you pass the DbSet as a parameter, there is nothing you can do with it. While creating the specification, you are simply just populating a list of information (It's a data bag). No action is taken at that moment. The action happens in the repository. By using the specification evaluator it tries to read the information in the spec and to evaluate into a query.

What you can do is create a custom repository in your infrastructure project, accept DbContext in it, and add methods that fully utilize the EntityFramework. Then, you can keep the interface of that repository in your domain model (e.g. core project). There is nothing wrong with doing that.

**Comment by ardalis** [comment]
Agreed with @fiseni. You should just bypass the specification in that case.

Usually what you need in this case is a separate read model because you're just executing a query, not trying to get back your domain model. It often causes folks a lot of pain trying to use a custom query that returns their domain model, when using a custom read model that's designed to fit the needs of the use case and query involved works much easier. If this doesn't sound like a good fit for your design, please share more about the scenario you're envisioning and we can see if we have other ideas.

**Comment by Itsamirmasoud** [comment]
@ardalis @fiseni 
Thank you for your help!

In my case, my project does not have a repository, I'm kinda with the group who believe entity framework is a repository on itself so moving it to a repository is not an option. up until now we had a set of extension methods on DbContext and that is where we put the shared logic since there were not that much shared logic but, as always it started growing.

So, as i was looking for a solution to gather all these repeated code and make it look like something more decent and maintainable, when I came across this [article ](https://gunnarpeipman.com/ef-core-query-specification/).

what I'm trying to do here is to use specification to gather all the shared logic and put it in one place. now, as it happens some of this queries are raw queries due to the importance of the performance.

**Comment by ardalis** [comment]
The repository pattern is all about the _abstraction_, not the implementation. EF is an implementation, and thus not a repository by definition (though you can implement your abstraction with EF if you so desire).

Extension methods work great for many things but aren't as extensible or flexible as some other options in C#. It sounds like you're starting to hit the point where you're feeling that.

I've read the article you cited - it's a reasonable approach (aside from the usual misinformation about repositories and EF ;) ). Hopefully you can leverage it for your needs.

If you do opt to leverage this package, I don't see why you couldn't just inherit from our base class and add a RawSQL property. Then if that property is set, use it via your DbContext to execute your query. Do you need something more than that?

**Comment by Itsamirmasoud** [comment]
> If you do opt to leverage this package, I don't see why you couldn't just inherit from our base class and add a RawSQL property. Then if that property is set, use it via your DbContext to execute your query. Do you need something more than that?

As a matter of fact i did think about doing this and creating my own customized version. but i was not sure if it is the right thing to do or maybe even i am missing something from your package  or it's usage entirely... so i though i ask a couple of expert first.

thanks for the help.

P.S : let's just agree to disagree on the subject of EF and repositories ;)

**Comment by ardalis** [comment]
Sure thing. Good luck!
