### ISSUE TITLE
How to cast from Specification<DomainEntity> to Specification<DBEntity> where DBEntity derives from DomainEntity

### ISSUE THREAD

**Issue by hesperanca** [ardalis/Specification#69]
Hi,

I'm trying to use the library to connect to a CosmosDB database in a  "Clean Architecture" solution. The database is using database entities (implemented in the infrastructure layer) that are derived from the domain entities (implemented in the domain layer).  The DB entities contain extra properties like "DataType" (so that we can differentiate from other entities stored in the same Cosmos DB container). 

The problem that I have is that the Specification object is defined in the application layer using domain entities but the repositories, in the infrastructure layer, need to be able to convert them into Specification objects using DB entities ( the repos need to add a value to the "EntityType" field in the DB entity). Any ideas on how we can convert from `Specification<DomainEntity>` into `Specification<DBEntity>`? 

Many thanks.

**Comment by fiseni** [comment]
Hi @hesperanca 

Simply, you can't do that in elegant way. More specifically you can't do that in the specifications, since your `DomainEntity` doesn't contain that extra field in order to filter by it.
What you can do is tweak the specification evaluation (which is done in the infrastructure layer), and add that extra condition after the evaluation of `Where` expressions. Although, the casting might be a bit tricky. Not sure, but probably you will need something like this
```
if (typeof(T) == typeof(DBEntity))
{
	query = query.Where(x => ((DBEntity)(object)x).EntityType = "something");
}
```

**Comment by hesperanca** [comment]
Hi @fiseni 

Many thanks for your answer. I'll try your suggestion. 

The original specification object is created in the application layer and it doesn't know anything about the extra "EntityType" field. I'm only applying the extra filtering for "EntityType" in the repository. I will try your suggestion (the specification evaluation is called by the repository base class) to see if it works and will post the results here just in case it helps someone else.

Many thanks for your help.

I'll give

**Comment by fiseni** [comment]
Just make sure to add those criteria before any Search or Pagination expressions, right after the `Where` expression evaluations in this file [SpecificationEvaluator](https://github.com/ardalis/Specification/blob/master/ArdalisSpecificationEF/src/Ardalis.Specification.EF/SpecificationEvaluator.cs).

**Comment by fiseni** [comment]
Hey @hesperanca,

Did the suggestion work for you? Closing the issue due to inactivity. If you have any further questions let us know.

**Comment by hesperanca** [comment]
Hi @fiseni ,

Yes your suggestion worked. Many thanks. To avoid that nasty casting I've created a new SpecificationEvaluator using generics to filter on the extra properties of the DBEntity.  I'm copying the code below in case it may help someone.

` public class DbSpecificationEvaluator<T, C> where C : IDBEntity, T
    {
        public virtual IQueryable<T> GetQuery(IQueryable<T> inputQuery, ISpecification<T> specification)
        {
            IQueryable<T> query = inputQuery;

            foreach (Expression<Func<T, bool>> criteria in specification.WhereExpressions)
            {
                query = query.Where(criteria);
            }

            query = query.Where(x => ((C) x).EntityType == typeof(C).Name);

            // Need to check for null if <Nullable> is enabled.
            if (specification.OrderExpressions != null)
            {
                if (specification.OrderExpressions.Count(x => x.OrderType == OrderTypeEnum.OrderBy ||
                                                              x.OrderType == OrderTypeEnum.OrderByDescending) > 1)
                {
                    throw new DuplicateOrderChainException();
                }

                IOrderedQueryable<T>? orderedQuery = null;
                foreach ((Expression<Func<T, object>> KeySelector, OrderTypeEnum OrderType) orderExpression in specification.OrderExpressions)
                {
                    if (orderExpression.OrderType == OrderTypeEnum.OrderBy)
                    {
                        orderedQuery = query.OrderBy(orderExpression.KeySelector);
                    }
                    else if (orderExpression.OrderType == OrderTypeEnum.OrderByDescending)
                    {
                        orderedQuery = query.OrderByDescending(orderExpression.KeySelector);
                    }
                    else if (orderExpression.OrderType == OrderTypeEnum.ThenBy)
                    {
                        orderedQuery = orderedQuery.ThenBy(orderExpression.KeySelector);
                    }
                    else if (orderExpression.OrderType == OrderTypeEnum.ThenByDescending)
                    {
                        orderedQuery = orderedQuery.ThenByDescending(orderExpression.KeySelector);
                    }
                }

                if (orderedQuery != null)
                {
                    query = orderedQuery;
                }
            }

            // If skip is 0, avoid adding to the IQueryable. It will generate more optimized SQL that way.
            if (specification.Skip != null && specification.Skip != 0)
            {
                query = query.Skip(specification.Skip.Value);
            }

            if (specification.Take != null)
            {
                query = query.Take(specification.Take.Value);
            }


            //Include expressions will be evaluated within the EF implementation package.

            return query;
        }
    }`
