### ISSUE TITLE
Allow specifying QuerySplitBehaviour for specifications

### ISSUE THREAD

**Issue by ConnerOrth** [ardalis/Specification#77]
When retrieving one-to-many EFCore starting from v5 allows us to specify whether or not we want to execute the query as a single statement or as a split statement.
see: [MS docs on split-queries](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#split-queries)

Currently at the dbcontext-level we are able to set this globally.
Would like to be able to set this per specification.

What are your thoughts on this, @ardalis ?

Copied over from [Ardalis/Specification.EFCore](https://github.com/ardalis/Specification.EFCore/issues/1) due to that repo no longer being maintained, and this repo might be more suited to handle this request. @fiseni

**Comment by ConnerOrth** [comment]
Comments from original ticket, see image below.
![image](https://user-images.githubusercontent.com/10193903/106801902-91919f00-6662-11eb-9853-203c9bcfeb4c.png)

**Comment by fiseni** [comment]
We will implement this once we sort out issue #78.

**Comment by fiseni** [comment]
Implemented in `version 5.0.3`
