### ISSUE TITLE
Add support for EntityFramework 6 and EntityFramework Core 5

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#78]
In this issue, we should continue the discussion and decide in which way we will proceed with plugin/addon packages.
Plugin packages contain the implementation for a given ORM, more specifically, the evaluation logic for the specification and any other ORM dependent features. For now, we're providing only one package, the implementation for `EntityFramework Core 3`. We should add support for `EntityFramework 6` and `EntityFramework Core 5`.

- EntityFramework 6

<strong>Naming:</strong> The official name is `EntityFramework`, but while installing it we are aware of the version "v6". In our case, it will be something like "Ardalis.Specification.EntityFramework v1.0", the version of our package won't necessarily correspond to the version of the EF, and it may lead to confusion. I believe we should name this plugin package `EntityFramework6`.

<strong>TFM:</strong> The last version of EF is v6.4.4. This version is not compatible with .NET Standard 2.0, instead, it requires .NET Standard 2.1. I assume folks that are still using EF are the ones that are still unable to migrate to .NET Core, and still using .NET Framework (for whatever reasons, and there can be plenty). Since .NET Standard 2.1 can't be referenced by .NET Framework projects, I suggest this plugin package should target .NET Framework (the lowest supported version). Officially it can run on v4.5 and newer, but I do think v4.6.2 is the "sweet" spot in terms of stability and compatibility. But, if we want to add support for Nullable Reference Types, then I guess we have to go for v4.8.

- EntityFramework Core 5

<strong>Naming:</strong> The choices are either we create new package and name it "EntityFrameworkCore5", or we update the existing `EntityFrameworkCore` package to the latest EF Core version v5. The cons of having one consolidated package are that the users that are unable to migrate to EF Core 5 will be locked to the features that we provide up to that point. So, if we add additional features they won't be able to use them until they migrate to EF Core 5. On the other hand, the cons of having separate packages are simply having too many of them, Core, Core5, tomorrow will be Core6, and so on.

<strong>TFM:</strong> EntityFramework Core 5 is compatible with .NET Standard 2.1, so probably we should target that one.

**Comment by nelsonprsousa** [comment]
Sorry guys, I got confused. Can we use this package with .NET 5 + Microsoft.EntityFrameworkCore v5?

**Comment by fiseni** [comment]
Hi @nelsonprsousa 

Not yet. You can use it on .NET 5, but with EF Core 3.

@ardalis any feedback here? Should we just update the existing one to EF Core 5?

**Comment by nelsonprsousa** [comment]
Thanks for the feedback @fiseni,

Gonna wait for features releases 🙏

**Comment by nelsonprsousa** [comment]
btw guys, will [Filtered Include](https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include) be included?

**Comment by ardalis** [comment]
Let's split this issue between EF6 and EF Core 5 and note that the latter is done in the current v5 beta.
https://www.nuget.org/packages/Ardalis.Specification/5.0.1-beta

**Comment by fiseni** [comment]
The issue is split into two separate issues. Closing this one.
