### ISSUE TITLE
How to use specifications without a repository?

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#86]
I noticed that one of the reasons users avoid using specifications is because they don't like adding additional abstractions on top of DbContext. More specifically, they don't like repositories.
Usually, their arguments are:
- I don't like additional abstraction. I don't plan to switch the ORM anyway.
- EF is quite a powerful tool and offers quite complex features. Why would I hide all of that behind a repository and expose a minimal set of functionalities?
- I use Automapper's ProjectTo feature to map the EF queries to my models. It automatically creates select queries for me.

These are totally valid points. But, using specifications doesn't necessarily require repositories, and this fact might not be so obvious to the users. In order to mitigate this, we can define a set of extension methods to simplify this usage.

Proposed API

```c#
var specification = new CustomerSpecification();
dbContext.Customers.ApplySpecification(specification).ToListAsync();
dbContext.Customers.ApplySpecification(specification).FirstOrDefaultAsync();
dbContext.Customers.ApplySpecification(specification).Select("whatever your expression is").ToListAsync();

// in combination with AutoMapper
dbContext.Customers.ApplySpecification(specification).ProjectTo<SomeModel>(configuration).ToListAsync();

// alternatively, we can overload some of the extension methods
dbContext.Customer.ToListAsync(specification);
```

We'll just build the query to some point using specifications, and afterward, the user can use EF's methods to materialize the query or continue building the query if necessary in more complex scenarios.

**Comment by ardalis** [comment]
This is working now in the v5 branch, which is also available here:
https://www.nuget.org/packages/Ardalis.Specification/5.0.1-beta

**Comment by fiseni** [comment]
This is implemented with minor changes, as following:
- The `ApplySpecification` extension method is renamed to `WithSpecification`. It is extension to `IQueryable`. The usage is as following:
```c#
dbContext.Customers.WithSpecification(specification).ToListAsync();
dbContext.Customers.WithSpecification(specification).FirstOrDefaultAsync();
dbContext.Customers.WithSpecification(specification).Select("whatever your expression is").ToListAsync();
dbContext.Customers.WithSpecification(specification).UseWhateverExtensionsAvailableForIQueryable;
// in combination with AutoMapper
dbContext.Customers.ApplySpecification(specification).ProjectTo<SomeModel>(configuration).ToListAsync();
```
- We also shipped method overload for `ToListAsync` which accepts specification as parameter. This is necessary if you want to evaluate the `PostProcessingAction` defined in the specification. This is defined as extension method to `DbSet` not to `IQueryable` in order to avoid some missusages (what if you do `Select` first, etc). The usage is as following:
```
dbContext.Customer.ToListAsync(specification);
```

**Comment by fiseni** [comment]
We might restrict the `WithSpecification` as well to `DbSet` (the same issue with Select). It might be wiser that way. You start with DbSet, apply a specification, and then you can do whatever you want.

**Comment by fiseni** [comment]
Now that I'm thinking of it, since you can chain the `WithSpecification`, some interesting use-cases can be designed. You can apply some common specification for a given entity, and then keep building it with more specific one.

The users also could organize the specification a bit differently. Instead of naming the specs by their content, they could name them by their intended usage.

```c#
dbContext.Customers.WithSpecification(new CustomerCommonSpec())
                   .WithSpecification(new ListCustomersSpec())
                   .ToListAsync();
				   
dbContext.Customers.WithSpecification(new CustomerCommonSpec())
                  .WithSpecification(new EditCustomerSpec(id))
                  .ToListAsync();
```

where `CustomerCommonSpec` could hold some common criteria. Let's say I have 1:1 relation with `Address` table and always want to include it when retrieving the customers.

```c#
public class CustomerCommonSpec : Specification<Customer>
{
    public CustomerCommonSpec()
    {
         Query.Include(x => x.Address);
    }
}
```

**Comment by ardalis** [comment]
My only concern with this is that it might be abused in ways similar to just exposing `IQueryable`. Choosing how to stitch together multiple specifications is essentially data access logic, and we would be putting it in other places throughout the app, rather than only in the specifications themselves. Now to test if a query is correct, you can't just test a specification, but instead you must test a particular combination of specifications.

That's not to say we can't support it, but it seems like a "footgun" to me and one we would want to offer warnings about in our docs. At some point it starts to look like LINQ-but-with-strongly-typed-expressions which perhaps adds some value but isn't as nicely encapsulated as using a single specification to describe, completely, a single data operation/query.

**Comment by fiseni** [comment]
I do completely agree with you. But, probably that's valid when specs are used with repositories, and we indeed force only one specification in that usage.
But, in this case where we work directly with dbContext, you already have a leaky abstraction. You already return an `IQueryable`, and you're free to do additional stuff. Folks using this approach probably will use it exactly because of this reason.

Generally, I do agree with your sentiment.

**Comment by fiseni** [comment]
Implemented in `version 5.0.3`

**Comment by davidhenley** [comment]
Is it possible to use Automapper's `ProjectTo<>` in the specification or do you need to use the `WithSpecification` pattern?

**Comment by fiseni** [comment]
You can use the `WithSpecification` feature for that. Alternatively, you can utilize it in your base repository.
We can't include such a feature in our built-in base repository. It would be too specific to Automapper.

**Comment by davidhenley** [comment]
Thanks for all your help @fiseni !
