### ISSUE TITLE
Organize docs site

### ISSUE THREAD

**Issue by ardalis** [ardalis/Specification#87]
Consider:
- github pages
- github page + gatsbyjs
- readthedocs
-gatsbyjs/netlify/custom domain

**Comment by ardalis** [comment]
I think I could pretty easily get specification.ardalis.com working via netlify/gatsbyjs, so that's probably easiest.

**Comment by ardalis** [comment]
Actually I had already set up github pages for this purpose so we'll try that for now.

https://ardalis.github.io/Specification/

Need to figure out how to get a TOC working, next.

**Comment by ardalis** [comment]
What should be the top level organization for the docs?

- Getting Started
  - Quick Start Guide
  - Overview
  - Patterns Used
  - Frequently Asked Questions
- Features
  - Basic Specification
    - Basic Usage (how to create a specification)
    - Where
    - Take
    - Skip
    - Paging
    - Cache Support
  - Basic Repository Abstraction
  - EF Repository Base Class
    - Include
    - ThenInclude
    - AsNoTracking
- Reference
- Related Resources
  - Training
  - Videos
  - Articles
- Projects Using This
  - Microsoft eShopOnWeb Reference App
  - Pluralsight Vet Shop Sample
  - CleanArchitecture Solution Template

Maybe Extensibility?

**Comment by ardalis** [comment]
Should we document the Evaluators? They're kind of behind the scenes.

**Comment by ardalis** [comment]
Reference docs sites:

- https://docs.automapper.org/en/stable/
- https://identityserver4.readthedocs.io/en/latest/index.html
- https://autofixture.github.io/docs/quick-start/
- https://autofaccn.readthedocs.io/en/latest/

**Comment by ardalis** [comment]
Related: https://github.com/fiseni/QuerySpecification

**Comment by fiseni** [comment]
I did some modifications. What do you think?

- Getting Started
  - Quick Start Guide
  - Overview
  - Patterns Used
  - Frequently Asked Questions
- Usage
  - How to create specifications
  - How to use specifications with Repository pattern
  - How to use specification with DbContext
  - How to evaluate specification with in-memory collections
  - How to use the provided built-in abstract repositories
- Features
  - Common/abstract features
    - Where
    - Order
    - Take
    - Skip
    - Paging
    - Cache support
  - ORM specific features
    - Include/ThenInclude
    - Search
    - AsNoTracking
    - AsSplitquery
- Extensions
  - How to write extensions to specifications
  - How to create your own specification builder
  - How to extend or define your own evaluators
- Reference
- Related Resources
  - Training
  - Videos
  - Articles
- Projects Using This
  - Microsoft eShopOnWeb Reference App
  - Pluralsight Vet Shop Sample
  - CleanArchitecture Solution Template

Maybe Extensibility?

**Comment by ardalis** [comment]
Where should be put info on how to use the built-in abstract repository base class? I was thinking the repository needed its own doc(s) since it has a bunch of different methods and folks will need guidance on how they're supposed to make use of it in their own projects.

**Comment by fiseni** [comment]
We might add an overview of the usage in the "Usage" section, and then provide more details under the "Features" topic, as a separate subtopic perhaps "Built-in Repository"?

**Comment by ardalis** [comment]
Sure, that makes sense.

**Comment by ardalis** [comment]
closing this - refer to this issue if you need anything for the docs site, @ilyanaDev
