### ISSUE TITLE
Add EntityFramework6 support

### ISSUE THREAD

**Issue by fiseni** [ardalis/Specification#93]
We should add plugin/addon (we should decide how to call this packages :)) for EntityFramework6.

Naming: The official name is EntityFramework, but while installing it we are aware of the version "v6". In our case, it will be something like "Ardalis.Specification.EntityFramework v1.0", the version of our package won't necessarily correspond to the version of the EF, and it may lead to confusion. I believe we should name this plugin package EntityFramework6.

TFM: The last version of EF is v6.4.4. This version is not compatible with .NET Standard 2.0, instead, it requires .NET Standard 2.1. I assume folks that are still using EF are the ones that are still unable to migrate to .NET Core, and still using .NET Framework (for whatever reasons, and there can be plenty). Since .NET Standard 2.1 can't be referenced by .NET Framework projects, I suggest this plugin package should target .NET Framework (the lowest supported version). Officially it can run on v4.5 and newer, but I do think v4.6.2 is the "sweet" spot in terms of stability and compatibility. But, if we want to add support for Nullable Reference Types, then I guess we have to go for v4.8.

**Comment by ardalis** [comment]
I'm fine to target 4.6.2 and Net Standard 2.0, I think. But this is a low priority item (for me) so an additional package that targets EF6 is something I'd hope a community member would provide or at least assist with.

**Comment by fiseni** [comment]
Let's first complete the existing features and call it done. Once we do that, we would kindly ask @ngruson to create fresh PR for EF6. He has already PR for it #62, but should be adapted to the new changes.

**Comment by ardalis** [comment]
Right - I forgot we had that PR already. Sounds good.

**Comment by ardalis** [comment]
This is done.
