### ISSUE TITLE
Support for GroupBy in Specification?

### ISSUE THREAD

**Issue by fingers10** [ardalis/Specification#99]
I'm exploring this Repo. Do we have any example that covers GroupBy in the Specification?

**Comment by ardalis** [comment]
We are building out the docs and will be sure to cover this there:

https://ardalis.github.io/Specification/

**Comment by ardalis** [comment]
Contributions to the docs are welcome.

**Comment by fiseni** [comment]
The `GroupBy` is a complex operation. It returns `IQueryable<IGrouping<TKey, TSource>>`; and very rarely is an "independent" operation, but usually is followed by a `Select` statement. This is manageable if you're working directly with `IQueryable`, you can apply operations incrementally and build on top of the existing state of the `IQueryable`.
We don't have that luxury while storing the specification information. Also, we don't wanna over-complicate the usage nor the internal infrastructure. We don't wanna become an ORM probably :) There are a lot of complex scenarios that various ORMs support, and it would be wise to communicate directly in those cases.

**Comment by fingers10** [comment]
@fiseni Thanks for the inputs. Sounds fair. Can we close this?

**Comment by fiseni** [comment]
If you're OK then yes we can close it.
In the future, if we get many requests for this feature, we might try and find an appropriate solution for it.
